/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.Achievements;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AchievementsRecord extends UpdatableRecordImpl<AchievementsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.achievements.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.achievements.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.achievements.slug</code>.
     */
    public void setSlug(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.achievements.slug</code>.
     */
    public String getSlug() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.achievements.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.achievements.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.achievements.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.achievements.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.achievements.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.achievements.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.achievements.points</code>.
     */
    public void setPoints(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.achievements.points</code>.
     */
    public Integer getPoints() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.achievements.category</code>.
     */
    public void setCategory(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.achievements.category</code>.
     */
    public String getCategory() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.achievements.source</code>.
     */
    public void setSource(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.achievements.source</code>.
     */
    public String getSource() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AchievementsRecord
     */
    public AchievementsRecord() {
        super(Achievements.ACHIEVEMENTS);
    }

    /**
     * Create a detached, initialised AchievementsRecord
     */
    public AchievementsRecord(Long id, String slug, String name, String description, OffsetDateTime createdAt, Integer points, String category, String source) {
        super(Achievements.ACHIEVEMENTS);

        setId(id);
        setSlug(slug);
        setName(name);
        setDescription(description);
        setCreatedAt(createdAt);
        setPoints(points);
        setCategory(category);
        setSource(source);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AchievementsRecord
     */
    public AchievementsRecord(io.aeyer.voidcore.jooq.tables.pojos.Achievements value) {
        super(Achievements.ACHIEVEMENTS);

        if (value != null) {
            setId(value.getId());
            setSlug(value.getSlug());
            setName(value.getName());
            setDescription(value.getDescription());
            setCreatedAt(value.getCreatedAt());
            setPoints(value.getPoints());
            setCategory(value.getCategory());
            setSource(value.getSource());
            resetChangedOnNotNull();
        }
    }
}
