/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.AclGrants;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AclGrantsRecord extends UpdatableRecordImpl<AclGrantsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.acl_grants.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.acl_grants.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.acl_grants.resource_type</code>.
     */
    public void setResourceType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.acl_grants.resource_type</code>.
     */
    public String getResourceType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.acl_grants.resource_id</code>.
     */
    public void setResourceId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.acl_grants.resource_id</code>.
     */
    public Long getResourceId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.acl_grants.permission</code>.
     */
    public void setPermission(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.acl_grants.permission</code>.
     */
    public String getPermission() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.acl_grants.principal_type</code>.
     */
    public void setPrincipalType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.acl_grants.principal_type</code>.
     */
    public String getPrincipalType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.acl_grants.principal_id</code>.
     */
    public void setPrincipalId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.acl_grants.principal_id</code>.
     */
    public Long getPrincipalId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.acl_grants.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.acl_grants.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AclGrantsRecord
     */
    public AclGrantsRecord() {
        super(AclGrants.ACL_GRANTS);
    }

    /**
     * Create a detached, initialised AclGrantsRecord
     */
    public AclGrantsRecord(Long id, String resourceType, Long resourceId, String permission, String principalType, Long principalId, OffsetDateTime createdAt) {
        super(AclGrants.ACL_GRANTS);

        setId(id);
        setResourceType(resourceType);
        setResourceId(resourceId);
        setPermission(permission);
        setPrincipalType(principalType);
        setPrincipalId(principalId);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AclGrantsRecord
     */
    public AclGrantsRecord(io.aeyer.voidcore.jooq.tables.pojos.AclGrants value) {
        super(AclGrants.ACL_GRANTS);

        if (value != null) {
            setId(value.getId());
            setResourceType(value.getResourceType());
            setResourceId(value.getResourceId());
            setPermission(value.getPermission());
            setPrincipalType(value.getPrincipalType());
            setPrincipalId(value.getPrincipalId());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
