/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.ActivityEvents;

import java.time.OffsetDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ActivityEventsRecord extends UpdatableRecordImpl<ActivityEventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.activity_events.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.activity_events.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.activity_events.topic</code>.
     */
    public void setTopic(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.activity_events.topic</code>.
     */
    public String getTopic() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.activity_events.actor_id</code>.
     */
    public void setActorId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.activity_events.actor_id</code>.
     */
    public Long getActorId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.activity_events.payload</code>.
     */
    public void setPayload(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.activity_events.payload</code>.
     */
    public JSONB getPayload() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.activity_events.emitted_at</code>.
     */
    public void setEmittedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.activity_events.emitted_at</code>.
     */
    public OffsetDateTime getEmittedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActivityEventsRecord
     */
    public ActivityEventsRecord() {
        super(ActivityEvents.ACTIVITY_EVENTS);
    }

    /**
     * Create a detached, initialised ActivityEventsRecord
     */
    public ActivityEventsRecord(Long id, String topic, Long actorId, JSONB payload, OffsetDateTime emittedAt) {
        super(ActivityEvents.ACTIVITY_EVENTS);

        setId(id);
        setTopic(topic);
        setActorId(actorId);
        setPayload(payload);
        setEmittedAt(emittedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ActivityEventsRecord
     */
    public ActivityEventsRecord(io.aeyer.voidcore.jooq.tables.pojos.ActivityEvents value) {
        super(ActivityEvents.ACTIVITY_EVENTS);

        if (value != null) {
            setId(value.getId());
            setTopic(value.getTopic());
            setActorId(value.getActorId());
            setPayload(value.getPayload());
            setEmittedAt(value.getEmittedAt());
            resetChangedOnNotNull();
        }
    }
}
