/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.ChatRoomMessages;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChatRoomMessagesRecord extends UpdatableRecordImpl<ChatRoomMessagesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.chat_room_messages.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.chat_room_messages.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.chat_room_messages.room_id</code>.
     */
    public void setRoomId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.chat_room_messages.room_id</code>.
     */
    public Long getRoomId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.chat_room_messages.author_id</code>.
     */
    public void setAuthorId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.chat_room_messages.author_id</code>.
     */
    public Long getAuthorId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.chat_room_messages.body</code>.
     */
    public void setBody(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.chat_room_messages.body</code>.
     */
    public String getBody() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.chat_room_messages.kind</code>.
     */
    public void setKind(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.chat_room_messages.kind</code>.
     */
    public String getKind() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.chat_room_messages.posted_at</code>.
     */
    public void setPostedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.chat_room_messages.posted_at</code>.
     */
    public OffsetDateTime getPostedAt() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatRoomMessagesRecord
     */
    public ChatRoomMessagesRecord() {
        super(ChatRoomMessages.CHAT_ROOM_MESSAGES);
    }

    /**
     * Create a detached, initialised ChatRoomMessagesRecord
     */
    public ChatRoomMessagesRecord(Long id, Long roomId, Long authorId, String body, String kind, OffsetDateTime postedAt) {
        super(ChatRoomMessages.CHAT_ROOM_MESSAGES);

        setId(id);
        setRoomId(roomId);
        setAuthorId(authorId);
        setBody(body);
        setKind(kind);
        setPostedAt(postedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ChatRoomMessagesRecord
     */
    public ChatRoomMessagesRecord(io.aeyer.voidcore.jooq.tables.pojos.ChatRoomMessages value) {
        super(ChatRoomMessages.CHAT_ROOM_MESSAGES);

        if (value != null) {
            setId(value.getId());
            setRoomId(value.getRoomId());
            setAuthorId(value.getAuthorId());
            setBody(value.getBody());
            setKind(value.getKind());
            setPostedAt(value.getPostedAt());
            resetChangedOnNotNull();
        }
    }
}
