/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.Fortunes;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FortunesRecord extends UpdatableRecordImpl<FortunesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.fortunes.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fortunes.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.fortunes.text</code>.
     */
    public void setText(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fortunes.text</code>.
     */
    public String getText() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FortunesRecord
     */
    public FortunesRecord() {
        super(Fortunes.FORTUNES);
    }

    /**
     * Create a detached, initialised FortunesRecord
     */
    public FortunesRecord(Long id, String text) {
        super(Fortunes.FORTUNES);

        setId(id);
        setText(text);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FortunesRecord
     */
    public FortunesRecord(io.aeyer.voidcore.jooq.tables.pojos.Fortunes value) {
        super(Fortunes.FORTUNES);

        if (value != null) {
            setId(value.getId());
            setText(value.getText());
            resetChangedOnNotNull();
        }
    }
}
