/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.InstanceFeatures;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InstanceFeaturesRecord extends UpdatableRecordImpl<InstanceFeaturesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.instance_features.feature_slug</code>.
     */
    public void setFeatureSlug(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.instance_features.feature_slug</code>.
     */
    public String getFeatureSlug() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.instance_features.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.instance_features.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InstanceFeaturesRecord
     */
    public InstanceFeaturesRecord() {
        super(InstanceFeatures.INSTANCE_FEATURES);
    }

    /**
     * Create a detached, initialised InstanceFeaturesRecord
     */
    public InstanceFeaturesRecord(String featureSlug, Boolean enabled) {
        super(InstanceFeatures.INSTANCE_FEATURES);

        setFeatureSlug(featureSlug);
        setEnabled(enabled);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised InstanceFeaturesRecord
     */
    public InstanceFeaturesRecord(io.aeyer.voidcore.jooq.tables.pojos.InstanceFeatures value) {
        super(InstanceFeatures.INSTANCE_FEATURES);

        if (value != null) {
            setFeatureSlug(value.getFeatureSlug());
            setEnabled(value.getEnabled());
            resetChangedOnNotNull();
        }
    }
}
