/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.LoginAttempts;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LoginAttemptsRecord extends UpdatableRecordImpl<LoginAttemptsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.login_attempts.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.login_attempts.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.login_attempts.ip</code>.
     */
    public void setIp(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.login_attempts.ip</code>.
     */
    public String getIp() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.login_attempts.handle</code>.
     */
    public void setHandle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.login_attempts.handle</code>.
     */
    public String getHandle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.login_attempts.success</code>.
     */
    public void setSuccess(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.login_attempts.success</code>.
     */
    public Boolean getSuccess() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.login_attempts.at</code>.
     */
    public void setAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.login_attempts.at</code>.
     */
    public OffsetDateTime getAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoginAttemptsRecord
     */
    public LoginAttemptsRecord() {
        super(LoginAttempts.LOGIN_ATTEMPTS);
    }

    /**
     * Create a detached, initialised LoginAttemptsRecord
     */
    public LoginAttemptsRecord(Long id, String ip, String handle, Boolean success, OffsetDateTime at) {
        super(LoginAttempts.LOGIN_ATTEMPTS);

        setId(id);
        setIp(ip);
        setHandle(handle);
        setSuccess(success);
        setAt(at);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LoginAttemptsRecord
     */
    public LoginAttemptsRecord(io.aeyer.voidcore.jooq.tables.pojos.LoginAttempts value) {
        super(LoginAttempts.LOGIN_ATTEMPTS);

        if (value != null) {
            setId(value.getId());
            setIp(value.getIp());
            setHandle(value.getHandle());
            setSuccess(value.getSuccess());
            setAt(value.getAt());
            resetChangedOnNotNull();
        }
    }
}
