/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.Oneliners;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OnelinersRecord extends UpdatableRecordImpl<OnelinersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.oneliners.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.oneliners.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.oneliners.author_id</code>.
     */
    public void setAuthorId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.oneliners.author_id</code>.
     */
    public Long getAuthorId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.oneliners.body</code>.
     */
    public void setBody(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.oneliners.body</code>.
     */
    public String getBody() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.oneliners.posted_at</code>.
     */
    public void setPostedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.oneliners.posted_at</code>.
     */
    public OffsetDateTime getPostedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OnelinersRecord
     */
    public OnelinersRecord() {
        super(Oneliners.ONELINERS);
    }

    /**
     * Create a detached, initialised OnelinersRecord
     */
    public OnelinersRecord(Long id, Long authorId, String body, OffsetDateTime postedAt) {
        super(Oneliners.ONELINERS);

        setId(id);
        setAuthorId(authorId);
        setBody(body);
        setPostedAt(postedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised OnelinersRecord
     */
    public OnelinersRecord(io.aeyer.voidcore.jooq.tables.pojos.Oneliners value) {
        super(Oneliners.ONELINERS);

        if (value != null) {
            setId(value.getId());
            setAuthorId(value.getAuthorId());
            setBody(value.getBody());
            setPostedAt(value.getPostedAt());
            resetChangedOnNotNull();
        }
    }
}
