/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.PollVotes;

import java.time.OffsetDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PollVotesRecord extends UpdatableRecordImpl<PollVotesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.poll_votes.poll_id</code>.
     */
    public void setPollId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.poll_votes.poll_id</code>.
     */
    public Long getPollId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.poll_votes.option_id</code>.
     */
    public void setOptionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.poll_votes.option_id</code>.
     */
    public Long getOptionId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.poll_votes.user_id</code>.
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.poll_votes.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.poll_votes.voted_at</code>.
     */
    public void setVotedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.poll_votes.voted_at</code>.
     */
    public OffsetDateTime getVotedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PollVotesRecord
     */
    public PollVotesRecord() {
        super(PollVotes.POLL_VOTES);
    }

    /**
     * Create a detached, initialised PollVotesRecord
     */
    public PollVotesRecord(Long pollId, Long optionId, Long userId, OffsetDateTime votedAt) {
        super(PollVotes.POLL_VOTES);

        setPollId(pollId);
        setOptionId(optionId);
        setUserId(userId);
        setVotedAt(votedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PollVotesRecord
     */
    public PollVotesRecord(io.aeyer.voidcore.jooq.tables.pojos.PollVotes value) {
        super(PollVotes.POLL_VOTES);

        if (value != null) {
            setPollId(value.getPollId());
            setOptionId(value.getOptionId());
            setUserId(value.getUserId());
            setVotedAt(value.getVotedAt());
            resetChangedOnNotNull();
        }
    }
}
