/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.PollOptions;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PollOptionsRecord extends UpdatableRecordImpl<PollOptionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.poll_options.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.poll_options.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.poll_options.poll_id</code>.
     */
    public void setPollId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.poll_options.poll_id</code>.
     */
    public Long getPollId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.poll_options.text</code>.
     */
    public void setText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.poll_options.text</code>.
     */
    public String getText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.poll_options.position</code>.
     */
    public void setPosition(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.poll_options.position</code>.
     */
    public Integer getPosition() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PollOptionsRecord
     */
    public PollOptionsRecord() {
        super(PollOptions.POLL_OPTIONS);
    }

    /**
     * Create a detached, initialised PollOptionsRecord
     */
    public PollOptionsRecord(Long id, Long pollId, String text, Integer position) {
        super(PollOptions.POLL_OPTIONS);

        setId(id);
        setPollId(pollId);
        setText(text);
        setPosition(position);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PollOptionsRecord
     */
    public PollOptionsRecord(io.aeyer.voidcore.jooq.tables.pojos.PollOptions value) {
        super(PollOptions.POLL_OPTIONS);

        if (value != null) {
            setId(value.getId());
            setPollId(value.getPollId());
            setText(value.getText());
            setPosition(value.getPosition());
            resetChangedOnNotNull();
        }
    }
}
