/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.Polls;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PollsRecord extends UpdatableRecordImpl<PollsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.polls.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.polls.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.polls.author_id</code>.
     */
    public void setAuthorId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.polls.author_id</code>.
     */
    public Long getAuthorId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.polls.question</code>.
     */
    public void setQuestion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.polls.question</code>.
     */
    public String getQuestion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.polls.closed_at</code>.
     */
    public void setClosedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.polls.closed_at</code>.
     */
    public OffsetDateTime getClosedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.polls.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.polls.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PollsRecord
     */
    public PollsRecord() {
        super(Polls.POLLS);
    }

    /**
     * Create a detached, initialised PollsRecord
     */
    public PollsRecord(Long id, Long authorId, String question, OffsetDateTime closedAt, OffsetDateTime createdAt) {
        super(Polls.POLLS);

        setId(id);
        setAuthorId(authorId);
        setQuestion(question);
        setClosedAt(closedAt);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PollsRecord
     */
    public PollsRecord(io.aeyer.voidcore.jooq.tables.pojos.Polls value) {
        super(Polls.POLLS);

        if (value != null) {
            setId(value.getId());
            setAuthorId(value.getAuthorId());
            setQuestion(value.getQuestion());
            setClosedAt(value.getClosedAt());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
