/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.Posts;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PostsRecord extends UpdatableRecordImpl<PostsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.posts.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.posts.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.posts.thread_id</code>.
     */
    public void setThreadId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.posts.thread_id</code>.
     */
    public Long getThreadId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.posts.author_id</code>.
     */
    public void setAuthorId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.posts.author_id</code>.
     */
    public Long getAuthorId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.posts.body</code>.
     */
    public void setBody(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.posts.body</code>.
     */
    public String getBody() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.posts.posted_at</code>.
     */
    public void setPostedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.posts.posted_at</code>.
     */
    public OffsetDateTime getPostedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.posts.edited_at</code>.
     */
    public void setEditedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.posts.edited_at</code>.
     */
    public OffsetDateTime getEditedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.posts.is_deleted</code>.
     */
    public void setIsDeleted(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.posts.is_deleted</code>.
     */
    public Boolean getIsDeleted() {
        return (Boolean) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostsRecord
     */
    public PostsRecord() {
        super(Posts.POSTS);
    }

    /**
     * Create a detached, initialised PostsRecord
     */
    public PostsRecord(Long id, Long threadId, Long authorId, String body, OffsetDateTime postedAt, OffsetDateTime editedAt, Boolean isDeleted) {
        super(Posts.POSTS);

        setId(id);
        setThreadId(threadId);
        setAuthorId(authorId);
        setBody(body);
        setPostedAt(postedAt);
        setEditedAt(editedAt);
        setIsDeleted(isDeleted);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PostsRecord
     */
    public PostsRecord(io.aeyer.voidcore.jooq.tables.pojos.Posts value) {
        super(Posts.POSTS);

        if (value != null) {
            setId(value.getId());
            setThreadId(value.getThreadId());
            setAuthorId(value.getAuthorId());
            setBody(value.getBody());
            setPostedAt(value.getPostedAt());
            setEditedAt(value.getEditedAt());
            setIsDeleted(value.getIsDeleted());
            resetChangedOnNotNull();
        }
    }
}
