/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.Reactions;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReactionsRecord extends UpdatableRecordImpl<ReactionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.reactions.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.reactions.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.reactions.target_type</code>.
     */
    public void setTargetType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.reactions.target_type</code>.
     */
    public String getTargetType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.reactions.target_id</code>.
     */
    public void setTargetId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.reactions.target_id</code>.
     */
    public Long getTargetId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.reactions.user_id</code>.
     */
    public void setUserId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.reactions.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.reactions.reaction</code>.
     */
    public void setReaction(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.reactions.reaction</code>.
     */
    public String getReaction() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.reactions.reacted_at</code>.
     */
    public void setReactedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.reactions.reacted_at</code>.
     */
    public OffsetDateTime getReactedAt() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReactionsRecord
     */
    public ReactionsRecord() {
        super(Reactions.REACTIONS);
    }

    /**
     * Create a detached, initialised ReactionsRecord
     */
    public ReactionsRecord(Long id, String targetType, Long targetId, Long userId, String reaction, OffsetDateTime reactedAt) {
        super(Reactions.REACTIONS);

        setId(id);
        setTargetType(targetType);
        setTargetId(targetId);
        setUserId(userId);
        setReaction(reaction);
        setReactedAt(reactedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ReactionsRecord
     */
    public ReactionsRecord(io.aeyer.voidcore.jooq.tables.pojos.Reactions value) {
        super(Reactions.REACTIONS);

        if (value != null) {
            setId(value.getId());
            setTargetType(value.getTargetType());
            setTargetId(value.getTargetId());
            setUserId(value.getUserId());
            setReaction(value.getReaction());
            setReactedAt(value.getReactedAt());
            resetChangedOnNotNull();
        }
    }
}
