/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.SysopNotes;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SysopNotesRecord extends UpdatableRecordImpl<SysopNotesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sysop_notes.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.sysop_notes.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.sysop_notes.subject_id</code>.
     */
    public void setSubjectId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.sysop_notes.subject_id</code>.
     */
    public Long getSubjectId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.sysop_notes.author_id</code>.
     */
    public void setAuthorId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.sysop_notes.author_id</code>.
     */
    public Long getAuthorId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.sysop_notes.body</code>.
     */
    public void setBody(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.sysop_notes.body</code>.
     */
    public String getBody() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.sysop_notes.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.sysop_notes.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysopNotesRecord
     */
    public SysopNotesRecord() {
        super(SysopNotes.SYSOP_NOTES);
    }

    /**
     * Create a detached, initialised SysopNotesRecord
     */
    public SysopNotesRecord(Long id, Long subjectId, Long authorId, String body, OffsetDateTime createdAt) {
        super(SysopNotes.SYSOP_NOTES);

        setId(id);
        setSubjectId(subjectId);
        setAuthorId(authorId);
        setBody(body);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SysopNotesRecord
     */
    public SysopNotesRecord(io.aeyer.voidcore.jooq.tables.pojos.SysopNotes value) {
        super(SysopNotes.SYSOP_NOTES);

        if (value != null) {
            setId(value.getId());
            setSubjectId(value.getSubjectId());
            setAuthorId(value.getAuthorId());
            setBody(value.getBody());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
