/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.SysopActions;

import java.time.OffsetDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SysopActionsRecord extends UpdatableRecordImpl<SysopActionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sysop_actions.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.sysop_actions.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.sysop_actions.actor_id</code>.
     */
    public void setActorId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.sysop_actions.actor_id</code>.
     */
    public Long getActorId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.sysop_actions.action</code>.
     */
    public void setAction(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.sysop_actions.action</code>.
     */
    public String getAction() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.sysop_actions.payload</code>.
     */
    public void setPayload(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.sysop_actions.payload</code>.
     */
    public JSONB getPayload() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.sysop_actions.at</code>.
     */
    public void setAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.sysop_actions.at</code>.
     */
    public OffsetDateTime getAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysopActionsRecord
     */
    public SysopActionsRecord() {
        super(SysopActions.SYSOP_ACTIONS);
    }

    /**
     * Create a detached, initialised SysopActionsRecord
     */
    public SysopActionsRecord(Long id, Long actorId, String action, JSONB payload, OffsetDateTime at) {
        super(SysopActions.SYSOP_ACTIONS);

        setId(id);
        setActorId(actorId);
        setAction(action);
        setPayload(payload);
        setAt(at);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SysopActionsRecord
     */
    public SysopActionsRecord(io.aeyer.voidcore.jooq.tables.pojos.SysopActions value) {
        super(SysopActions.SYSOP_ACTIONS);

        if (value != null) {
            setId(value.getId());
            setActorId(value.getActorId());
            setAction(value.getAction());
            setPayload(value.getPayload());
            setAt(value.getAt());
            resetChangedOnNotNull();
        }
    }
}
