/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.Threads;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ThreadsRecord extends UpdatableRecordImpl<ThreadsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.threads.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.threads.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.threads.base_id</code>.
     */
    public void setBaseId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.threads.base_id</code>.
     */
    public Long getBaseId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.threads.subject</code>.
     */
    public void setSubject(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.threads.subject</code>.
     */
    public String getSubject() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.threads.author_id</code>.
     */
    public void setAuthorId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.threads.author_id</code>.
     */
    public Long getAuthorId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.threads.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.threads.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.threads.last_post_at</code>.
     */
    public void setLastPostAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.threads.last_post_at</code>.
     */
    public OffsetDateTime getLastPostAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.threads.post_count</code>.
     */
    public void setPostCount(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.threads.post_count</code>.
     */
    public Integer getPostCount() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.threads.is_pinned</code>.
     */
    public void setIsPinned(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.threads.is_pinned</code>.
     */
    public Boolean getIsPinned() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.threads.is_locked</code>.
     */
    public void setIsLocked(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.threads.is_locked</code>.
     */
    public Boolean getIsLocked() {
        return (Boolean) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ThreadsRecord
     */
    public ThreadsRecord() {
        super(Threads.THREADS);
    }

    /**
     * Create a detached, initialised ThreadsRecord
     */
    public ThreadsRecord(Long id, Long baseId, String subject, Long authorId, OffsetDateTime createdAt, OffsetDateTime lastPostAt, Integer postCount, Boolean isPinned, Boolean isLocked) {
        super(Threads.THREADS);

        setId(id);
        setBaseId(baseId);
        setSubject(subject);
        setAuthorId(authorId);
        setCreatedAt(createdAt);
        setLastPostAt(lastPostAt);
        setPostCount(postCount);
        setIsPinned(isPinned);
        setIsLocked(isLocked);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ThreadsRecord
     */
    public ThreadsRecord(io.aeyer.voidcore.jooq.tables.pojos.Threads value) {
        super(Threads.THREADS);

        if (value != null) {
            setId(value.getId());
            setBaseId(value.getBaseId());
            setSubject(value.getSubject());
            setAuthorId(value.getAuthorId());
            setCreatedAt(value.getCreatedAt());
            setLastPostAt(value.getLastPostAt());
            setPostCount(value.getPostCount());
            setIsPinned(value.getIsPinned());
            setIsLocked(value.getIsLocked());
            resetChangedOnNotNull();
        }
    }
}
