/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.UserRoles;

import java.time.OffsetDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRolesRecord extends UpdatableRecordImpl<UserRolesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_roles.user_id</code>.
     */
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_roles.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_roles.role_id</code>.
     */
    public void setRoleId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_roles.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.user_roles.granted_at</code>.
     */
    public void setGrantedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_roles.granted_at</code>.
     */
    public OffsetDateTime getGrantedAt() {
        return (OffsetDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRolesRecord
     */
    public UserRolesRecord() {
        super(UserRoles.USER_ROLES);
    }

    /**
     * Create a detached, initialised UserRolesRecord
     */
    public UserRolesRecord(Long userId, Long roleId, OffsetDateTime grantedAt) {
        super(UserRoles.USER_ROLES);

        setUserId(userId);
        setRoleId(roleId);
        setGrantedAt(grantedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserRolesRecord
     */
    public UserRolesRecord(io.aeyer.voidcore.jooq.tables.pojos.UserRoles value) {
        super(UserRoles.USER_ROLES);

        if (value != null) {
            setUserId(value.getUserId());
            setRoleId(value.getRoleId());
            setGrantedAt(value.getGrantedAt());
            resetChangedOnNotNull();
        }
    }
}
