/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.Users;

import java.time.OffsetDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.users.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.users.handle</code>.
     */
    public void setHandle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.users.handle</code>.
     */
    public String getHandle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.users.pw_hash</code>.
     */
    public void setPwHash(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.users.pw_hash</code>.
     */
    public String getPwHash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.users.location</code>.
     */
    public void setLocation(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.users.location</code>.
     */
    public String getLocation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.users.setup</code>.
     */
    public void setSetup(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.users.setup</code>.
     */
    public String getSetup() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.users.found_via</code>.
     */
    public void setFoundVia(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.users.found_via</code>.
     */
    public String getFoundVia() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.users.fav_genres</code>.
     */
    public void setFavGenres(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.users.fav_genres</code>.
     */
    public String getFavGenres() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.users.bio</code>.
     */
    public void setBio(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.users.bio</code>.
     */
    public String getBio() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.users.preferences</code>.
     */
    public void setPreferences(JSONB value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.users.preferences</code>.
     */
    public JSONB getPreferences() {
        return (JSONB) get(8);
    }

    /**
     * Setter for <code>public.users.joined_at</code>.
     */
    public void setJoinedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.users.joined_at</code>.
     */
    public OffsetDateTime getJoinedAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.users.last_call_at</code>.
     */
    public void setLastCallAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.users.last_call_at</code>.
     */
    public OffsetDateTime getLastCallAt() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>public.users.call_count</code>.
     */
    public void setCallCount(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.users.call_count</code>.
     */
    public Integer getCallCount() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.users.post_count</code>.
     */
    public void setPostCount(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.users.post_count</code>.
     */
    public Integer getPostCount() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.users.is_sysop</code>.
     */
    public void setIsSysop(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.users.is_sysop</code>.
     */
    public Boolean getIsSysop() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>public.users.is_banned</code>.
     */
    public void setIsBanned(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.users.is_banned</code>.
     */
    public Boolean getIsBanned() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>public.users.banned_reason</code>.
     */
    public void setBannedReason(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.users.banned_reason</code>.
     */
    public String getBannedReason() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Long id, String handle, String pwHash, String location, String setup, String foundVia, String favGenres, String bio, JSONB preferences, OffsetDateTime joinedAt, OffsetDateTime lastCallAt, Integer callCount, Integer postCount, Boolean isSysop, Boolean isBanned, String bannedReason) {
        super(Users.USERS);

        setId(id);
        setHandle(handle);
        setPwHash(pwHash);
        setLocation(location);
        setSetup(setup);
        setFoundVia(foundVia);
        setFavGenres(favGenres);
        setBio(bio);
        setPreferences(preferences);
        setJoinedAt(joinedAt);
        setLastCallAt(lastCallAt);
        setCallCount(callCount);
        setPostCount(postCount);
        setIsSysop(isSysop);
        setIsBanned(isBanned);
        setBannedReason(bannedReason);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(io.aeyer.voidcore.jooq.tables.pojos.Users value) {
        super(Users.USERS);

        if (value != null) {
            setId(value.getId());
            setHandle(value.getHandle());
            setPwHash(value.getPwHash());
            setLocation(value.getLocation());
            setSetup(value.getSetup());
            setFoundVia(value.getFoundVia());
            setFavGenres(value.getFavGenres());
            setBio(value.getBio());
            setPreferences(value.getPreferences());
            setJoinedAt(value.getJoinedAt());
            setLastCallAt(value.getLastCallAt());
            setCallCount(value.getCallCount());
            setPostCount(value.getPostCount());
            setIsSysop(value.getIsSysop());
            setIsBanned(value.getIsBanned());
            setBannedReason(value.getBannedReason());
            resetChangedOnNotNull();
        }
    }
}
