/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.UserAchievements;

import java.time.OffsetDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserAchievementsRecord extends UpdatableRecordImpl<UserAchievementsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_achievements.user_id</code>.
     */
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_achievements.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_achievements.achievement_id</code>.
     */
    public void setAchievementId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_achievements.achievement_id</code>.
     */
    public Long getAchievementId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.user_achievements.awarded_at</code>.
     */
    public void setAwardedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_achievements.awarded_at</code>.
     */
    public OffsetDateTime getAwardedAt() {
        return (OffsetDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAchievementsRecord
     */
    public UserAchievementsRecord() {
        super(UserAchievements.USER_ACHIEVEMENTS);
    }

    /**
     * Create a detached, initialised UserAchievementsRecord
     */
    public UserAchievementsRecord(Long userId, Long achievementId, OffsetDateTime awardedAt) {
        super(UserAchievements.USER_ACHIEVEMENTS);

        setUserId(userId);
        setAchievementId(achievementId);
        setAwardedAt(awardedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UserAchievementsRecord
     */
    public UserAchievementsRecord(io.aeyer.voidcore.jooq.tables.pojos.UserAchievements value) {
        super(UserAchievements.USER_ACHIEVEMENTS);

        if (value != null) {
            setUserId(value.getUserId());
            setAchievementId(value.getAchievementId());
            setAwardedAt(value.getAwardedAt());
            resetChangedOnNotNull();
        }
    }
}
