/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.records;


import io.aeyer.voidcore.jooq.tables.WatchList;

import java.time.OffsetDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WatchListRecord extends UpdatableRecordImpl<WatchListRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.watch_list.watcher_id</code>.
     */
    public void setWatcherId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.watch_list.watcher_id</code>.
     */
    public Long getWatcherId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.watch_list.watched_id</code>.
     */
    public void setWatchedId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.watch_list.watched_id</code>.
     */
    public Long getWatchedId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.watch_list.watched_at</code>.
     */
    public void setWatchedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.watch_list.watched_at</code>.
     */
    public OffsetDateTime getWatchedAt() {
        return (OffsetDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WatchListRecord
     */
    public WatchListRecord() {
        super(WatchList.WATCH_LIST);
    }

    /**
     * Create a detached, initialised WatchListRecord
     */
    public WatchListRecord(Long watcherId, Long watchedId, OffsetDateTime watchedAt) {
        super(WatchList.WATCH_LIST);

        setWatcherId(watcherId);
        setWatchedId(watchedId);
        setWatchedAt(watchedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised WatchListRecord
     */
    public WatchListRecord(io.aeyer.voidcore.jooq.tables.pojos.WatchList value) {
        super(WatchList.WATCH_LIST);

        if (value != null) {
            setWatcherId(value.getWatcherId());
            setWatchedId(value.getWatchedId());
            setWatchedAt(value.getWatchedAt());
            resetChangedOnNotNull();
        }
    }
}
