#!/bin/bash
set -euo pipefail

: "${VOIDCORE_APP_USER:?env VOIDCORE_APP_USER required}"
: "${VOIDCORE_APP_PASSWORD:?env VOIDCORE_APP_PASSWORD required}"
: "${POSTGRES_DB:?env POSTGRES_DB required}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE EXTENSION IF NOT EXISTS citext;
  CREATE EXTENSION IF NOT EXISTS pgcrypto;

  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${VOIDCORE_APP_USER}') THEN
      CREATE ROLE ${VOIDCORE_APP_USER} WITH LOGIN PASSWORD '${VOIDCORE_APP_PASSWORD}';
    END IF;
  END
  \$\$;

  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${VOIDCORE_APP_USER};
  GRANT USAGE, CREATE ON SCHEMA public TO ${VOIDCORE_APP_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${VOIDCORE_APP_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO ${VOIDCORE_APP_USER};
EOSQL

echo "Roles initialised: ${VOIDCORE_APP_USER}"
