/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq;


import io.aeyer.voidcore.jooq.tables.Achievements;
import io.aeyer.voidcore.jooq.tables.AclGrants;
import io.aeyer.voidcore.jooq.tables.ActivityEvents;
import io.aeyer.voidcore.jooq.tables.ChatMessages;
import io.aeyer.voidcore.jooq.tables.ChatRoomMembers;
import io.aeyer.voidcore.jooq.tables.ChatRoomMessages;
import io.aeyer.voidcore.jooq.tables.ChatRooms;
import io.aeyer.voidcore.jooq.tables.Counters;
import io.aeyer.voidcore.jooq.tables.DocumentEditors;
import io.aeyer.voidcore.jooq.tables.DocumentLinks;
import io.aeyer.voidcore.jooq.tables.DocumentRevisions;
import io.aeyer.voidcore.jooq.tables.Documents;
import io.aeyer.voidcore.jooq.tables.DoorState;
import io.aeyer.voidcore.jooq.tables.Fortunes;
import io.aeyer.voidcore.jooq.tables.InstanceFeatures;
import io.aeyer.voidcore.jooq.tables.LastCallers;
import io.aeyer.voidcore.jooq.tables.LoginAttempts;
import io.aeyer.voidcore.jooq.tables.MessageBases;
import io.aeyer.voidcore.jooq.tables.Netmail;
import io.aeyer.voidcore.jooq.tables.Oneliners;
import io.aeyer.voidcore.jooq.tables.PendingContent;
import io.aeyer.voidcore.jooq.tables.PollOptions;
import io.aeyer.voidcore.jooq.tables.PollVotes;
import io.aeyer.voidcore.jooq.tables.Polls;
import io.aeyer.voidcore.jooq.tables.Posts;
import io.aeyer.voidcore.jooq.tables.Reactions;
import io.aeyer.voidcore.jooq.tables.Roles;
import io.aeyer.voidcore.jooq.tables.Schemas;
import io.aeyer.voidcore.jooq.tables.Sessions;
import io.aeyer.voidcore.jooq.tables.SysopActions;
import io.aeyer.voidcore.jooq.tables.SysopNotes;
import io.aeyer.voidcore.jooq.tables.ThreadRead;
import io.aeyer.voidcore.jooq.tables.Threads;
import io.aeyer.voidcore.jooq.tables.UserAchievements;
import io.aeyer.voidcore.jooq.tables.UserRoles;
import io.aeyer.voidcore.jooq.tables.Users;
import io.aeyer.voidcore.jooq.tables.WatchList;
import io.aeyer.voidcore.jooq.tables.records.AchievementsRecord;
import io.aeyer.voidcore.jooq.tables.records.AclGrantsRecord;
import io.aeyer.voidcore.jooq.tables.records.ActivityEventsRecord;
import io.aeyer.voidcore.jooq.tables.records.ChatMessagesRecord;
import io.aeyer.voidcore.jooq.tables.records.ChatRoomMembersRecord;
import io.aeyer.voidcore.jooq.tables.records.ChatRoomMessagesRecord;
import io.aeyer.voidcore.jooq.tables.records.ChatRoomsRecord;
import io.aeyer.voidcore.jooq.tables.records.CountersRecord;
import io.aeyer.voidcore.jooq.tables.records.DocumentEditorsRecord;
import io.aeyer.voidcore.jooq.tables.records.DocumentLinksRecord;
import io.aeyer.voidcore.jooq.tables.records.DocumentRevisionsRecord;
import io.aeyer.voidcore.jooq.tables.records.DocumentsRecord;
import io.aeyer.voidcore.jooq.tables.records.DoorStateRecord;
import io.aeyer.voidcore.jooq.tables.records.FortunesRecord;
import io.aeyer.voidcore.jooq.tables.records.InstanceFeaturesRecord;
import io.aeyer.voidcore.jooq.tables.records.LastCallersRecord;
import io.aeyer.voidcore.jooq.tables.records.LoginAttemptsRecord;
import io.aeyer.voidcore.jooq.tables.records.MessageBasesRecord;
import io.aeyer.voidcore.jooq.tables.records.NetmailRecord;
import io.aeyer.voidcore.jooq.tables.records.OnelinersRecord;
import io.aeyer.voidcore.jooq.tables.records.PendingContentRecord;
import io.aeyer.voidcore.jooq.tables.records.PollOptionsRecord;
import io.aeyer.voidcore.jooq.tables.records.PollVotesRecord;
import io.aeyer.voidcore.jooq.tables.records.PollsRecord;
import io.aeyer.voidcore.jooq.tables.records.PostsRecord;
import io.aeyer.voidcore.jooq.tables.records.ReactionsRecord;
import io.aeyer.voidcore.jooq.tables.records.RolesRecord;
import io.aeyer.voidcore.jooq.tables.records.SchemasRecord;
import io.aeyer.voidcore.jooq.tables.records.SessionsRecord;
import io.aeyer.voidcore.jooq.tables.records.SysopActionsRecord;
import io.aeyer.voidcore.jooq.tables.records.SysopNotesRecord;
import io.aeyer.voidcore.jooq.tables.records.ThreadReadRecord;
import io.aeyer.voidcore.jooq.tables.records.ThreadsRecord;
import io.aeyer.voidcore.jooq.tables.records.UserAchievementsRecord;
import io.aeyer.voidcore.jooq.tables.records.UserRolesRecord;
import io.aeyer.voidcore.jooq.tables.records.UsersRecord;
import io.aeyer.voidcore.jooq.tables.records.WatchListRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AchievementsRecord> ACHIEVEMENTS_PKEY = Internal.createUniqueKey(Achievements.ACHIEVEMENTS, DSL.name("achievements_pkey"), new TableField[] { Achievements.ACHIEVEMENTS.ID }, true);
    public static final UniqueKey<AchievementsRecord> ACHIEVEMENTS_SLUG_KEY = Internal.createUniqueKey(Achievements.ACHIEVEMENTS, DSL.name("achievements_slug_key"), new TableField[] { Achievements.ACHIEVEMENTS.SLUG }, true);
    public static final UniqueKey<AclGrantsRecord> ACL_GRANTS_PKEY = Internal.createUniqueKey(AclGrants.ACL_GRANTS, DSL.name("acl_grants_pkey"), new TableField[] { AclGrants.ACL_GRANTS.ID }, true);
    public static final UniqueKey<AclGrantsRecord> UQ_ACL_GRANTS = Internal.createUniqueKey(AclGrants.ACL_GRANTS, DSL.name("uq_acl_grants"), new TableField[] { AclGrants.ACL_GRANTS.RESOURCE_TYPE, AclGrants.ACL_GRANTS.RESOURCE_ID, AclGrants.ACL_GRANTS.PERMISSION, AclGrants.ACL_GRANTS.PRINCIPAL_TYPE, AclGrants.ACL_GRANTS.PRINCIPAL_ID }, true);
    public static final UniqueKey<ActivityEventsRecord> ACTIVITY_EVENTS_PKEY = Internal.createUniqueKey(ActivityEvents.ACTIVITY_EVENTS, DSL.name("activity_events_pkey"), new TableField[] { ActivityEvents.ACTIVITY_EVENTS.ID }, true);
    public static final UniqueKey<ChatMessagesRecord> CHAT_MESSAGES_PKEY = Internal.createUniqueKey(ChatMessages.CHAT_MESSAGES, DSL.name("chat_messages_pkey"), new TableField[] { ChatMessages.CHAT_MESSAGES.ID }, true);
    public static final UniqueKey<ChatRoomMembersRecord> CHAT_ROOM_MEMBERS_PKEY = Internal.createUniqueKey(ChatRoomMembers.CHAT_ROOM_MEMBERS, DSL.name("chat_room_members_pkey"), new TableField[] { ChatRoomMembers.CHAT_ROOM_MEMBERS.ROOM_ID, ChatRoomMembers.CHAT_ROOM_MEMBERS.USER_ID }, true);
    public static final UniqueKey<ChatRoomMessagesRecord> CHAT_ROOM_MESSAGES_PKEY = Internal.createUniqueKey(ChatRoomMessages.CHAT_ROOM_MESSAGES, DSL.name("chat_room_messages_pkey"), new TableField[] { ChatRoomMessages.CHAT_ROOM_MESSAGES.ID }, true);
    public static final UniqueKey<ChatRoomsRecord> CHAT_ROOMS_PKEY = Internal.createUniqueKey(ChatRooms.CHAT_ROOMS, DSL.name("chat_rooms_pkey"), new TableField[] { ChatRooms.CHAT_ROOMS.ID }, true);
    public static final UniqueKey<ChatRoomsRecord> CHAT_ROOMS_SLUG_KEY = Internal.createUniqueKey(ChatRooms.CHAT_ROOMS, DSL.name("chat_rooms_slug_key"), new TableField[] { ChatRooms.CHAT_ROOMS.SLUG }, true);
    public static final UniqueKey<CountersRecord> COUNTERS_PKEY = Internal.createUniqueKey(Counters.COUNTERS, DSL.name("counters_pkey"), new TableField[] { Counters.COUNTERS.KEY }, true);
    public static final UniqueKey<DocumentEditorsRecord> DOCUMENT_EDITORS_PKEY = Internal.createUniqueKey(DocumentEditors.DOCUMENT_EDITORS, DSL.name("document_editors_pkey"), new TableField[] { DocumentEditors.DOCUMENT_EDITORS.DOCUMENT_ID, DocumentEditors.DOCUMENT_EDITORS.USER_ID }, true);
    public static final UniqueKey<DocumentLinksRecord> DOCUMENT_LINKS_PKEY = Internal.createUniqueKey(DocumentLinks.DOCUMENT_LINKS, DSL.name("document_links_pkey"), new TableField[] { DocumentLinks.DOCUMENT_LINKS.SOURCE_ID, DocumentLinks.DOCUMENT_LINKS.TARGET_ID, DocumentLinks.DOCUMENT_LINKS.KIND }, true);
    public static final UniqueKey<DocumentRevisionsRecord> DOCUMENT_REVISIONS_DOC_REV_UNIQUE = Internal.createUniqueKey(DocumentRevisions.DOCUMENT_REVISIONS, DSL.name("document_revisions_doc_rev_unique"), new TableField[] { DocumentRevisions.DOCUMENT_REVISIONS.DOCUMENT_ID, DocumentRevisions.DOCUMENT_REVISIONS.REV }, true);
    public static final UniqueKey<DocumentRevisionsRecord> DOCUMENT_REVISIONS_PKEY = Internal.createUniqueKey(DocumentRevisions.DOCUMENT_REVISIONS, DSL.name("document_revisions_pkey"), new TableField[] { DocumentRevisions.DOCUMENT_REVISIONS.ID }, true);
    public static final UniqueKey<DocumentsRecord> DOCUMENTS_PKEY = Internal.createUniqueKey(Documents.DOCUMENTS, DSL.name("documents_pkey"), new TableField[] { Documents.DOCUMENTS.ID }, true);
    public static final UniqueKey<DocumentsRecord> DOCUMENTS_SLUG_KEY = Internal.createUniqueKey(Documents.DOCUMENTS, DSL.name("documents_slug_key"), new TableField[] { Documents.DOCUMENTS.SLUG }, true);
    public static final UniqueKey<DoorStateRecord> DOOR_STATE_PKEY = Internal.createUniqueKey(DoorState.DOOR_STATE, DSL.name("door_state_pkey"), new TableField[] { DoorState.DOOR_STATE.DOOR_ID, DoorState.DOOR_STATE.SCOPE, DoorState.DOOR_STATE.SCOPE_KEY, DoorState.DOOR_STATE.KEY }, true);
    public static final UniqueKey<FortunesRecord> FORTUNES_PKEY = Internal.createUniqueKey(Fortunes.FORTUNES, DSL.name("fortunes_pkey"), new TableField[] { Fortunes.FORTUNES.ID }, true);
    public static final UniqueKey<InstanceFeaturesRecord> INSTANCE_FEATURES_PKEY = Internal.createUniqueKey(InstanceFeatures.INSTANCE_FEATURES, DSL.name("instance_features_pkey"), new TableField[] { InstanceFeatures.INSTANCE_FEATURES.FEATURE_SLUG }, true);
    public static final UniqueKey<LastCallersRecord> LAST_CALLERS_PKEY = Internal.createUniqueKey(LastCallers.LAST_CALLERS, DSL.name("last_callers_pkey"), new TableField[] { LastCallers.LAST_CALLERS.ID }, true);
    public static final UniqueKey<LoginAttemptsRecord> LOGIN_ATTEMPTS_PKEY = Internal.createUniqueKey(LoginAttempts.LOGIN_ATTEMPTS, DSL.name("login_attempts_pkey"), new TableField[] { LoginAttempts.LOGIN_ATTEMPTS.ID }, true);
    public static final UniqueKey<MessageBasesRecord> MESSAGE_BASES_PKEY = Internal.createUniqueKey(MessageBases.MESSAGE_BASES, DSL.name("message_bases_pkey"), new TableField[] { MessageBases.MESSAGE_BASES.ID }, true);
    public static final UniqueKey<MessageBasesRecord> MESSAGE_BASES_SLUG_KEY = Internal.createUniqueKey(MessageBases.MESSAGE_BASES, DSL.name("message_bases_slug_key"), new TableField[] { MessageBases.MESSAGE_BASES.SLUG }, true);
    public static final UniqueKey<NetmailRecord> NETMAIL_PKEY = Internal.createUniqueKey(Netmail.NETMAIL, DSL.name("netmail_pkey"), new TableField[] { Netmail.NETMAIL.ID }, true);
    public static final UniqueKey<OnelinersRecord> ONELINERS_PKEY = Internal.createUniqueKey(Oneliners.ONELINERS, DSL.name("oneliners_pkey"), new TableField[] { Oneliners.ONELINERS.ID }, true);
    public static final UniqueKey<PendingContentRecord> PENDING_CONTENT_PKEY = Internal.createUniqueKey(PendingContent.PENDING_CONTENT, DSL.name("pending_content_pkey"), new TableField[] { PendingContent.PENDING_CONTENT.ID }, true);
    public static final UniqueKey<PollOptionsRecord> POLL_OPTIONS_PKEY = Internal.createUniqueKey(PollOptions.POLL_OPTIONS, DSL.name("poll_options_pkey"), new TableField[] { PollOptions.POLL_OPTIONS.ID }, true);
    public static final UniqueKey<PollOptionsRecord> POLL_OPTIONS_POLL_ID_POSITION_KEY = Internal.createUniqueKey(PollOptions.POLL_OPTIONS, DSL.name("poll_options_poll_id_position_key"), new TableField[] { PollOptions.POLL_OPTIONS.POLL_ID, PollOptions.POLL_OPTIONS.POSITION }, true);
    public static final UniqueKey<PollVotesRecord> POLL_VOTES_PKEY = Internal.createUniqueKey(PollVotes.POLL_VOTES, DSL.name("poll_votes_pkey"), new TableField[] { PollVotes.POLL_VOTES.POLL_ID, PollVotes.POLL_VOTES.USER_ID }, true);
    public static final UniqueKey<PollsRecord> POLLS_PKEY = Internal.createUniqueKey(Polls.POLLS, DSL.name("polls_pkey"), new TableField[] { Polls.POLLS.ID }, true);
    public static final UniqueKey<PostsRecord> POSTS_PKEY = Internal.createUniqueKey(Posts.POSTS, DSL.name("posts_pkey"), new TableField[] { Posts.POSTS.ID }, true);
    public static final UniqueKey<ReactionsRecord> REACTIONS_PKEY = Internal.createUniqueKey(Reactions.REACTIONS, DSL.name("reactions_pkey"), new TableField[] { Reactions.REACTIONS.ID }, true);
    public static final UniqueKey<ReactionsRecord> REACTIONS_TARGET_TYPE_TARGET_ID_USER_ID_REACTION_KEY = Internal.createUniqueKey(Reactions.REACTIONS, DSL.name("reactions_target_type_target_id_user_id_reaction_key"), new TableField[] { Reactions.REACTIONS.TARGET_TYPE, Reactions.REACTIONS.TARGET_ID, Reactions.REACTIONS.USER_ID, Reactions.REACTIONS.REACTION }, true);
    public static final UniqueKey<RolesRecord> ROLES_NAME_KEY = Internal.createUniqueKey(Roles.ROLES, DSL.name("roles_name_key"), new TableField[] { Roles.ROLES.NAME }, true);
    public static final UniqueKey<RolesRecord> ROLES_PKEY = Internal.createUniqueKey(Roles.ROLES, DSL.name("roles_pkey"), new TableField[] { Roles.ROLES.ID }, true);
    public static final UniqueKey<SchemasRecord> SCHEMAS_PKEY = Internal.createUniqueKey(Schemas.SCHEMAS, DSL.name("schemas_pkey"), new TableField[] { Schemas.SCHEMAS.ID }, true);
    public static final UniqueKey<SchemasRecord> SCHEMAS_SLUG_VERSION_KEY = Internal.createUniqueKey(Schemas.SCHEMAS, DSL.name("schemas_slug_version_key"), new TableField[] { Schemas.SCHEMAS.SLUG, Schemas.SCHEMAS.VERSION }, true);
    public static final UniqueKey<SessionsRecord> SESSIONS_PKEY = Internal.createUniqueKey(Sessions.SESSIONS, DSL.name("sessions_pkey"), new TableField[] { Sessions.SESSIONS.TOKEN }, true);
    public static final UniqueKey<SysopActionsRecord> SYSOP_ACTIONS_PKEY = Internal.createUniqueKey(SysopActions.SYSOP_ACTIONS, DSL.name("sysop_actions_pkey"), new TableField[] { SysopActions.SYSOP_ACTIONS.ID }, true);
    public static final UniqueKey<SysopNotesRecord> SYSOP_NOTES_PKEY = Internal.createUniqueKey(SysopNotes.SYSOP_NOTES, DSL.name("sysop_notes_pkey"), new TableField[] { SysopNotes.SYSOP_NOTES.ID }, true);
    public static final UniqueKey<ThreadReadRecord> THREAD_READ_PKEY = Internal.createUniqueKey(ThreadRead.THREAD_READ, DSL.name("thread_read_pkey"), new TableField[] { ThreadRead.THREAD_READ.USER_ID, ThreadRead.THREAD_READ.THREAD_ID }, true);
    public static final UniqueKey<ThreadsRecord> THREADS_PKEY = Internal.createUniqueKey(Threads.THREADS, DSL.name("threads_pkey"), new TableField[] { Threads.THREADS.ID }, true);
    public static final UniqueKey<UserAchievementsRecord> USER_ACHIEVEMENTS_PKEY = Internal.createUniqueKey(UserAchievements.USER_ACHIEVEMENTS, DSL.name("user_achievements_pkey"), new TableField[] { UserAchievements.USER_ACHIEVEMENTS.USER_ID, UserAchievements.USER_ACHIEVEMENTS.ACHIEVEMENT_ID }, true);
    public static final UniqueKey<UserRolesRecord> USER_ROLES_PKEY = Internal.createUniqueKey(UserRoles.USER_ROLES, DSL.name("user_roles_pkey"), new TableField[] { UserRoles.USER_ROLES.USER_ID, UserRoles.USER_ROLES.ROLE_ID }, true);
    public static final UniqueKey<UsersRecord> USERS_HANDLE_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_handle_key"), new TableField[] { Users.USERS.HANDLE }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<WatchListRecord> WATCH_LIST_PKEY = Internal.createUniqueKey(WatchList.WATCH_LIST, DSL.name("watch_list_pkey"), new TableField[] { WatchList.WATCH_LIST.WATCHER_ID, WatchList.WATCH_LIST.WATCHED_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ActivityEventsRecord, UsersRecord> ACTIVITY_EVENTS__ACTIVITY_EVENTS_ACTOR_ID_FKEY = Internal.createForeignKey(ActivityEvents.ACTIVITY_EVENTS, DSL.name("activity_events_actor_id_fkey"), new TableField[] { ActivityEvents.ACTIVITY_EVENTS.ACTOR_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<ChatMessagesRecord, UsersRecord> CHAT_MESSAGES__CHAT_MESSAGES_AUTHOR_ID_FKEY = Internal.createForeignKey(ChatMessages.CHAT_MESSAGES, DSL.name("chat_messages_author_id_fkey"), new TableField[] { ChatMessages.CHAT_MESSAGES.AUTHOR_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<ChatRoomMembersRecord, ChatRoomsRecord> CHAT_ROOM_MEMBERS__CHAT_ROOM_MEMBERS_ROOM_ID_FKEY = Internal.createForeignKey(ChatRoomMembers.CHAT_ROOM_MEMBERS, DSL.name("chat_room_members_room_id_fkey"), new TableField[] { ChatRoomMembers.CHAT_ROOM_MEMBERS.ROOM_ID }, Keys.CHAT_ROOMS_PKEY, new TableField[] { ChatRooms.CHAT_ROOMS.ID }, true);
    public static final ForeignKey<ChatRoomMembersRecord, UsersRecord> CHAT_ROOM_MEMBERS__CHAT_ROOM_MEMBERS_USER_ID_FKEY = Internal.createForeignKey(ChatRoomMembers.CHAT_ROOM_MEMBERS, DSL.name("chat_room_members_user_id_fkey"), new TableField[] { ChatRoomMembers.CHAT_ROOM_MEMBERS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<ChatRoomMessagesRecord, UsersRecord> CHAT_ROOM_MESSAGES__CHAT_ROOM_MESSAGES_AUTHOR_ID_FKEY = Internal.createForeignKey(ChatRoomMessages.CHAT_ROOM_MESSAGES, DSL.name("chat_room_messages_author_id_fkey"), new TableField[] { ChatRoomMessages.CHAT_ROOM_MESSAGES.AUTHOR_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<ChatRoomMessagesRecord, ChatRoomsRecord> CHAT_ROOM_MESSAGES__CHAT_ROOM_MESSAGES_ROOM_ID_FKEY = Internal.createForeignKey(ChatRoomMessages.CHAT_ROOM_MESSAGES, DSL.name("chat_room_messages_room_id_fkey"), new TableField[] { ChatRoomMessages.CHAT_ROOM_MESSAGES.ROOM_ID }, Keys.CHAT_ROOMS_PKEY, new TableField[] { ChatRooms.CHAT_ROOMS.ID }, true);
    public static final ForeignKey<DocumentEditorsRecord, DocumentsRecord> DOCUMENT_EDITORS__DOCUMENT_EDITORS_DOCUMENT_ID_FKEY = Internal.createForeignKey(DocumentEditors.DOCUMENT_EDITORS, DSL.name("document_editors_document_id_fkey"), new TableField[] { DocumentEditors.DOCUMENT_EDITORS.DOCUMENT_ID }, Keys.DOCUMENTS_PKEY, new TableField[] { Documents.DOCUMENTS.ID }, true);
    public static final ForeignKey<DocumentEditorsRecord, UsersRecord> DOCUMENT_EDITORS__DOCUMENT_EDITORS_USER_ID_FKEY = Internal.createForeignKey(DocumentEditors.DOCUMENT_EDITORS, DSL.name("document_editors_user_id_fkey"), new TableField[] { DocumentEditors.DOCUMENT_EDITORS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<DocumentLinksRecord, DocumentsRecord> DOCUMENT_LINKS__DOCUMENT_LINKS_SOURCE_ID_FKEY = Internal.createForeignKey(DocumentLinks.DOCUMENT_LINKS, DSL.name("document_links_source_id_fkey"), new TableField[] { DocumentLinks.DOCUMENT_LINKS.SOURCE_ID }, Keys.DOCUMENTS_PKEY, new TableField[] { Documents.DOCUMENTS.ID }, true);
    public static final ForeignKey<DocumentLinksRecord, DocumentsRecord> DOCUMENT_LINKS__DOCUMENT_LINKS_TARGET_ID_FKEY = Internal.createForeignKey(DocumentLinks.DOCUMENT_LINKS, DSL.name("document_links_target_id_fkey"), new TableField[] { DocumentLinks.DOCUMENT_LINKS.TARGET_ID }, Keys.DOCUMENTS_PKEY, new TableField[] { Documents.DOCUMENTS.ID }, true);
    public static final ForeignKey<DocumentRevisionsRecord, DocumentsRecord> DOCUMENT_REVISIONS__DOCUMENT_REVISIONS_DOCUMENT_ID_FKEY = Internal.createForeignKey(DocumentRevisions.DOCUMENT_REVISIONS, DSL.name("document_revisions_document_id_fkey"), new TableField[] { DocumentRevisions.DOCUMENT_REVISIONS.DOCUMENT_ID }, Keys.DOCUMENTS_PKEY, new TableField[] { Documents.DOCUMENTS.ID }, true);
    public static final ForeignKey<DocumentRevisionsRecord, UsersRecord> DOCUMENT_REVISIONS__DOCUMENT_REVISIONS_EDITED_BY_FKEY = Internal.createForeignKey(DocumentRevisions.DOCUMENT_REVISIONS, DSL.name("document_revisions_edited_by_fkey"), new TableField[] { DocumentRevisions.DOCUMENT_REVISIONS.EDITED_BY }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<DocumentRevisionsRecord, SchemasRecord> DOCUMENT_REVISIONS__DOCUMENT_REVISIONS_TYPE_FK = Internal.createForeignKey(DocumentRevisions.DOCUMENT_REVISIONS, DSL.name("document_revisions_type_fk"), new TableField[] { DocumentRevisions.DOCUMENT_REVISIONS.TYPE_SLUG, DocumentRevisions.DOCUMENT_REVISIONS.TYPE_VERSION }, Keys.SCHEMAS_SLUG_VERSION_KEY, new TableField[] { Schemas.SCHEMAS.SLUG, Schemas.SCHEMAS.VERSION }, true);
    public static final ForeignKey<DocumentsRecord, UsersRecord> DOCUMENTS__DOCUMENTS_AUTHOR_ID_FKEY = Internal.createForeignKey(Documents.DOCUMENTS, DSL.name("documents_author_id_fkey"), new TableField[] { Documents.DOCUMENTS.AUTHOR_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<DocumentsRecord, UsersRecord> DOCUMENTS__DOCUMENTS_DELETED_BY_FKEY = Internal.createForeignKey(Documents.DOCUMENTS, DSL.name("documents_deleted_by_fkey"), new TableField[] { Documents.DOCUMENTS.DELETED_BY }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<DocumentsRecord, SchemasRecord> DOCUMENTS__DOCUMENTS_TYPE_FK = Internal.createForeignKey(Documents.DOCUMENTS, DSL.name("documents_type_fk"), new TableField[] { Documents.DOCUMENTS.TYPE_SLUG, Documents.DOCUMENTS.TYPE_VERSION }, Keys.SCHEMAS_SLUG_VERSION_KEY, new TableField[] { Schemas.SCHEMAS.SLUG, Schemas.SCHEMAS.VERSION }, true);
    public static final ForeignKey<LastCallersRecord, UsersRecord> LAST_CALLERS__LAST_CALLERS_USER_ID_FKEY = Internal.createForeignKey(LastCallers.LAST_CALLERS, DSL.name("last_callers_user_id_fkey"), new TableField[] { LastCallers.LAST_CALLERS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<NetmailRecord, UsersRecord> NETMAIL__NETMAIL_FROM_ID_FKEY = Internal.createForeignKey(Netmail.NETMAIL, DSL.name("netmail_from_id_fkey"), new TableField[] { Netmail.NETMAIL.FROM_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<NetmailRecord, UsersRecord> NETMAIL__NETMAIL_TO_ID_FKEY = Internal.createForeignKey(Netmail.NETMAIL, DSL.name("netmail_to_id_fkey"), new TableField[] { Netmail.NETMAIL.TO_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<OnelinersRecord, UsersRecord> ONELINERS__ONELINERS_AUTHOR_ID_FKEY = Internal.createForeignKey(Oneliners.ONELINERS, DSL.name("oneliners_author_id_fkey"), new TableField[] { Oneliners.ONELINERS.AUTHOR_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<PendingContentRecord, UsersRecord> PENDING_CONTENT__PENDING_CONTENT_AUTHOR_ID_FKEY = Internal.createForeignKey(PendingContent.PENDING_CONTENT, DSL.name("pending_content_author_id_fkey"), new TableField[] { PendingContent.PENDING_CONTENT.AUTHOR_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<PendingContentRecord, UsersRecord> PENDING_CONTENT__PENDING_CONTENT_DECIDED_BY_FKEY = Internal.createForeignKey(PendingContent.PENDING_CONTENT, DSL.name("pending_content_decided_by_fkey"), new TableField[] { PendingContent.PENDING_CONTENT.DECIDED_BY }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<PollOptionsRecord, PollsRecord> POLL_OPTIONS__POLL_OPTIONS_POLL_ID_FKEY = Internal.createForeignKey(PollOptions.POLL_OPTIONS, DSL.name("poll_options_poll_id_fkey"), new TableField[] { PollOptions.POLL_OPTIONS.POLL_ID }, Keys.POLLS_PKEY, new TableField[] { Polls.POLLS.ID }, true);
    public static final ForeignKey<PollVotesRecord, PollOptionsRecord> POLL_VOTES__POLL_VOTES_OPTION_ID_FKEY = Internal.createForeignKey(PollVotes.POLL_VOTES, DSL.name("poll_votes_option_id_fkey"), new TableField[] { PollVotes.POLL_VOTES.OPTION_ID }, Keys.POLL_OPTIONS_PKEY, new TableField[] { PollOptions.POLL_OPTIONS.ID }, true);
    public static final ForeignKey<PollVotesRecord, PollsRecord> POLL_VOTES__POLL_VOTES_POLL_ID_FKEY = Internal.createForeignKey(PollVotes.POLL_VOTES, DSL.name("poll_votes_poll_id_fkey"), new TableField[] { PollVotes.POLL_VOTES.POLL_ID }, Keys.POLLS_PKEY, new TableField[] { Polls.POLLS.ID }, true);
    public static final ForeignKey<PollVotesRecord, UsersRecord> POLL_VOTES__POLL_VOTES_USER_ID_FKEY = Internal.createForeignKey(PollVotes.POLL_VOTES, DSL.name("poll_votes_user_id_fkey"), new TableField[] { PollVotes.POLL_VOTES.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<PollsRecord, UsersRecord> POLLS__POLLS_AUTHOR_ID_FKEY = Internal.createForeignKey(Polls.POLLS, DSL.name("polls_author_id_fkey"), new TableField[] { Polls.POLLS.AUTHOR_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<PostsRecord, UsersRecord> POSTS__POSTS_AUTHOR_ID_FKEY = Internal.createForeignKey(Posts.POSTS, DSL.name("posts_author_id_fkey"), new TableField[] { Posts.POSTS.AUTHOR_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<PostsRecord, ThreadsRecord> POSTS__POSTS_THREAD_ID_FKEY = Internal.createForeignKey(Posts.POSTS, DSL.name("posts_thread_id_fkey"), new TableField[] { Posts.POSTS.THREAD_ID }, Keys.THREADS_PKEY, new TableField[] { Threads.THREADS.ID }, true);
    public static final ForeignKey<ReactionsRecord, UsersRecord> REACTIONS__REACTIONS_USER_ID_FKEY = Internal.createForeignKey(Reactions.REACTIONS, DSL.name("reactions_user_id_fkey"), new TableField[] { Reactions.REACTIONS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<SchemasRecord, UsersRecord> SCHEMAS__SCHEMAS_CREATED_BY_FKEY = Internal.createForeignKey(Schemas.SCHEMAS, DSL.name("schemas_created_by_fkey"), new TableField[] { Schemas.SCHEMAS.CREATED_BY }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<SessionsRecord, UsersRecord> SESSIONS__SESSIONS_USER_ID_FKEY = Internal.createForeignKey(Sessions.SESSIONS, DSL.name("sessions_user_id_fkey"), new TableField[] { Sessions.SESSIONS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<SysopActionsRecord, UsersRecord> SYSOP_ACTIONS__SYSOP_ACTIONS_ACTOR_ID_FKEY = Internal.createForeignKey(SysopActions.SYSOP_ACTIONS, DSL.name("sysop_actions_actor_id_fkey"), new TableField[] { SysopActions.SYSOP_ACTIONS.ACTOR_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<SysopNotesRecord, UsersRecord> SYSOP_NOTES__SYSOP_NOTES_AUTHOR_ID_FKEY = Internal.createForeignKey(SysopNotes.SYSOP_NOTES, DSL.name("sysop_notes_author_id_fkey"), new TableField[] { SysopNotes.SYSOP_NOTES.AUTHOR_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<SysopNotesRecord, UsersRecord> SYSOP_NOTES__SYSOP_NOTES_SUBJECT_ID_FKEY = Internal.createForeignKey(SysopNotes.SYSOP_NOTES, DSL.name("sysop_notes_subject_id_fkey"), new TableField[] { SysopNotes.SYSOP_NOTES.SUBJECT_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<ThreadReadRecord, ThreadsRecord> THREAD_READ__THREAD_READ_THREAD_ID_FKEY = Internal.createForeignKey(ThreadRead.THREAD_READ, DSL.name("thread_read_thread_id_fkey"), new TableField[] { ThreadRead.THREAD_READ.THREAD_ID }, Keys.THREADS_PKEY, new TableField[] { Threads.THREADS.ID }, true);
    public static final ForeignKey<ThreadReadRecord, UsersRecord> THREAD_READ__THREAD_READ_USER_ID_FKEY = Internal.createForeignKey(ThreadRead.THREAD_READ, DSL.name("thread_read_user_id_fkey"), new TableField[] { ThreadRead.THREAD_READ.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<ThreadsRecord, UsersRecord> THREADS__THREADS_AUTHOR_ID_FKEY = Internal.createForeignKey(Threads.THREADS, DSL.name("threads_author_id_fkey"), new TableField[] { Threads.THREADS.AUTHOR_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<ThreadsRecord, MessageBasesRecord> THREADS__THREADS_BASE_ID_FKEY = Internal.createForeignKey(Threads.THREADS, DSL.name("threads_base_id_fkey"), new TableField[] { Threads.THREADS.BASE_ID }, Keys.MESSAGE_BASES_PKEY, new TableField[] { MessageBases.MESSAGE_BASES.ID }, true);
    public static final ForeignKey<UserAchievementsRecord, AchievementsRecord> USER_ACHIEVEMENTS__USER_ACHIEVEMENTS_ACHIEVEMENT_ID_FKEY = Internal.createForeignKey(UserAchievements.USER_ACHIEVEMENTS, DSL.name("user_achievements_achievement_id_fkey"), new TableField[] { UserAchievements.USER_ACHIEVEMENTS.ACHIEVEMENT_ID }, Keys.ACHIEVEMENTS_PKEY, new TableField[] { Achievements.ACHIEVEMENTS.ID }, true);
    public static final ForeignKey<UserAchievementsRecord, UsersRecord> USER_ACHIEVEMENTS__USER_ACHIEVEMENTS_USER_ID_FKEY = Internal.createForeignKey(UserAchievements.USER_ACHIEVEMENTS, DSL.name("user_achievements_user_id_fkey"), new TableField[] { UserAchievements.USER_ACHIEVEMENTS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<UserRolesRecord, RolesRecord> USER_ROLES__USER_ROLES_ROLE_ID_FKEY = Internal.createForeignKey(UserRoles.USER_ROLES, DSL.name("user_roles_role_id_fkey"), new TableField[] { UserRoles.USER_ROLES.ROLE_ID }, Keys.ROLES_PKEY, new TableField[] { Roles.ROLES.ID }, true);
    public static final ForeignKey<UserRolesRecord, UsersRecord> USER_ROLES__USER_ROLES_USER_ID_FKEY = Internal.createForeignKey(UserRoles.USER_ROLES, DSL.name("user_roles_user_id_fkey"), new TableField[] { UserRoles.USER_ROLES.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<WatchListRecord, UsersRecord> WATCH_LIST__WATCH_LIST_WATCHED_ID_FKEY = Internal.createForeignKey(WatchList.WATCH_LIST, DSL.name("watch_list_watched_id_fkey"), new TableField[] { WatchList.WATCH_LIST.WATCHED_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<WatchListRecord, UsersRecord> WATCH_LIST__WATCH_LIST_WATCHER_ID_FKEY = Internal.createForeignKey(WatchList.WATCH_LIST, DSL.name("watch_list_watcher_id_fkey"), new TableField[] { WatchList.WATCH_LIST.WATCHER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
}
