/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq;


import io.aeyer.voidcore.jooq.tables.Achievements;
import io.aeyer.voidcore.jooq.tables.AclGrants;
import io.aeyer.voidcore.jooq.tables.ActivityEvents;
import io.aeyer.voidcore.jooq.tables.ChatMessages;
import io.aeyer.voidcore.jooq.tables.ChatRoomMembers;
import io.aeyer.voidcore.jooq.tables.ChatRoomMessages;
import io.aeyer.voidcore.jooq.tables.ChatRooms;
import io.aeyer.voidcore.jooq.tables.Counters;
import io.aeyer.voidcore.jooq.tables.DocumentEditors;
import io.aeyer.voidcore.jooq.tables.DocumentLinks;
import io.aeyer.voidcore.jooq.tables.DocumentRevisions;
import io.aeyer.voidcore.jooq.tables.Documents;
import io.aeyer.voidcore.jooq.tables.DoorState;
import io.aeyer.voidcore.jooq.tables.Fortunes;
import io.aeyer.voidcore.jooq.tables.InstanceFeatures;
import io.aeyer.voidcore.jooq.tables.LastCallers;
import io.aeyer.voidcore.jooq.tables.LoginAttempts;
import io.aeyer.voidcore.jooq.tables.MessageBases;
import io.aeyer.voidcore.jooq.tables.Netmail;
import io.aeyer.voidcore.jooq.tables.Oneliners;
import io.aeyer.voidcore.jooq.tables.PendingContent;
import io.aeyer.voidcore.jooq.tables.PollOptions;
import io.aeyer.voidcore.jooq.tables.PollVotes;
import io.aeyer.voidcore.jooq.tables.Polls;
import io.aeyer.voidcore.jooq.tables.Posts;
import io.aeyer.voidcore.jooq.tables.Reactions;
import io.aeyer.voidcore.jooq.tables.Roles;
import io.aeyer.voidcore.jooq.tables.Schemas;
import io.aeyer.voidcore.jooq.tables.Sessions;
import io.aeyer.voidcore.jooq.tables.SysopActions;
import io.aeyer.voidcore.jooq.tables.SysopNotes;
import io.aeyer.voidcore.jooq.tables.ThreadRead;
import io.aeyer.voidcore.jooq.tables.Threads;
import io.aeyer.voidcore.jooq.tables.UserAchievements;
import io.aeyer.voidcore.jooq.tables.UserRoles;
import io.aeyer.voidcore.jooq.tables.Users;
import io.aeyer.voidcore.jooq.tables.WatchList;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.achievements</code>.
     */
    public final Achievements ACHIEVEMENTS = Achievements.ACHIEVEMENTS;

    /**
     * The table <code>public.acl_grants</code>.
     */
    public final AclGrants ACL_GRANTS = AclGrants.ACL_GRANTS;

    /**
     * The table <code>public.activity_events</code>.
     */
    public final ActivityEvents ACTIVITY_EVENTS = ActivityEvents.ACTIVITY_EVENTS;

    /**
     * The table <code>public.chat_messages</code>.
     */
    public final ChatMessages CHAT_MESSAGES = ChatMessages.CHAT_MESSAGES;

    /**
     * The table <code>public.chat_room_members</code>.
     */
    public final ChatRoomMembers CHAT_ROOM_MEMBERS = ChatRoomMembers.CHAT_ROOM_MEMBERS;

    /**
     * The table <code>public.chat_room_messages</code>.
     */
    public final ChatRoomMessages CHAT_ROOM_MESSAGES = ChatRoomMessages.CHAT_ROOM_MESSAGES;

    /**
     * The table <code>public.chat_rooms</code>.
     */
    public final ChatRooms CHAT_ROOMS = ChatRooms.CHAT_ROOMS;

    /**
     * The table <code>public.counters</code>.
     */
    public final Counters COUNTERS = Counters.COUNTERS;

    /**
     * The table <code>public.document_editors</code>.
     */
    public final DocumentEditors DOCUMENT_EDITORS = DocumentEditors.DOCUMENT_EDITORS;

    /**
     * The table <code>public.document_links</code>.
     */
    public final DocumentLinks DOCUMENT_LINKS = DocumentLinks.DOCUMENT_LINKS;

    /**
     * The table <code>public.document_revisions</code>.
     */
    public final DocumentRevisions DOCUMENT_REVISIONS = DocumentRevisions.DOCUMENT_REVISIONS;

    /**
     * The table <code>public.documents</code>.
     */
    public final Documents DOCUMENTS = Documents.DOCUMENTS;

    /**
     * The table <code>public.door_state</code>.
     */
    public final DoorState DOOR_STATE = DoorState.DOOR_STATE;

    /**
     * The table <code>public.fortunes</code>.
     */
    public final Fortunes FORTUNES = Fortunes.FORTUNES;

    /**
     * The table <code>public.instance_features</code>.
     */
    public final InstanceFeatures INSTANCE_FEATURES = InstanceFeatures.INSTANCE_FEATURES;

    /**
     * The table <code>public.last_callers</code>.
     */
    public final LastCallers LAST_CALLERS = LastCallers.LAST_CALLERS;

    /**
     * The table <code>public.login_attempts</code>.
     */
    public final LoginAttempts LOGIN_ATTEMPTS = LoginAttempts.LOGIN_ATTEMPTS;

    /**
     * The table <code>public.message_bases</code>.
     */
    public final MessageBases MESSAGE_BASES = MessageBases.MESSAGE_BASES;

    /**
     * The table <code>public.netmail</code>.
     */
    public final Netmail NETMAIL = Netmail.NETMAIL;

    /**
     * The table <code>public.oneliners</code>.
     */
    public final Oneliners ONELINERS = Oneliners.ONELINERS;

    /**
     * The table <code>public.pending_content</code>.
     */
    public final PendingContent PENDING_CONTENT = PendingContent.PENDING_CONTENT;

    /**
     * The table <code>public.poll_options</code>.
     */
    public final PollOptions POLL_OPTIONS = PollOptions.POLL_OPTIONS;

    /**
     * The table <code>public.poll_votes</code>.
     */
    public final PollVotes POLL_VOTES = PollVotes.POLL_VOTES;

    /**
     * The table <code>public.polls</code>.
     */
    public final Polls POLLS = Polls.POLLS;

    /**
     * The table <code>public.posts</code>.
     */
    public final Posts POSTS = Posts.POSTS;

    /**
     * The table <code>public.reactions</code>.
     */
    public final Reactions REACTIONS = Reactions.REACTIONS;

    /**
     * The table <code>public.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.schemas</code>.
     */
    public final Schemas SCHEMAS = Schemas.SCHEMAS;

    /**
     * The table <code>public.sessions</code>.
     */
    public final Sessions SESSIONS = Sessions.SESSIONS;

    /**
     * The table <code>public.sysop_actions</code>.
     */
    public final SysopActions SYSOP_ACTIONS = SysopActions.SYSOP_ACTIONS;

    /**
     * The table <code>public.sysop_notes</code>.
     */
    public final SysopNotes SYSOP_NOTES = SysopNotes.SYSOP_NOTES;

    /**
     * The table <code>public.thread_read</code>.
     */
    public final ThreadRead THREAD_READ = ThreadRead.THREAD_READ;

    /**
     * The table <code>public.threads</code>.
     */
    public final Threads THREADS = Threads.THREADS;

    /**
     * The table <code>public.user_achievements</code>.
     */
    public final UserAchievements USER_ACHIEVEMENTS = UserAchievements.USER_ACHIEVEMENTS;

    /**
     * The table <code>public.user_roles</code>.
     */
    public final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * The table <code>public.watch_list</code>.
     */
    public final WatchList WATCH_LIST = WatchList.WATCH_LIST;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Achievements.ACHIEVEMENTS,
            AclGrants.ACL_GRANTS,
            ActivityEvents.ACTIVITY_EVENTS,
            ChatMessages.CHAT_MESSAGES,
            ChatRoomMembers.CHAT_ROOM_MEMBERS,
            ChatRoomMessages.CHAT_ROOM_MESSAGES,
            ChatRooms.CHAT_ROOMS,
            Counters.COUNTERS,
            DocumentEditors.DOCUMENT_EDITORS,
            DocumentLinks.DOCUMENT_LINKS,
            DocumentRevisions.DOCUMENT_REVISIONS,
            Documents.DOCUMENTS,
            DoorState.DOOR_STATE,
            Fortunes.FORTUNES,
            InstanceFeatures.INSTANCE_FEATURES,
            LastCallers.LAST_CALLERS,
            LoginAttempts.LOGIN_ATTEMPTS,
            MessageBases.MESSAGE_BASES,
            Netmail.NETMAIL,
            Oneliners.ONELINERS,
            PendingContent.PENDING_CONTENT,
            PollOptions.POLL_OPTIONS,
            PollVotes.POLL_VOTES,
            Polls.POLLS,
            Posts.POSTS,
            Reactions.REACTIONS,
            Roles.ROLES,
            Schemas.SCHEMAS,
            Sessions.SESSIONS,
            SysopActions.SYSOP_ACTIONS,
            SysopNotes.SYSOP_NOTES,
            ThreadRead.THREAD_READ,
            Threads.THREADS,
            UserAchievements.USER_ACHIEVEMENTS,
            UserRoles.USER_ROLES,
            Users.USERS,
            WatchList.WATCH_LIST
        );
    }
}
