/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq;


import io.aeyer.voidcore.jooq.tables.Achievements;
import io.aeyer.voidcore.jooq.tables.AclGrants;
import io.aeyer.voidcore.jooq.tables.ActivityEvents;
import io.aeyer.voidcore.jooq.tables.ChatMessages;
import io.aeyer.voidcore.jooq.tables.ChatRoomMembers;
import io.aeyer.voidcore.jooq.tables.ChatRoomMessages;
import io.aeyer.voidcore.jooq.tables.ChatRooms;
import io.aeyer.voidcore.jooq.tables.Counters;
import io.aeyer.voidcore.jooq.tables.DocumentEditors;
import io.aeyer.voidcore.jooq.tables.DocumentLinks;
import io.aeyer.voidcore.jooq.tables.DocumentRevisions;
import io.aeyer.voidcore.jooq.tables.Documents;
import io.aeyer.voidcore.jooq.tables.DoorState;
import io.aeyer.voidcore.jooq.tables.Fortunes;
import io.aeyer.voidcore.jooq.tables.InstanceFeatures;
import io.aeyer.voidcore.jooq.tables.LastCallers;
import io.aeyer.voidcore.jooq.tables.LoginAttempts;
import io.aeyer.voidcore.jooq.tables.MessageBases;
import io.aeyer.voidcore.jooq.tables.Netmail;
import io.aeyer.voidcore.jooq.tables.Oneliners;
import io.aeyer.voidcore.jooq.tables.PendingContent;
import io.aeyer.voidcore.jooq.tables.PollOptions;
import io.aeyer.voidcore.jooq.tables.PollVotes;
import io.aeyer.voidcore.jooq.tables.Polls;
import io.aeyer.voidcore.jooq.tables.Posts;
import io.aeyer.voidcore.jooq.tables.Reactions;
import io.aeyer.voidcore.jooq.tables.Roles;
import io.aeyer.voidcore.jooq.tables.Schemas;
import io.aeyer.voidcore.jooq.tables.Sessions;
import io.aeyer.voidcore.jooq.tables.SysopActions;
import io.aeyer.voidcore.jooq.tables.SysopNotes;
import io.aeyer.voidcore.jooq.tables.ThreadRead;
import io.aeyer.voidcore.jooq.tables.Threads;
import io.aeyer.voidcore.jooq.tables.UserAchievements;
import io.aeyer.voidcore.jooq.tables.UserRoles;
import io.aeyer.voidcore.jooq.tables.Users;
import io.aeyer.voidcore.jooq.tables.WatchList;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.achievements</code>.
     */
    public static final Achievements ACHIEVEMENTS = Achievements.ACHIEVEMENTS;

    /**
     * The table <code>public.acl_grants</code>.
     */
    public static final AclGrants ACL_GRANTS = AclGrants.ACL_GRANTS;

    /**
     * The table <code>public.activity_events</code>.
     */
    public static final ActivityEvents ACTIVITY_EVENTS = ActivityEvents.ACTIVITY_EVENTS;

    /**
     * The table <code>public.chat_messages</code>.
     */
    public static final ChatMessages CHAT_MESSAGES = ChatMessages.CHAT_MESSAGES;

    /**
     * The table <code>public.chat_room_members</code>.
     */
    public static final ChatRoomMembers CHAT_ROOM_MEMBERS = ChatRoomMembers.CHAT_ROOM_MEMBERS;

    /**
     * The table <code>public.chat_room_messages</code>.
     */
    public static final ChatRoomMessages CHAT_ROOM_MESSAGES = ChatRoomMessages.CHAT_ROOM_MESSAGES;

    /**
     * The table <code>public.chat_rooms</code>.
     */
    public static final ChatRooms CHAT_ROOMS = ChatRooms.CHAT_ROOMS;

    /**
     * The table <code>public.counters</code>.
     */
    public static final Counters COUNTERS = Counters.COUNTERS;

    /**
     * The table <code>public.document_editors</code>.
     */
    public static final DocumentEditors DOCUMENT_EDITORS = DocumentEditors.DOCUMENT_EDITORS;

    /**
     * The table <code>public.document_links</code>.
     */
    public static final DocumentLinks DOCUMENT_LINKS = DocumentLinks.DOCUMENT_LINKS;

    /**
     * The table <code>public.document_revisions</code>.
     */
    public static final DocumentRevisions DOCUMENT_REVISIONS = DocumentRevisions.DOCUMENT_REVISIONS;

    /**
     * The table <code>public.documents</code>.
     */
    public static final Documents DOCUMENTS = Documents.DOCUMENTS;

    /**
     * The table <code>public.door_state</code>.
     */
    public static final DoorState DOOR_STATE = DoorState.DOOR_STATE;

    /**
     * The table <code>public.fortunes</code>.
     */
    public static final Fortunes FORTUNES = Fortunes.FORTUNES;

    /**
     * The table <code>public.instance_features</code>.
     */
    public static final InstanceFeatures INSTANCE_FEATURES = InstanceFeatures.INSTANCE_FEATURES;

    /**
     * The table <code>public.last_callers</code>.
     */
    public static final LastCallers LAST_CALLERS = LastCallers.LAST_CALLERS;

    /**
     * The table <code>public.login_attempts</code>.
     */
    public static final LoginAttempts LOGIN_ATTEMPTS = LoginAttempts.LOGIN_ATTEMPTS;

    /**
     * The table <code>public.message_bases</code>.
     */
    public static final MessageBases MESSAGE_BASES = MessageBases.MESSAGE_BASES;

    /**
     * The table <code>public.netmail</code>.
     */
    public static final Netmail NETMAIL = Netmail.NETMAIL;

    /**
     * The table <code>public.oneliners</code>.
     */
    public static final Oneliners ONELINERS = Oneliners.ONELINERS;

    /**
     * The table <code>public.pending_content</code>.
     */
    public static final PendingContent PENDING_CONTENT = PendingContent.PENDING_CONTENT;

    /**
     * The table <code>public.poll_options</code>.
     */
    public static final PollOptions POLL_OPTIONS = PollOptions.POLL_OPTIONS;

    /**
     * The table <code>public.poll_votes</code>.
     */
    public static final PollVotes POLL_VOTES = PollVotes.POLL_VOTES;

    /**
     * The table <code>public.polls</code>.
     */
    public static final Polls POLLS = Polls.POLLS;

    /**
     * The table <code>public.posts</code>.
     */
    public static final Posts POSTS = Posts.POSTS;

    /**
     * The table <code>public.reactions</code>.
     */
    public static final Reactions REACTIONS = Reactions.REACTIONS;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.schemas</code>.
     */
    public static final Schemas SCHEMAS = Schemas.SCHEMAS;

    /**
     * The table <code>public.sessions</code>.
     */
    public static final Sessions SESSIONS = Sessions.SESSIONS;

    /**
     * The table <code>public.sysop_actions</code>.
     */
    public static final SysopActions SYSOP_ACTIONS = SysopActions.SYSOP_ACTIONS;

    /**
     * The table <code>public.sysop_notes</code>.
     */
    public static final SysopNotes SYSOP_NOTES = SysopNotes.SYSOP_NOTES;

    /**
     * The table <code>public.thread_read</code>.
     */
    public static final ThreadRead THREAD_READ = ThreadRead.THREAD_READ;

    /**
     * The table <code>public.threads</code>.
     */
    public static final Threads THREADS = Threads.THREADS;

    /**
     * The table <code>public.user_achievements</code>.
     */
    public static final UserAchievements USER_ACHIEVEMENTS = UserAchievements.USER_ACHIEVEMENTS;

    /**
     * The table <code>public.user_roles</code>.
     */
    public static final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>public.watch_list</code>.
     */
    public static final WatchList WATCH_LIST = WatchList.WATCH_LIST;
}
