/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Indexes;
import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.Users.UsersPath;
import io.aeyer.voidcore.jooq.tables.records.ActivityEventsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ActivityEvents extends TableImpl<ActivityEventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.activity_events</code>
     */
    public static final ActivityEvents ACTIVITY_EVENTS = new ActivityEvents();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActivityEventsRecord> getRecordType() {
        return ActivityEventsRecord.class;
    }

    /**
     * The column <code>public.activity_events.id</code>.
     */
    public final TableField<ActivityEventsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.activity_events.topic</code>.
     */
    public final TableField<ActivityEventsRecord, String> TOPIC = createField(DSL.name("topic"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.activity_events.actor_id</code>.
     */
    public final TableField<ActivityEventsRecord, Long> ACTOR_ID = createField(DSL.name("actor_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.activity_events.payload</code>.
     */
    public final TableField<ActivityEventsRecord, JSONB> PAYLOAD = createField(DSL.name("payload"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.activity_events.emitted_at</code>.
     */
    public final TableField<ActivityEventsRecord, OffsetDateTime> EMITTED_AT = createField(DSL.name("emitted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private ActivityEvents(Name alias, Table<ActivityEventsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ActivityEvents(Name alias, Table<ActivityEventsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.activity_events</code> table reference
     */
    public ActivityEvents(String alias) {
        this(DSL.name(alias), ACTIVITY_EVENTS);
    }

    /**
     * Create an aliased <code>public.activity_events</code> table reference
     */
    public ActivityEvents(Name alias) {
        this(alias, ACTIVITY_EVENTS);
    }

    /**
     * Create a <code>public.activity_events</code> table reference
     */
    public ActivityEvents() {
        this(DSL.name("activity_events"), null);
    }

    public <O extends Record> ActivityEvents(Table<O> path, ForeignKey<O, ActivityEventsRecord> childPath, InverseForeignKey<O, ActivityEventsRecord> parentPath) {
        super(path, childPath, parentPath, ACTIVITY_EVENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ActivityEventsPath extends ActivityEvents implements Path<ActivityEventsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ActivityEventsPath(Table<O> path, ForeignKey<O, ActivityEventsRecord> childPath, InverseForeignKey<O, ActivityEventsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ActivityEventsPath(Name alias, Table<ActivityEventsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ActivityEventsPath as(String alias) {
            return new ActivityEventsPath(DSL.name(alias), this);
        }

        @Override
        public ActivityEventsPath as(Name alias) {
            return new ActivityEventsPath(alias, this);
        }

        @Override
        public ActivityEventsPath as(Table<?> alias) {
            return new ActivityEventsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_ACTIVITY_EVENTS_ACTOR, Indexes.IDX_ACTIVITY_EVENTS_EMITTED);
    }

    @Override
    public Identity<ActivityEventsRecord, Long> getIdentity() {
        return (Identity<ActivityEventsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ActivityEventsRecord> getPrimaryKey() {
        return Keys.ACTIVITY_EVENTS_PKEY;
    }

    @Override
    public List<ForeignKey<ActivityEventsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ACTIVITY_EVENTS__ACTIVITY_EVENTS_ACTOR_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.ACTIVITY_EVENTS__ACTIVITY_EVENTS_ACTOR_ID_FKEY, null);

        return _users;
    }

    @Override
    public ActivityEvents as(String alias) {
        return new ActivityEvents(DSL.name(alias), this);
    }

    @Override
    public ActivityEvents as(Name alias) {
        return new ActivityEvents(alias, this);
    }

    @Override
    public ActivityEvents as(Table<?> alias) {
        return new ActivityEvents(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActivityEvents rename(String name) {
        return new ActivityEvents(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActivityEvents rename(Name name) {
        return new ActivityEvents(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActivityEvents rename(Table<?> name) {
        return new ActivityEvents(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActivityEvents where(Condition condition) {
        return new ActivityEvents(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActivityEvents where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActivityEvents where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActivityEvents where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ActivityEvents where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ActivityEvents where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ActivityEvents where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ActivityEvents where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActivityEvents whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActivityEvents whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
