/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Indexes;
import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.ChatRoomMembers.ChatRoomMembersPath;
import io.aeyer.voidcore.jooq.tables.ChatRoomMessages.ChatRoomMessagesPath;
import io.aeyer.voidcore.jooq.tables.Users.UsersPath;
import io.aeyer.voidcore.jooq.tables.records.ChatRoomsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChatRooms extends TableImpl<ChatRoomsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.chat_rooms</code>
     */
    public static final ChatRooms CHAT_ROOMS = new ChatRooms();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChatRoomsRecord> getRecordType() {
        return ChatRoomsRecord.class;
    }

    /**
     * The column <code>public.chat_rooms.id</code>.
     */
    public final TableField<ChatRoomsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.chat_rooms.slug</code>.
     */
    public final TableField<ChatRoomsRecord, String> SLUG = createField(DSL.name("slug"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.chat_rooms.label</code>.
     */
    public final TableField<ChatRoomsRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.chat_rooms.is_private</code>.
     */
    public final TableField<ChatRoomsRecord, Boolean> IS_PRIVATE = createField(DSL.name("is_private"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.chat_rooms.is_active</code>.
     */
    public final TableField<ChatRoomsRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.chat_rooms.sort_order</code>.
     */
    public final TableField<ChatRoomsRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.chat_rooms.created_at</code>.
     */
    public final TableField<ChatRoomsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.chat_rooms.is_dm</code>.
     */
    public final TableField<ChatRoomsRecord, Boolean> IS_DM = createField(DSL.name("is_dm"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    private ChatRooms(Name alias, Table<ChatRoomsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ChatRooms(Name alias, Table<ChatRoomsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.chat_rooms</code> table reference
     */
    public ChatRooms(String alias) {
        this(DSL.name(alias), CHAT_ROOMS);
    }

    /**
     * Create an aliased <code>public.chat_rooms</code> table reference
     */
    public ChatRooms(Name alias) {
        this(alias, CHAT_ROOMS);
    }

    /**
     * Create a <code>public.chat_rooms</code> table reference
     */
    public ChatRooms() {
        this(DSL.name("chat_rooms"), null);
    }

    public <O extends Record> ChatRooms(Table<O> path, ForeignKey<O, ChatRoomsRecord> childPath, InverseForeignKey<O, ChatRoomsRecord> parentPath) {
        super(path, childPath, parentPath, CHAT_ROOMS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ChatRoomsPath extends ChatRooms implements Path<ChatRoomsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ChatRoomsPath(Table<O> path, ForeignKey<O, ChatRoomsRecord> childPath, InverseForeignKey<O, ChatRoomsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ChatRoomsPath(Name alias, Table<ChatRoomsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ChatRoomsPath as(String alias) {
            return new ChatRoomsPath(DSL.name(alias), this);
        }

        @Override
        public ChatRoomsPath as(Name alias) {
            return new ChatRoomsPath(alias, this);
        }

        @Override
        public ChatRoomsPath as(Table<?> alias) {
            return new ChatRoomsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CHAT_ROOMS_SORT);
    }

    @Override
    public Identity<ChatRoomsRecord, Long> getIdentity() {
        return (Identity<ChatRoomsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ChatRoomsRecord> getPrimaryKey() {
        return Keys.CHAT_ROOMS_PKEY;
    }

    @Override
    public List<UniqueKey<ChatRoomsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CHAT_ROOMS_SLUG_KEY);
    }

    private transient ChatRoomMembersPath _chatRoomMembers;

    /**
     * Get the implicit to-many join path to the
     * <code>public.chat_room_members</code> table
     */
    public ChatRoomMembersPath chatRoomMembers() {
        if (_chatRoomMembers == null)
            _chatRoomMembers = new ChatRoomMembersPath(this, null, Keys.CHAT_ROOM_MEMBERS__CHAT_ROOM_MEMBERS_ROOM_ID_FKEY.getInverseKey());

        return _chatRoomMembers;
    }

    private transient ChatRoomMessagesPath _chatRoomMessages;

    /**
     * Get the implicit to-many join path to the
     * <code>public.chat_room_messages</code> table
     */
    public ChatRoomMessagesPath chatRoomMessages() {
        if (_chatRoomMessages == null)
            _chatRoomMessages = new ChatRoomMessagesPath(this, null, Keys.CHAT_ROOM_MESSAGES__CHAT_ROOM_MESSAGES_ROOM_ID_FKEY.getInverseKey());

        return _chatRoomMessages;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.users</code>
     * table
     */
    public UsersPath users() {
        return chatRoomMembers().users();
    }

    @Override
    public ChatRooms as(String alias) {
        return new ChatRooms(DSL.name(alias), this);
    }

    @Override
    public ChatRooms as(Name alias) {
        return new ChatRooms(alias, this);
    }

    @Override
    public ChatRooms as(Table<?> alias) {
        return new ChatRooms(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ChatRooms rename(String name) {
        return new ChatRooms(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChatRooms rename(Name name) {
        return new ChatRooms(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChatRooms rename(Table<?> name) {
        return new ChatRooms(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChatRooms where(Condition condition) {
        return new ChatRooms(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChatRooms where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChatRooms where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChatRooms where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChatRooms where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChatRooms where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChatRooms where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChatRooms where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChatRooms whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChatRooms whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
