/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.ChatRooms.ChatRoomsPath;
import io.aeyer.voidcore.jooq.tables.Users.UsersPath;
import io.aeyer.voidcore.jooq.tables.records.ChatRoomMembersRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChatRoomMembers extends TableImpl<ChatRoomMembersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.chat_room_members</code>
     */
    public static final ChatRoomMembers CHAT_ROOM_MEMBERS = new ChatRoomMembers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChatRoomMembersRecord> getRecordType() {
        return ChatRoomMembersRecord.class;
    }

    /**
     * The column <code>public.chat_room_members.room_id</code>.
     */
    public final TableField<ChatRoomMembersRecord, Long> ROOM_ID = createField(DSL.name("room_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.chat_room_members.user_id</code>.
     */
    public final TableField<ChatRoomMembersRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.chat_room_members.granted_at</code>.
     */
    public final TableField<ChatRoomMembersRecord, OffsetDateTime> GRANTED_AT = createField(DSL.name("granted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private ChatRoomMembers(Name alias, Table<ChatRoomMembersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ChatRoomMembers(Name alias, Table<ChatRoomMembersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.chat_room_members</code> table reference
     */
    public ChatRoomMembers(String alias) {
        this(DSL.name(alias), CHAT_ROOM_MEMBERS);
    }

    /**
     * Create an aliased <code>public.chat_room_members</code> table reference
     */
    public ChatRoomMembers(Name alias) {
        this(alias, CHAT_ROOM_MEMBERS);
    }

    /**
     * Create a <code>public.chat_room_members</code> table reference
     */
    public ChatRoomMembers() {
        this(DSL.name("chat_room_members"), null);
    }

    public <O extends Record> ChatRoomMembers(Table<O> path, ForeignKey<O, ChatRoomMembersRecord> childPath, InverseForeignKey<O, ChatRoomMembersRecord> parentPath) {
        super(path, childPath, parentPath, CHAT_ROOM_MEMBERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ChatRoomMembersPath extends ChatRoomMembers implements Path<ChatRoomMembersRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ChatRoomMembersPath(Table<O> path, ForeignKey<O, ChatRoomMembersRecord> childPath, InverseForeignKey<O, ChatRoomMembersRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ChatRoomMembersPath(Name alias, Table<ChatRoomMembersRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ChatRoomMembersPath as(String alias) {
            return new ChatRoomMembersPath(DSL.name(alias), this);
        }

        @Override
        public ChatRoomMembersPath as(Name alias) {
            return new ChatRoomMembersPath(alias, this);
        }

        @Override
        public ChatRoomMembersPath as(Table<?> alias) {
            return new ChatRoomMembersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ChatRoomMembersRecord> getPrimaryKey() {
        return Keys.CHAT_ROOM_MEMBERS_PKEY;
    }

    @Override
    public List<ForeignKey<ChatRoomMembersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CHAT_ROOM_MEMBERS__CHAT_ROOM_MEMBERS_ROOM_ID_FKEY, Keys.CHAT_ROOM_MEMBERS__CHAT_ROOM_MEMBERS_USER_ID_FKEY);
    }

    private transient ChatRoomsPath _chatRooms;

    /**
     * Get the implicit join path to the <code>public.chat_rooms</code> table.
     */
    public ChatRoomsPath chatRooms() {
        if (_chatRooms == null)
            _chatRooms = new ChatRoomsPath(this, Keys.CHAT_ROOM_MEMBERS__CHAT_ROOM_MEMBERS_ROOM_ID_FKEY, null);

        return _chatRooms;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.CHAT_ROOM_MEMBERS__CHAT_ROOM_MEMBERS_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public ChatRoomMembers as(String alias) {
        return new ChatRoomMembers(DSL.name(alias), this);
    }

    @Override
    public ChatRoomMembers as(Name alias) {
        return new ChatRoomMembers(alias, this);
    }

    @Override
    public ChatRoomMembers as(Table<?> alias) {
        return new ChatRoomMembers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ChatRoomMembers rename(String name) {
        return new ChatRoomMembers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChatRoomMembers rename(Name name) {
        return new ChatRoomMembers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChatRoomMembers rename(Table<?> name) {
        return new ChatRoomMembers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChatRoomMembers where(Condition condition) {
        return new ChatRoomMembers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChatRoomMembers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChatRoomMembers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChatRoomMembers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChatRoomMembers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChatRoomMembers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChatRoomMembers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChatRoomMembers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChatRoomMembers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChatRoomMembers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
