/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.records.CountersRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Counters extends TableImpl<CountersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.counters</code>
     */
    public static final Counters COUNTERS = new Counters();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CountersRecord> getRecordType() {
        return CountersRecord.class;
    }

    /**
     * The column <code>public.counters.key</code>.
     */
    public final TableField<CountersRecord, String> KEY = createField(DSL.name("key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.counters.value</code>.
     */
    public final TableField<CountersRecord, Long> VALUE = createField(DSL.name("value"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    private Counters(Name alias, Table<CountersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Counters(Name alias, Table<CountersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.counters</code> table reference
     */
    public Counters(String alias) {
        this(DSL.name(alias), COUNTERS);
    }

    /**
     * Create an aliased <code>public.counters</code> table reference
     */
    public Counters(Name alias) {
        this(alias, COUNTERS);
    }

    /**
     * Create a <code>public.counters</code> table reference
     */
    public Counters() {
        this(DSL.name("counters"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CountersRecord> getPrimaryKey() {
        return Keys.COUNTERS_PKEY;
    }

    @Override
    public Counters as(String alias) {
        return new Counters(DSL.name(alias), this);
    }

    @Override
    public Counters as(Name alias) {
        return new Counters(alias, this);
    }

    @Override
    public Counters as(Table<?> alias) {
        return new Counters(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Counters rename(String name) {
        return new Counters(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Counters rename(Name name) {
        return new Counters(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Counters rename(Table<?> name) {
        return new Counters(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Counters where(Condition condition) {
        return new Counters(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Counters where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Counters where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Counters where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Counters where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Counters where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Counters where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Counters where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Counters whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Counters whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
