/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Indexes;
import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.DocumentEditors.DocumentEditorsPath;
import io.aeyer.voidcore.jooq.tables.DocumentLinks.DocumentLinksPath;
import io.aeyer.voidcore.jooq.tables.DocumentRevisions.DocumentRevisionsPath;
import io.aeyer.voidcore.jooq.tables.Schemas.SchemasPath;
import io.aeyer.voidcore.jooq.tables.Users.UsersPath;
import io.aeyer.voidcore.jooq.tables.records.DocumentsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Documents extends TableImpl<DocumentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.documents</code>
     */
    public static final Documents DOCUMENTS = new Documents();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DocumentsRecord> getRecordType() {
        return DocumentsRecord.class;
    }

    /**
     * The column <code>public.documents.id</code>.
     */
    public final TableField<DocumentsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.documents.slug</code>.
     */
    public final TableField<DocumentsRecord, String> SLUG = createField(DSL.name("slug"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.documents.title</code>.
     */
    public final TableField<DocumentsRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.documents.type_slug</code>.
     */
    public final TableField<DocumentsRecord, String> TYPE_SLUG = createField(DSL.name("type_slug"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.documents.body</code>.
     */
    public final TableField<DocumentsRecord, String> BODY = createField(DSL.name("body"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.documents.frontmatter</code>.
     */
    public final TableField<DocumentsRecord, JSONB> FRONTMATTER = createField(DSL.name("frontmatter"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.documents.tags</code>.
     */
    public final TableField<DocumentsRecord, String[]> TAGS = createField(DSL.name("tags"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::text[]"), SQLDataType.CLOB)).array(), this, "");

    /**
     * The column <code>public.documents.author_id</code>.
     */
    public final TableField<DocumentsRecord, Long> AUTHOR_ID = createField(DSL.name("author_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.documents.visibility</code>.
     */
    public final TableField<DocumentsRecord, String> VISIBILITY = createField(DSL.name("visibility"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'public'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.documents.status</code>.
     */
    public final TableField<DocumentsRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'published'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.documents.created_at</code>.
     */
    public final TableField<DocumentsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.documents.updated_at</code>.
     */
    public final TableField<DocumentsRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<DocumentsRecord, Object> SEARCH_VECTOR = createField(DSL.name("search_vector"), DefaultDataType.getDefaultDataType("\"pg_catalog\".\"tsvector\""), this, "");

    /**
     * The column <code>public.documents.anchor_document_id</code>.
     */
    public final TableField<DocumentsRecord, UUID> ANCHOR_DOCUMENT_ID = createField(DSL.name("anchor_document_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.documents.type_version</code>.
     */
    public final TableField<DocumentsRecord, Integer> TYPE_VERSION = createField(DSL.name("type_version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.documents.rev</code>.
     */
    public final TableField<DocumentsRecord, Integer> REV = createField(DSL.name("rev"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.documents.deleted_at</code>.
     */
    public final TableField<DocumentsRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.documents.deleted_by</code>.
     */
    public final TableField<DocumentsRecord, Long> DELETED_BY = createField(DSL.name("deleted_by"), SQLDataType.BIGINT, this, "");

    private Documents(Name alias, Table<DocumentsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Documents(Name alias, Table<DocumentsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.documents</code> table reference
     */
    public Documents(String alias) {
        this(DSL.name(alias), DOCUMENTS);
    }

    /**
     * Create an aliased <code>public.documents</code> table reference
     */
    public Documents(Name alias) {
        this(alias, DOCUMENTS);
    }

    /**
     * Create a <code>public.documents</code> table reference
     */
    public Documents() {
        this(DSL.name("documents"), null);
    }

    public <O extends Record> Documents(Table<O> path, ForeignKey<O, DocumentsRecord> childPath, InverseForeignKey<O, DocumentsRecord> parentPath) {
        super(path, childPath, parentPath, DOCUMENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DocumentsPath extends Documents implements Path<DocumentsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DocumentsPath(Table<O> path, ForeignKey<O, DocumentsRecord> childPath, InverseForeignKey<O, DocumentsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DocumentsPath(Name alias, Table<DocumentsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DocumentsPath as(String alias) {
            return new DocumentsPath(DSL.name(alias), this);
        }

        @Override
        public DocumentsPath as(Name alias) {
            return new DocumentsPath(alias, this);
        }

        @Override
        public DocumentsPath as(Table<?> alias) {
            return new DocumentsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.DOCUMENTS_AUTHOR, Indexes.DOCUMENTS_DELETED, Indexes.DOCUMENTS_LIVE, Indexes.DOCUMENTS_SEARCH, Indexes.DOCUMENTS_STATUS, Indexes.DOCUMENTS_TAGS, Indexes.DOCUMENTS_TYPE_SLUG, Indexes.DOCUMENTS_UPDATED);
    }

    @Override
    public Identity<DocumentsRecord, Long> getIdentity() {
        return (Identity<DocumentsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DocumentsRecord> getPrimaryKey() {
        return Keys.DOCUMENTS_PKEY;
    }

    @Override
    public List<UniqueKey<DocumentsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.DOCUMENTS_SLUG_KEY);
    }

    @Override
    public List<ForeignKey<DocumentsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DOCUMENTS__DOCUMENTS_AUTHOR_ID_FKEY, Keys.DOCUMENTS__DOCUMENTS_DELETED_BY_FKEY, Keys.DOCUMENTS__DOCUMENTS_TYPE_FK);
    }

    private transient UsersPath _documentsAuthorIdFkey;

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>documents_author_id_fkey</code> key.
     */
    public UsersPath documentsAuthorIdFkey() {
        if (_documentsAuthorIdFkey == null)
            _documentsAuthorIdFkey = new UsersPath(this, Keys.DOCUMENTS__DOCUMENTS_AUTHOR_ID_FKEY, null);

        return _documentsAuthorIdFkey;
    }

    private transient UsersPath _documentsDeletedByFkey;

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>documents_deleted_by_fkey</code> key.
     */
    public UsersPath documentsDeletedByFkey() {
        if (_documentsDeletedByFkey == null)
            _documentsDeletedByFkey = new UsersPath(this, Keys.DOCUMENTS__DOCUMENTS_DELETED_BY_FKEY, null);

        return _documentsDeletedByFkey;
    }

    private transient SchemasPath _schemas;

    /**
     * Get the implicit join path to the <code>public.schemas</code> table.
     */
    public SchemasPath schemas() {
        if (_schemas == null)
            _schemas = new SchemasPath(this, Keys.DOCUMENTS__DOCUMENTS_TYPE_FK, null);

        return _schemas;
    }

    private transient DocumentEditorsPath _documentEditors;

    /**
     * Get the implicit to-many join path to the
     * <code>public.document_editors</code> table
     */
    public DocumentEditorsPath documentEditors() {
        if (_documentEditors == null)
            _documentEditors = new DocumentEditorsPath(this, null, Keys.DOCUMENT_EDITORS__DOCUMENT_EDITORS_DOCUMENT_ID_FKEY.getInverseKey());

        return _documentEditors;
    }

    private transient DocumentLinksPath _documentLinksSourceIdFkey;

    /**
     * Get the implicit to-many join path to the
     * <code>public.document_links</code> table, via the
     * <code>document_links_source_id_fkey</code> key
     */
    public DocumentLinksPath documentLinksSourceIdFkey() {
        if (_documentLinksSourceIdFkey == null)
            _documentLinksSourceIdFkey = new DocumentLinksPath(this, null, Keys.DOCUMENT_LINKS__DOCUMENT_LINKS_SOURCE_ID_FKEY.getInverseKey());

        return _documentLinksSourceIdFkey;
    }

    private transient DocumentLinksPath _documentLinksTargetIdFkey;

    /**
     * Get the implicit to-many join path to the
     * <code>public.document_links</code> table, via the
     * <code>document_links_target_id_fkey</code> key
     */
    public DocumentLinksPath documentLinksTargetIdFkey() {
        if (_documentLinksTargetIdFkey == null)
            _documentLinksTargetIdFkey = new DocumentLinksPath(this, null, Keys.DOCUMENT_LINKS__DOCUMENT_LINKS_TARGET_ID_FKEY.getInverseKey());

        return _documentLinksTargetIdFkey;
    }

    private transient DocumentRevisionsPath _documentRevisions;

    /**
     * Get the implicit to-many join path to the
     * <code>public.document_revisions</code> table
     */
    public DocumentRevisionsPath documentRevisions() {
        if (_documentRevisions == null)
            _documentRevisions = new DocumentRevisionsPath(this, null, Keys.DOCUMENT_REVISIONS__DOCUMENT_REVISIONS_DOCUMENT_ID_FKEY.getInverseKey());

        return _documentRevisions;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.users</code>
     * table
     */
    public UsersPath users() {
        return documentEditors().users();
    }

    @Override
    public List<Check<DocumentsRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("documents_rev_check"), "((rev >= 1))", true),
            Internal.createCheck(this, DSL.name("documents_status_check"), "((status = ANY (ARRAY['draft'::text, 'pending'::text, 'published'::text])))", true),
            Internal.createCheck(this, DSL.name("documents_type_version_check"), "((type_version >= 1))", true),
            Internal.createCheck(this, DSL.name("documents_visibility_check"), "((visibility = ANY (ARRAY['public'::text, 'private'::text])))", true)
        );
    }

    @Override
    public Documents as(String alias) {
        return new Documents(DSL.name(alias), this);
    }

    @Override
    public Documents as(Name alias) {
        return new Documents(alias, this);
    }

    @Override
    public Documents as(Table<?> alias) {
        return new Documents(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Documents rename(String name) {
        return new Documents(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Documents rename(Name name) {
        return new Documents(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Documents rename(Table<?> name) {
        return new Documents(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Documents where(Condition condition) {
        return new Documents(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Documents where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Documents where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Documents where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Documents where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Documents where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Documents where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Documents where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Documents whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Documents whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
