/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.Documents.DocumentsPath;
import io.aeyer.voidcore.jooq.tables.Users.UsersPath;
import io.aeyer.voidcore.jooq.tables.records.DocumentEditorsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DocumentEditors extends TableImpl<DocumentEditorsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.document_editors</code>
     */
    public static final DocumentEditors DOCUMENT_EDITORS = new DocumentEditors();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DocumentEditorsRecord> getRecordType() {
        return DocumentEditorsRecord.class;
    }

    /**
     * The column <code>public.document_editors.document_id</code>.
     */
    public final TableField<DocumentEditorsRecord, Long> DOCUMENT_ID = createField(DSL.name("document_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.document_editors.user_id</code>.
     */
    public final TableField<DocumentEditorsRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private DocumentEditors(Name alias, Table<DocumentEditorsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DocumentEditors(Name alias, Table<DocumentEditorsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.document_editors</code> table reference
     */
    public DocumentEditors(String alias) {
        this(DSL.name(alias), DOCUMENT_EDITORS);
    }

    /**
     * Create an aliased <code>public.document_editors</code> table reference
     */
    public DocumentEditors(Name alias) {
        this(alias, DOCUMENT_EDITORS);
    }

    /**
     * Create a <code>public.document_editors</code> table reference
     */
    public DocumentEditors() {
        this(DSL.name("document_editors"), null);
    }

    public <O extends Record> DocumentEditors(Table<O> path, ForeignKey<O, DocumentEditorsRecord> childPath, InverseForeignKey<O, DocumentEditorsRecord> parentPath) {
        super(path, childPath, parentPath, DOCUMENT_EDITORS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DocumentEditorsPath extends DocumentEditors implements Path<DocumentEditorsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DocumentEditorsPath(Table<O> path, ForeignKey<O, DocumentEditorsRecord> childPath, InverseForeignKey<O, DocumentEditorsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DocumentEditorsPath(Name alias, Table<DocumentEditorsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DocumentEditorsPath as(String alias) {
            return new DocumentEditorsPath(DSL.name(alias), this);
        }

        @Override
        public DocumentEditorsPath as(Name alias) {
            return new DocumentEditorsPath(alias, this);
        }

        @Override
        public DocumentEditorsPath as(Table<?> alias) {
            return new DocumentEditorsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<DocumentEditorsRecord> getPrimaryKey() {
        return Keys.DOCUMENT_EDITORS_PKEY;
    }

    @Override
    public List<ForeignKey<DocumentEditorsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DOCUMENT_EDITORS__DOCUMENT_EDITORS_DOCUMENT_ID_FKEY, Keys.DOCUMENT_EDITORS__DOCUMENT_EDITORS_USER_ID_FKEY);
    }

    private transient DocumentsPath _documents;

    /**
     * Get the implicit join path to the <code>public.documents</code> table.
     */
    public DocumentsPath documents() {
        if (_documents == null)
            _documents = new DocumentsPath(this, Keys.DOCUMENT_EDITORS__DOCUMENT_EDITORS_DOCUMENT_ID_FKEY, null);

        return _documents;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.DOCUMENT_EDITORS__DOCUMENT_EDITORS_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public DocumentEditors as(String alias) {
        return new DocumentEditors(DSL.name(alias), this);
    }

    @Override
    public DocumentEditors as(Name alias) {
        return new DocumentEditors(alias, this);
    }

    @Override
    public DocumentEditors as(Table<?> alias) {
        return new DocumentEditors(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DocumentEditors rename(String name) {
        return new DocumentEditors(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DocumentEditors rename(Name name) {
        return new DocumentEditors(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DocumentEditors rename(Table<?> name) {
        return new DocumentEditors(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DocumentEditors where(Condition condition) {
        return new DocumentEditors(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DocumentEditors where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DocumentEditors where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DocumentEditors where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DocumentEditors where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DocumentEditors where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DocumentEditors where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DocumentEditors where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DocumentEditors whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DocumentEditors whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
