/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Indexes;
import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.Documents.DocumentsPath;
import io.aeyer.voidcore.jooq.tables.records.DocumentLinksRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DocumentLinks extends TableImpl<DocumentLinksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.document_links</code>
     */
    public static final DocumentLinks DOCUMENT_LINKS = new DocumentLinks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DocumentLinksRecord> getRecordType() {
        return DocumentLinksRecord.class;
    }

    /**
     * The column <code>public.document_links.source_id</code>.
     */
    public final TableField<DocumentLinksRecord, Long> SOURCE_ID = createField(DSL.name("source_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.document_links.target_id</code>.
     */
    public final TableField<DocumentLinksRecord, Long> TARGET_ID = createField(DSL.name("target_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.document_links.kind</code>.
     */
    public final TableField<DocumentLinksRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'reference'::text"), SQLDataType.CLOB)), this, "");

    private DocumentLinks(Name alias, Table<DocumentLinksRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DocumentLinks(Name alias, Table<DocumentLinksRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.document_links</code> table reference
     */
    public DocumentLinks(String alias) {
        this(DSL.name(alias), DOCUMENT_LINKS);
    }

    /**
     * Create an aliased <code>public.document_links</code> table reference
     */
    public DocumentLinks(Name alias) {
        this(alias, DOCUMENT_LINKS);
    }

    /**
     * Create a <code>public.document_links</code> table reference
     */
    public DocumentLinks() {
        this(DSL.name("document_links"), null);
    }

    public <O extends Record> DocumentLinks(Table<O> path, ForeignKey<O, DocumentLinksRecord> childPath, InverseForeignKey<O, DocumentLinksRecord> parentPath) {
        super(path, childPath, parentPath, DOCUMENT_LINKS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DocumentLinksPath extends DocumentLinks implements Path<DocumentLinksRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DocumentLinksPath(Table<O> path, ForeignKey<O, DocumentLinksRecord> childPath, InverseForeignKey<O, DocumentLinksRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DocumentLinksPath(Name alias, Table<DocumentLinksRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DocumentLinksPath as(String alias) {
            return new DocumentLinksPath(DSL.name(alias), this);
        }

        @Override
        public DocumentLinksPath as(Name alias) {
            return new DocumentLinksPath(alias, this);
        }

        @Override
        public DocumentLinksPath as(Table<?> alias) {
            return new DocumentLinksPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.DOCUMENT_LINKS_TARGET);
    }

    @Override
    public UniqueKey<DocumentLinksRecord> getPrimaryKey() {
        return Keys.DOCUMENT_LINKS_PKEY;
    }

    @Override
    public List<ForeignKey<DocumentLinksRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DOCUMENT_LINKS__DOCUMENT_LINKS_SOURCE_ID_FKEY, Keys.DOCUMENT_LINKS__DOCUMENT_LINKS_TARGET_ID_FKEY);
    }

    private transient DocumentsPath _documentLinksSourceIdFkey;

    /**
     * Get the implicit join path to the <code>public.documents</code> table,
     * via the <code>document_links_source_id_fkey</code> key.
     */
    public DocumentsPath documentLinksSourceIdFkey() {
        if (_documentLinksSourceIdFkey == null)
            _documentLinksSourceIdFkey = new DocumentsPath(this, Keys.DOCUMENT_LINKS__DOCUMENT_LINKS_SOURCE_ID_FKEY, null);

        return _documentLinksSourceIdFkey;
    }

    private transient DocumentsPath _documentLinksTargetIdFkey;

    /**
     * Get the implicit join path to the <code>public.documents</code> table,
     * via the <code>document_links_target_id_fkey</code> key.
     */
    public DocumentsPath documentLinksTargetIdFkey() {
        if (_documentLinksTargetIdFkey == null)
            _documentLinksTargetIdFkey = new DocumentsPath(this, Keys.DOCUMENT_LINKS__DOCUMENT_LINKS_TARGET_ID_FKEY, null);

        return _documentLinksTargetIdFkey;
    }

    @Override
    public DocumentLinks as(String alias) {
        return new DocumentLinks(DSL.name(alias), this);
    }

    @Override
    public DocumentLinks as(Name alias) {
        return new DocumentLinks(alias, this);
    }

    @Override
    public DocumentLinks as(Table<?> alias) {
        return new DocumentLinks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DocumentLinks rename(String name) {
        return new DocumentLinks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DocumentLinks rename(Name name) {
        return new DocumentLinks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DocumentLinks rename(Table<?> name) {
        return new DocumentLinks(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DocumentLinks where(Condition condition) {
        return new DocumentLinks(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DocumentLinks where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DocumentLinks where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DocumentLinks where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DocumentLinks where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DocumentLinks where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DocumentLinks where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DocumentLinks where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DocumentLinks whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DocumentLinks whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
