/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Indexes;
import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.records.DoorStateRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DoorState extends TableImpl<DoorStateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.door_state</code>
     */
    public static final DoorState DOOR_STATE = new DoorState();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DoorStateRecord> getRecordType() {
        return DoorStateRecord.class;
    }

    /**
     * The column <code>public.door_state.door_id</code>.
     */
    public final TableField<DoorStateRecord, String> DOOR_ID = createField(DSL.name("door_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.door_state.scope</code>.
     */
    public final TableField<DoorStateRecord, String> SCOPE = createField(DSL.name("scope"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.door_state.scope_key</code>.
     */
    public final TableField<DoorStateRecord, String> SCOPE_KEY = createField(DSL.name("scope_key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.door_state.key</code>.
     */
    public final TableField<DoorStateRecord, String> KEY = createField(DSL.name("key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.door_state.value</code>.
     */
    public final TableField<DoorStateRecord, JSONB> VALUE = createField(DSL.name("value"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.door_state.version</code>.
     */
    public final TableField<DoorStateRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.door_state.updated_at</code>.
     */
    public final TableField<DoorStateRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private DoorState(Name alias, Table<DoorStateRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DoorState(Name alias, Table<DoorStateRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.door_state</code> table reference
     */
    public DoorState(String alias) {
        this(DSL.name(alias), DOOR_STATE);
    }

    /**
     * Create an aliased <code>public.door_state</code> table reference
     */
    public DoorState(Name alias) {
        this(alias, DOOR_STATE);
    }

    /**
     * Create a <code>public.door_state</code> table reference
     */
    public DoorState() {
        this(DSL.name("door_state"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.DOOR_STATE_SCAN);
    }

    @Override
    public UniqueKey<DoorStateRecord> getPrimaryKey() {
        return Keys.DOOR_STATE_PKEY;
    }

    @Override
    public List<Check<DoorStateRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("door_state_scope_check"), "((scope = ANY (ARRAY['user'::text, 'shared'::text, 'global'::text])))", true)
        );
    }

    @Override
    public DoorState as(String alias) {
        return new DoorState(DSL.name(alias), this);
    }

    @Override
    public DoorState as(Name alias) {
        return new DoorState(alias, this);
    }

    @Override
    public DoorState as(Table<?> alias) {
        return new DoorState(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DoorState rename(String name) {
        return new DoorState(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DoorState rename(Name name) {
        return new DoorState(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DoorState rename(Table<?> name) {
        return new DoorState(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DoorState where(Condition condition) {
        return new DoorState(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DoorState where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DoorState where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DoorState where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DoorState where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DoorState where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DoorState where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DoorState where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DoorState whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DoorState whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
