/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.records.FortunesRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Fortunes extends TableImpl<FortunesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.fortunes</code>
     */
    public static final Fortunes FORTUNES = new Fortunes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FortunesRecord> getRecordType() {
        return FortunesRecord.class;
    }

    /**
     * The column <code>public.fortunes.id</code>.
     */
    public final TableField<FortunesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.fortunes.text</code>.
     */
    public final TableField<FortunesRecord, String> TEXT = createField(DSL.name("text"), SQLDataType.CLOB.nullable(false), this, "");

    private Fortunes(Name alias, Table<FortunesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Fortunes(Name alias, Table<FortunesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.fortunes</code> table reference
     */
    public Fortunes(String alias) {
        this(DSL.name(alias), FORTUNES);
    }

    /**
     * Create an aliased <code>public.fortunes</code> table reference
     */
    public Fortunes(Name alias) {
        this(alias, FORTUNES);
    }

    /**
     * Create a <code>public.fortunes</code> table reference
     */
    public Fortunes() {
        this(DSL.name("fortunes"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<FortunesRecord, Long> getIdentity() {
        return (Identity<FortunesRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FortunesRecord> getPrimaryKey() {
        return Keys.FORTUNES_PKEY;
    }

    @Override
    public Fortunes as(String alias) {
        return new Fortunes(DSL.name(alias), this);
    }

    @Override
    public Fortunes as(Name alias) {
        return new Fortunes(alias, this);
    }

    @Override
    public Fortunes as(Table<?> alias) {
        return new Fortunes(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Fortunes rename(String name) {
        return new Fortunes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Fortunes rename(Name name) {
        return new Fortunes(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Fortunes rename(Table<?> name) {
        return new Fortunes(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fortunes where(Condition condition) {
        return new Fortunes(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fortunes where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fortunes where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fortunes where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Fortunes where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Fortunes where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Fortunes where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Fortunes where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fortunes whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fortunes whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
