/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Indexes;
import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.Users.UsersPath;
import io.aeyer.voidcore.jooq.tables.records.LastCallersRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LastCallers extends TableImpl<LastCallersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.last_callers</code>
     */
    public static final LastCallers LAST_CALLERS = new LastCallers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LastCallersRecord> getRecordType() {
        return LastCallersRecord.class;
    }

    /**
     * The column <code>public.last_callers.id</code>.
     */
    public final TableField<LastCallersRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.last_callers.user_id</code>.
     */
    public final TableField<LastCallersRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.last_callers.at</code>.
     */
    public final TableField<LastCallersRecord, OffsetDateTime> AT = createField(DSL.name("at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private LastCallers(Name alias, Table<LastCallersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LastCallers(Name alias, Table<LastCallersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.last_callers</code> table reference
     */
    public LastCallers(String alias) {
        this(DSL.name(alias), LAST_CALLERS);
    }

    /**
     * Create an aliased <code>public.last_callers</code> table reference
     */
    public LastCallers(Name alias) {
        this(alias, LAST_CALLERS);
    }

    /**
     * Create a <code>public.last_callers</code> table reference
     */
    public LastCallers() {
        this(DSL.name("last_callers"), null);
    }

    public <O extends Record> LastCallers(Table<O> path, ForeignKey<O, LastCallersRecord> childPath, InverseForeignKey<O, LastCallersRecord> parentPath) {
        super(path, childPath, parentPath, LAST_CALLERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LastCallersPath extends LastCallers implements Path<LastCallersRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> LastCallersPath(Table<O> path, ForeignKey<O, LastCallersRecord> childPath, InverseForeignKey<O, LastCallersRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LastCallersPath(Name alias, Table<LastCallersRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LastCallersPath as(String alias) {
            return new LastCallersPath(DSL.name(alias), this);
        }

        @Override
        public LastCallersPath as(Name alias) {
            return new LastCallersPath(alias, this);
        }

        @Override
        public LastCallersPath as(Table<?> alias) {
            return new LastCallersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_LASTCALLERS_AT);
    }

    @Override
    public Identity<LastCallersRecord, Long> getIdentity() {
        return (Identity<LastCallersRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<LastCallersRecord> getPrimaryKey() {
        return Keys.LAST_CALLERS_PKEY;
    }

    @Override
    public List<ForeignKey<LastCallersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.LAST_CALLERS__LAST_CALLERS_USER_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.LAST_CALLERS__LAST_CALLERS_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public LastCallers as(String alias) {
        return new LastCallers(DSL.name(alias), this);
    }

    @Override
    public LastCallers as(Name alias) {
        return new LastCallers(alias, this);
    }

    @Override
    public LastCallers as(Table<?> alias) {
        return new LastCallers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LastCallers rename(String name) {
        return new LastCallers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LastCallers rename(Name name) {
        return new LastCallers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LastCallers rename(Table<?> name) {
        return new LastCallers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LastCallers where(Condition condition) {
        return new LastCallers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LastCallers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LastCallers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LastCallers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LastCallers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LastCallers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LastCallers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LastCallers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LastCallers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LastCallers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
