/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Indexes;
import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.records.LoginAttemptsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LoginAttempts extends TableImpl<LoginAttemptsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.login_attempts</code>
     */
    public static final LoginAttempts LOGIN_ATTEMPTS = new LoginAttempts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LoginAttemptsRecord> getRecordType() {
        return LoginAttemptsRecord.class;
    }

    /**
     * The column <code>public.login_attempts.id</code>.
     */
    public final TableField<LoginAttemptsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.login_attempts.ip</code>.
     */
    public final TableField<LoginAttemptsRecord, String> IP = createField(DSL.name("ip"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.login_attempts.handle</code>.
     */
    public final TableField<LoginAttemptsRecord, String> HANDLE = createField(DSL.name("handle"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.login_attempts.success</code>.
     */
    public final TableField<LoginAttemptsRecord, Boolean> SUCCESS = createField(DSL.name("success"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.login_attempts.at</code>.
     */
    public final TableField<LoginAttemptsRecord, OffsetDateTime> AT = createField(DSL.name("at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private LoginAttempts(Name alias, Table<LoginAttemptsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LoginAttempts(Name alias, Table<LoginAttemptsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.login_attempts</code> table reference
     */
    public LoginAttempts(String alias) {
        this(DSL.name(alias), LOGIN_ATTEMPTS);
    }

    /**
     * Create an aliased <code>public.login_attempts</code> table reference
     */
    public LoginAttempts(Name alias) {
        this(alias, LOGIN_ATTEMPTS);
    }

    /**
     * Create a <code>public.login_attempts</code> table reference
     */
    public LoginAttempts() {
        this(DSL.name("login_attempts"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_LOGATTEMPTS_IP_AT);
    }

    @Override
    public Identity<LoginAttemptsRecord, Long> getIdentity() {
        return (Identity<LoginAttemptsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<LoginAttemptsRecord> getPrimaryKey() {
        return Keys.LOGIN_ATTEMPTS_PKEY;
    }

    @Override
    public LoginAttempts as(String alias) {
        return new LoginAttempts(DSL.name(alias), this);
    }

    @Override
    public LoginAttempts as(Name alias) {
        return new LoginAttempts(alias, this);
    }

    @Override
    public LoginAttempts as(Table<?> alias) {
        return new LoginAttempts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LoginAttempts rename(String name) {
        return new LoginAttempts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LoginAttempts rename(Name name) {
        return new LoginAttempts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LoginAttempts rename(Table<?> name) {
        return new LoginAttempts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoginAttempts where(Condition condition) {
        return new LoginAttempts(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoginAttempts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoginAttempts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoginAttempts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LoginAttempts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LoginAttempts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LoginAttempts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LoginAttempts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoginAttempts whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LoginAttempts whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
