/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Indexes;
import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.Users.UsersPath;
import io.aeyer.voidcore.jooq.tables.records.OnelinersRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Oneliners extends TableImpl<OnelinersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.oneliners</code>
     */
    public static final Oneliners ONELINERS = new Oneliners();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OnelinersRecord> getRecordType() {
        return OnelinersRecord.class;
    }

    /**
     * The column <code>public.oneliners.id</code>.
     */
    public final TableField<OnelinersRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.oneliners.author_id</code>.
     */
    public final TableField<OnelinersRecord, Long> AUTHOR_ID = createField(DSL.name("author_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.oneliners.body</code>.
     */
    public final TableField<OnelinersRecord, String> BODY = createField(DSL.name("body"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.oneliners.posted_at</code>.
     */
    public final TableField<OnelinersRecord, OffsetDateTime> POSTED_AT = createField(DSL.name("posted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Oneliners(Name alias, Table<OnelinersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Oneliners(Name alias, Table<OnelinersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.oneliners</code> table reference
     */
    public Oneliners(String alias) {
        this(DSL.name(alias), ONELINERS);
    }

    /**
     * Create an aliased <code>public.oneliners</code> table reference
     */
    public Oneliners(Name alias) {
        this(alias, ONELINERS);
    }

    /**
     * Create a <code>public.oneliners</code> table reference
     */
    public Oneliners() {
        this(DSL.name("oneliners"), null);
    }

    public <O extends Record> Oneliners(Table<O> path, ForeignKey<O, OnelinersRecord> childPath, InverseForeignKey<O, OnelinersRecord> parentPath) {
        super(path, childPath, parentPath, ONELINERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OnelinersPath extends Oneliners implements Path<OnelinersRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OnelinersPath(Table<O> path, ForeignKey<O, OnelinersRecord> childPath, InverseForeignKey<O, OnelinersRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OnelinersPath(Name alias, Table<OnelinersRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OnelinersPath as(String alias) {
            return new OnelinersPath(DSL.name(alias), this);
        }

        @Override
        public OnelinersPath as(Name alias) {
            return new OnelinersPath(alias, this);
        }

        @Override
        public OnelinersPath as(Table<?> alias) {
            return new OnelinersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_ONELINERS_POSTED);
    }

    @Override
    public Identity<OnelinersRecord, Long> getIdentity() {
        return (Identity<OnelinersRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<OnelinersRecord> getPrimaryKey() {
        return Keys.ONELINERS_PKEY;
    }

    @Override
    public List<ForeignKey<OnelinersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ONELINERS__ONELINERS_AUTHOR_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.ONELINERS__ONELINERS_AUTHOR_ID_FKEY, null);

        return _users;
    }

    @Override
    public List<Check<OnelinersRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("oneliners_body_check"), "((length(body) <= 70))", true)
        );
    }

    @Override
    public Oneliners as(String alias) {
        return new Oneliners(DSL.name(alias), this);
    }

    @Override
    public Oneliners as(Name alias) {
        return new Oneliners(alias, this);
    }

    @Override
    public Oneliners as(Table<?> alias) {
        return new Oneliners(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Oneliners rename(String name) {
        return new Oneliners(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Oneliners rename(Name name) {
        return new Oneliners(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Oneliners rename(Table<?> name) {
        return new Oneliners(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Oneliners where(Condition condition) {
        return new Oneliners(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Oneliners where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Oneliners where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Oneliners where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Oneliners where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Oneliners where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Oneliners where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Oneliners where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Oneliners whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Oneliners whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
