/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Indexes;
import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.Users.UsersPath;
import io.aeyer.voidcore.jooq.tables.records.PendingContentRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PendingContent extends TableImpl<PendingContentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.pending_content</code>
     */
    public static final PendingContent PENDING_CONTENT = new PendingContent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PendingContentRecord> getRecordType() {
        return PendingContentRecord.class;
    }

    /**
     * The column <code>public.pending_content.id</code>.
     */
    public final TableField<PendingContentRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.pending_content.kind</code>.
     */
    public final TableField<PendingContentRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.pending_content.author_id</code>.
     */
    public final TableField<PendingContentRecord, Long> AUTHOR_ID = createField(DSL.name("author_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.pending_content.payload</code>.
     */
    public final TableField<PendingContentRecord, JSONB> PAYLOAD = createField(DSL.name("payload"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.pending_content.submitted_at</code>.
     */
    public final TableField<PendingContentRecord, OffsetDateTime> SUBMITTED_AT = createField(DSL.name("submitted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.pending_content.decided_by</code>.
     */
    public final TableField<PendingContentRecord, Long> DECIDED_BY = createField(DSL.name("decided_by"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.pending_content.decided_at</code>.
     */
    public final TableField<PendingContentRecord, OffsetDateTime> DECIDED_AT = createField(DSL.name("decided_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.pending_content.decision</code>.
     */
    public final TableField<PendingContentRecord, String> DECISION = createField(DSL.name("decision"), SQLDataType.CLOB, this, "");

    private PendingContent(Name alias, Table<PendingContentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PendingContent(Name alias, Table<PendingContentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.pending_content</code> table reference
     */
    public PendingContent(String alias) {
        this(DSL.name(alias), PENDING_CONTENT);
    }

    /**
     * Create an aliased <code>public.pending_content</code> table reference
     */
    public PendingContent(Name alias) {
        this(alias, PENDING_CONTENT);
    }

    /**
     * Create a <code>public.pending_content</code> table reference
     */
    public PendingContent() {
        this(DSL.name("pending_content"), null);
    }

    public <O extends Record> PendingContent(Table<O> path, ForeignKey<O, PendingContentRecord> childPath, InverseForeignKey<O, PendingContentRecord> parentPath) {
        super(path, childPath, parentPath, PENDING_CONTENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PendingContentPath extends PendingContent implements Path<PendingContentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PendingContentPath(Table<O> path, ForeignKey<O, PendingContentRecord> childPath, InverseForeignKey<O, PendingContentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PendingContentPath(Name alias, Table<PendingContentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PendingContentPath as(String alias) {
            return new PendingContentPath(DSL.name(alias), this);
        }

        @Override
        public PendingContentPath as(Name alias) {
            return new PendingContentPath(alias, this);
        }

        @Override
        public PendingContentPath as(Table<?> alias) {
            return new PendingContentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PENDING_CONTENT_PENDING);
    }

    @Override
    public Identity<PendingContentRecord, Long> getIdentity() {
        return (Identity<PendingContentRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PendingContentRecord> getPrimaryKey() {
        return Keys.PENDING_CONTENT_PKEY;
    }

    @Override
    public List<ForeignKey<PendingContentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PENDING_CONTENT__PENDING_CONTENT_AUTHOR_ID_FKEY, Keys.PENDING_CONTENT__PENDING_CONTENT_DECIDED_BY_FKEY);
    }

    private transient UsersPath _pendingContentAuthorIdFkey;

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>pending_content_author_id_fkey</code> key.
     */
    public UsersPath pendingContentAuthorIdFkey() {
        if (_pendingContentAuthorIdFkey == null)
            _pendingContentAuthorIdFkey = new UsersPath(this, Keys.PENDING_CONTENT__PENDING_CONTENT_AUTHOR_ID_FKEY, null);

        return _pendingContentAuthorIdFkey;
    }

    private transient UsersPath _pendingContentDecidedByFkey;

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>pending_content_decided_by_fkey</code> key.
     */
    public UsersPath pendingContentDecidedByFkey() {
        if (_pendingContentDecidedByFkey == null)
            _pendingContentDecidedByFkey = new UsersPath(this, Keys.PENDING_CONTENT__PENDING_CONTENT_DECIDED_BY_FKEY, null);

        return _pendingContentDecidedByFkey;
    }

    @Override
    public PendingContent as(String alias) {
        return new PendingContent(DSL.name(alias), this);
    }

    @Override
    public PendingContent as(Name alias) {
        return new PendingContent(alias, this);
    }

    @Override
    public PendingContent as(Table<?> alias) {
        return new PendingContent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PendingContent rename(String name) {
        return new PendingContent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PendingContent rename(Name name) {
        return new PendingContent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PendingContent rename(Table<?> name) {
        return new PendingContent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingContent where(Condition condition) {
        return new PendingContent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingContent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingContent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingContent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingContent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingContent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingContent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingContent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingContent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingContent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
