/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Indexes;
import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.PollOptions.PollOptionsPath;
import io.aeyer.voidcore.jooq.tables.Polls.PollsPath;
import io.aeyer.voidcore.jooq.tables.Users.UsersPath;
import io.aeyer.voidcore.jooq.tables.records.PollVotesRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PollVotes extends TableImpl<PollVotesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.poll_votes</code>
     */
    public static final PollVotes POLL_VOTES = new PollVotes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PollVotesRecord> getRecordType() {
        return PollVotesRecord.class;
    }

    /**
     * The column <code>public.poll_votes.poll_id</code>.
     */
    public final TableField<PollVotesRecord, Long> POLL_ID = createField(DSL.name("poll_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.poll_votes.option_id</code>.
     */
    public final TableField<PollVotesRecord, Long> OPTION_ID = createField(DSL.name("option_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.poll_votes.user_id</code>.
     */
    public final TableField<PollVotesRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.poll_votes.voted_at</code>.
     */
    public final TableField<PollVotesRecord, OffsetDateTime> VOTED_AT = createField(DSL.name("voted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private PollVotes(Name alias, Table<PollVotesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PollVotes(Name alias, Table<PollVotesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.poll_votes</code> table reference
     */
    public PollVotes(String alias) {
        this(DSL.name(alias), POLL_VOTES);
    }

    /**
     * Create an aliased <code>public.poll_votes</code> table reference
     */
    public PollVotes(Name alias) {
        this(alias, POLL_VOTES);
    }

    /**
     * Create a <code>public.poll_votes</code> table reference
     */
    public PollVotes() {
        this(DSL.name("poll_votes"), null);
    }

    public <O extends Record> PollVotes(Table<O> path, ForeignKey<O, PollVotesRecord> childPath, InverseForeignKey<O, PollVotesRecord> parentPath) {
        super(path, childPath, parentPath, POLL_VOTES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PollVotesPath extends PollVotes implements Path<PollVotesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PollVotesPath(Table<O> path, ForeignKey<O, PollVotesRecord> childPath, InverseForeignKey<O, PollVotesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PollVotesPath(Name alias, Table<PollVotesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PollVotesPath as(String alias) {
            return new PollVotesPath(DSL.name(alias), this);
        }

        @Override
        public PollVotesPath as(Name alias) {
            return new PollVotesPath(alias, this);
        }

        @Override
        public PollVotesPath as(Table<?> alias) {
            return new PollVotesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_POLL_VOTES_OPTION);
    }

    @Override
    public UniqueKey<PollVotesRecord> getPrimaryKey() {
        return Keys.POLL_VOTES_PKEY;
    }

    @Override
    public List<ForeignKey<PollVotesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.POLL_VOTES__POLL_VOTES_OPTION_ID_FKEY, Keys.POLL_VOTES__POLL_VOTES_POLL_ID_FKEY, Keys.POLL_VOTES__POLL_VOTES_USER_ID_FKEY);
    }

    private transient PollOptionsPath _pollOptions;

    /**
     * Get the implicit join path to the <code>public.poll_options</code> table.
     */
    public PollOptionsPath pollOptions() {
        if (_pollOptions == null)
            _pollOptions = new PollOptionsPath(this, Keys.POLL_VOTES__POLL_VOTES_OPTION_ID_FKEY, null);

        return _pollOptions;
    }

    private transient PollsPath _polls;

    /**
     * Get the implicit join path to the <code>public.polls</code> table.
     */
    public PollsPath polls() {
        if (_polls == null)
            _polls = new PollsPath(this, Keys.POLL_VOTES__POLL_VOTES_POLL_ID_FKEY, null);

        return _polls;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.POLL_VOTES__POLL_VOTES_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public PollVotes as(String alias) {
        return new PollVotes(DSL.name(alias), this);
    }

    @Override
    public PollVotes as(Name alias) {
        return new PollVotes(alias, this);
    }

    @Override
    public PollVotes as(Table<?> alias) {
        return new PollVotes(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PollVotes rename(String name) {
        return new PollVotes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PollVotes rename(Name name) {
        return new PollVotes(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PollVotes rename(Table<?> name) {
        return new PollVotes(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PollVotes where(Condition condition) {
        return new PollVotes(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PollVotes where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PollVotes where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PollVotes where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PollVotes where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PollVotes where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PollVotes where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PollVotes where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PollVotes whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PollVotes whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
