/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Indexes;
import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.PollVotes.PollVotesPath;
import io.aeyer.voidcore.jooq.tables.Polls.PollsPath;
import io.aeyer.voidcore.jooq.tables.records.PollOptionsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PollOptions extends TableImpl<PollOptionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.poll_options</code>
     */
    public static final PollOptions POLL_OPTIONS = new PollOptions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PollOptionsRecord> getRecordType() {
        return PollOptionsRecord.class;
    }

    /**
     * The column <code>public.poll_options.id</code>.
     */
    public final TableField<PollOptionsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.poll_options.poll_id</code>.
     */
    public final TableField<PollOptionsRecord, Long> POLL_ID = createField(DSL.name("poll_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.poll_options.text</code>.
     */
    public final TableField<PollOptionsRecord, String> TEXT = createField(DSL.name("text"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.poll_options.position</code>.
     */
    public final TableField<PollOptionsRecord, Integer> POSITION = createField(DSL.name("position"), SQLDataType.INTEGER.nullable(false), this, "");

    private PollOptions(Name alias, Table<PollOptionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PollOptions(Name alias, Table<PollOptionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.poll_options</code> table reference
     */
    public PollOptions(String alias) {
        this(DSL.name(alias), POLL_OPTIONS);
    }

    /**
     * Create an aliased <code>public.poll_options</code> table reference
     */
    public PollOptions(Name alias) {
        this(alias, POLL_OPTIONS);
    }

    /**
     * Create a <code>public.poll_options</code> table reference
     */
    public PollOptions() {
        this(DSL.name("poll_options"), null);
    }

    public <O extends Record> PollOptions(Table<O> path, ForeignKey<O, PollOptionsRecord> childPath, InverseForeignKey<O, PollOptionsRecord> parentPath) {
        super(path, childPath, parentPath, POLL_OPTIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PollOptionsPath extends PollOptions implements Path<PollOptionsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PollOptionsPath(Table<O> path, ForeignKey<O, PollOptionsRecord> childPath, InverseForeignKey<O, PollOptionsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PollOptionsPath(Name alias, Table<PollOptionsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PollOptionsPath as(String alias) {
            return new PollOptionsPath(DSL.name(alias), this);
        }

        @Override
        public PollOptionsPath as(Name alias) {
            return new PollOptionsPath(alias, this);
        }

        @Override
        public PollOptionsPath as(Table<?> alias) {
            return new PollOptionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_POLL_OPTIONS_POLL);
    }

    @Override
    public Identity<PollOptionsRecord, Long> getIdentity() {
        return (Identity<PollOptionsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PollOptionsRecord> getPrimaryKey() {
        return Keys.POLL_OPTIONS_PKEY;
    }

    @Override
    public List<UniqueKey<PollOptionsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.POLL_OPTIONS_POLL_ID_POSITION_KEY);
    }

    @Override
    public List<ForeignKey<PollOptionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.POLL_OPTIONS__POLL_OPTIONS_POLL_ID_FKEY);
    }

    private transient PollsPath _polls;

    /**
     * Get the implicit join path to the <code>public.polls</code> table.
     */
    public PollsPath polls() {
        if (_polls == null)
            _polls = new PollsPath(this, Keys.POLL_OPTIONS__POLL_OPTIONS_POLL_ID_FKEY, null);

        return _polls;
    }

    private transient PollVotesPath _pollVotes;

    /**
     * Get the implicit to-many join path to the <code>public.poll_votes</code>
     * table
     */
    public PollVotesPath pollVotes() {
        if (_pollVotes == null)
            _pollVotes = new PollVotesPath(this, null, Keys.POLL_VOTES__POLL_VOTES_OPTION_ID_FKEY.getInverseKey());

        return _pollVotes;
    }

    @Override
    public PollOptions as(String alias) {
        return new PollOptions(DSL.name(alias), this);
    }

    @Override
    public PollOptions as(Name alias) {
        return new PollOptions(alias, this);
    }

    @Override
    public PollOptions as(Table<?> alias) {
        return new PollOptions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PollOptions rename(String name) {
        return new PollOptions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PollOptions rename(Name name) {
        return new PollOptions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PollOptions rename(Table<?> name) {
        return new PollOptions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PollOptions where(Condition condition) {
        return new PollOptions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PollOptions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PollOptions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PollOptions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PollOptions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PollOptions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PollOptions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PollOptions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PollOptions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PollOptions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
