/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Indexes;
import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.Users.UsersPath;
import io.aeyer.voidcore.jooq.tables.records.ReactionsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Reactions extends TableImpl<ReactionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.reactions</code>
     */
    public static final Reactions REACTIONS = new Reactions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReactionsRecord> getRecordType() {
        return ReactionsRecord.class;
    }

    /**
     * The column <code>public.reactions.id</code>.
     */
    public final TableField<ReactionsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.reactions.target_type</code>.
     */
    public final TableField<ReactionsRecord, String> TARGET_TYPE = createField(DSL.name("target_type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.reactions.target_id</code>.
     */
    public final TableField<ReactionsRecord, Long> TARGET_ID = createField(DSL.name("target_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.reactions.user_id</code>.
     */
    public final TableField<ReactionsRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.reactions.reaction</code>.
     */
    public final TableField<ReactionsRecord, String> REACTION = createField(DSL.name("reaction"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.reactions.reacted_at</code>.
     */
    public final TableField<ReactionsRecord, OffsetDateTime> REACTED_AT = createField(DSL.name("reacted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Reactions(Name alias, Table<ReactionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Reactions(Name alias, Table<ReactionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.reactions</code> table reference
     */
    public Reactions(String alias) {
        this(DSL.name(alias), REACTIONS);
    }

    /**
     * Create an aliased <code>public.reactions</code> table reference
     */
    public Reactions(Name alias) {
        this(alias, REACTIONS);
    }

    /**
     * Create a <code>public.reactions</code> table reference
     */
    public Reactions() {
        this(DSL.name("reactions"), null);
    }

    public <O extends Record> Reactions(Table<O> path, ForeignKey<O, ReactionsRecord> childPath, InverseForeignKey<O, ReactionsRecord> parentPath) {
        super(path, childPath, parentPath, REACTIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReactionsPath extends Reactions implements Path<ReactionsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReactionsPath(Table<O> path, ForeignKey<O, ReactionsRecord> childPath, InverseForeignKey<O, ReactionsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReactionsPath(Name alias, Table<ReactionsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReactionsPath as(String alias) {
            return new ReactionsPath(DSL.name(alias), this);
        }

        @Override
        public ReactionsPath as(Name alias) {
            return new ReactionsPath(alias, this);
        }

        @Override
        public ReactionsPath as(Table<?> alias) {
            return new ReactionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_REACTIONS_TARGET, Indexes.IDX_REACTIONS_USER);
    }

    @Override
    public Identity<ReactionsRecord, Long> getIdentity() {
        return (Identity<ReactionsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReactionsRecord> getPrimaryKey() {
        return Keys.REACTIONS_PKEY;
    }

    @Override
    public List<UniqueKey<ReactionsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.REACTIONS_TARGET_TYPE_TARGET_ID_USER_ID_REACTION_KEY);
    }

    @Override
    public List<ForeignKey<ReactionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REACTIONS__REACTIONS_USER_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.REACTIONS__REACTIONS_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public Reactions as(String alias) {
        return new Reactions(DSL.name(alias), this);
    }

    @Override
    public Reactions as(Name alias) {
        return new Reactions(alias, this);
    }

    @Override
    public Reactions as(Table<?> alias) {
        return new Reactions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Reactions rename(String name) {
        return new Reactions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Reactions rename(Name name) {
        return new Reactions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Reactions rename(Table<?> name) {
        return new Reactions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reactions where(Condition condition) {
        return new Reactions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reactions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reactions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reactions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reactions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reactions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reactions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Reactions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reactions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Reactions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
