/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Indexes;
import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.DocumentRevisions.DocumentRevisionsPath;
import io.aeyer.voidcore.jooq.tables.Documents.DocumentsPath;
import io.aeyer.voidcore.jooq.tables.Users.UsersPath;
import io.aeyer.voidcore.jooq.tables.records.SchemasRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Schemas extends TableImpl<SchemasRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.schemas</code>
     */
    public static final Schemas SCHEMAS = new Schemas();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SchemasRecord> getRecordType() {
        return SchemasRecord.class;
    }

    /**
     * The column <code>public.schemas.id</code>.
     */
    public final TableField<SchemasRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.schemas.slug</code>.
     */
    public final TableField<SchemasRecord, String> SLUG = createField(DSL.name("slug"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.schemas.version</code>.
     */
    public final TableField<SchemasRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.schemas.label</code>.
     */
    public final TableField<SchemasRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.schemas.description</code>.
     */
    public final TableField<SchemasRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.schemas.definition</code>.
     */
    public final TableField<SchemasRecord, JSONB> DEFINITION = createField(DSL.name("definition"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.schemas.presentation</code>.
     */
    public final TableField<SchemasRecord, JSONB> PRESENTATION = createField(DSL.name("presentation"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.schemas.status</code>.
     */
    public final TableField<SchemasRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'active'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.schemas.created_by</code>.
     */
    public final TableField<SchemasRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.schemas.created_at</code>.
     */
    public final TableField<SchemasRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.schemas.updated_at</code>.
     */
    public final TableField<SchemasRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Schemas(Name alias, Table<SchemasRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Schemas(Name alias, Table<SchemasRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.schemas</code> table reference
     */
    public Schemas(String alias) {
        this(DSL.name(alias), SCHEMAS);
    }

    /**
     * Create an aliased <code>public.schemas</code> table reference
     */
    public Schemas(Name alias) {
        this(alias, SCHEMAS);
    }

    /**
     * Create a <code>public.schemas</code> table reference
     */
    public Schemas() {
        this(DSL.name("schemas"), null);
    }

    public <O extends Record> Schemas(Table<O> path, ForeignKey<O, SchemasRecord> childPath, InverseForeignKey<O, SchemasRecord> parentPath) {
        super(path, childPath, parentPath, SCHEMAS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SchemasPath extends Schemas implements Path<SchemasRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SchemasPath(Table<O> path, ForeignKey<O, SchemasRecord> childPath, InverseForeignKey<O, SchemasRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SchemasPath(Name alias, Table<SchemasRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SchemasPath as(String alias) {
            return new SchemasPath(DSL.name(alias), this);
        }

        @Override
        public SchemasPath as(Name alias) {
            return new SchemasPath(alias, this);
        }

        @Override
        public SchemasPath as(Table<?> alias) {
            return new SchemasPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SCHEMAS_SLUG_ACTIVE);
    }

    @Override
    public Identity<SchemasRecord, Long> getIdentity() {
        return (Identity<SchemasRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SchemasRecord> getPrimaryKey() {
        return Keys.SCHEMAS_PKEY;
    }

    @Override
    public List<UniqueKey<SchemasRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.SCHEMAS_SLUG_VERSION_KEY);
    }

    @Override
    public List<ForeignKey<SchemasRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SCHEMAS__SCHEMAS_CREATED_BY_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.SCHEMAS__SCHEMAS_CREATED_BY_FKEY, null);

        return _users;
    }

    private transient DocumentRevisionsPath _documentRevisions;

    /**
     * Get the implicit to-many join path to the
     * <code>public.document_revisions</code> table
     */
    public DocumentRevisionsPath documentRevisions() {
        if (_documentRevisions == null)
            _documentRevisions = new DocumentRevisionsPath(this, null, Keys.DOCUMENT_REVISIONS__DOCUMENT_REVISIONS_TYPE_FK.getInverseKey());

        return _documentRevisions;
    }

    private transient DocumentsPath _documents;

    /**
     * Get the implicit to-many join path to the <code>public.documents</code>
     * table
     */
    public DocumentsPath documents() {
        if (_documents == null)
            _documents = new DocumentsPath(this, null, Keys.DOCUMENTS__DOCUMENTS_TYPE_FK.getInverseKey());

        return _documents;
    }

    @Override
    public List<Check<SchemasRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("schemas_status_check"), "((status = ANY (ARRAY['draft'::text, 'active'::text, 'deprecated'::text])))", true),
            Internal.createCheck(this, DSL.name("schemas_version_check"), "((version >= 1))", true)
        );
    }

    @Override
    public Schemas as(String alias) {
        return new Schemas(DSL.name(alias), this);
    }

    @Override
    public Schemas as(Name alias) {
        return new Schemas(alias, this);
    }

    @Override
    public Schemas as(Table<?> alias) {
        return new Schemas(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Schemas rename(String name) {
        return new Schemas(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Schemas rename(Name name) {
        return new Schemas(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Schemas rename(Table<?> name) {
        return new Schemas(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Schemas where(Condition condition) {
        return new Schemas(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Schemas where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Schemas where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Schemas where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Schemas where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Schemas where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Schemas where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Schemas where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Schemas whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Schemas whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
