/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Indexes;
import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.Users.UsersPath;
import io.aeyer.voidcore.jooq.tables.records.SessionsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sessions extends TableImpl<SessionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.sessions</code>
     */
    public static final Sessions SESSIONS = new Sessions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SessionsRecord> getRecordType() {
        return SessionsRecord.class;
    }

    /**
     * The column <code>public.sessions.token</code>.
     */
    public final TableField<SessionsRecord, String> TOKEN = createField(DSL.name("token"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sessions.user_id</code>.
     */
    public final TableField<SessionsRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sessions.created_at</code>.
     */
    public final TableField<SessionsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.sessions.last_seen_at</code>.
     */
    public final TableField<SessionsRecord, OffsetDateTime> LAST_SEEN_AT = createField(DSL.name("last_seen_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.sessions.expires_at</code>.
     */
    public final TableField<SessionsRecord, OffsetDateTime> EXPIRES_AT = createField(DSL.name("expires_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.sessions.ip</code>.
     */
    public final TableField<SessionsRecord, String> IP = createField(DSL.name("ip"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.sessions.ua</code>.
     */
    public final TableField<SessionsRecord, String> UA = createField(DSL.name("ua"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.sessions.current_screen</code>.
     */
    public final TableField<SessionsRecord, JSONB> CURRENT_SCREEN = createField(DSL.name("current_screen"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{\"kind\": \"menu\"}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.sessions.app_state</code>.
     */
    public final TableField<SessionsRecord, JSONB> APP_STATE = createField(DSL.name("app_state"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    private Sessions(Name alias, Table<SessionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Sessions(Name alias, Table<SessionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.sessions</code> table reference
     */
    public Sessions(String alias) {
        this(DSL.name(alias), SESSIONS);
    }

    /**
     * Create an aliased <code>public.sessions</code> table reference
     */
    public Sessions(Name alias) {
        this(alias, SESSIONS);
    }

    /**
     * Create a <code>public.sessions</code> table reference
     */
    public Sessions() {
        this(DSL.name("sessions"), null);
    }

    public <O extends Record> Sessions(Table<O> path, ForeignKey<O, SessionsRecord> childPath, InverseForeignKey<O, SessionsRecord> parentPath) {
        super(path, childPath, parentPath, SESSIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SessionsPath extends Sessions implements Path<SessionsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SessionsPath(Table<O> path, ForeignKey<O, SessionsRecord> childPath, InverseForeignKey<O, SessionsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SessionsPath(Name alias, Table<SessionsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SessionsPath as(String alias) {
            return new SessionsPath(DSL.name(alias), this);
        }

        @Override
        public SessionsPath as(Name alias) {
            return new SessionsPath(alias, this);
        }

        @Override
        public SessionsPath as(Table<?> alias) {
            return new SessionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SESSIONS_EXPIRES, Indexes.IDX_SESSIONS_USER);
    }

    @Override
    public UniqueKey<SessionsRecord> getPrimaryKey() {
        return Keys.SESSIONS_PKEY;
    }

    @Override
    public List<ForeignKey<SessionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SESSIONS__SESSIONS_USER_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.SESSIONS__SESSIONS_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public Sessions as(String alias) {
        return new Sessions(DSL.name(alias), this);
    }

    @Override
    public Sessions as(Name alias) {
        return new Sessions(alias, this);
    }

    @Override
    public Sessions as(Table<?> alias) {
        return new Sessions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Sessions rename(String name) {
        return new Sessions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sessions rename(Name name) {
        return new Sessions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sessions rename(Table<?> name) {
        return new Sessions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sessions where(Condition condition) {
        return new Sessions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sessions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sessions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sessions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sessions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sessions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sessions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sessions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sessions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sessions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
