/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Indexes;
import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.Users.UsersPath;
import io.aeyer.voidcore.jooq.tables.records.SysopActionsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SysopActions extends TableImpl<SysopActionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.sysop_actions</code>
     */
    public static final SysopActions SYSOP_ACTIONS = new SysopActions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysopActionsRecord> getRecordType() {
        return SysopActionsRecord.class;
    }

    /**
     * The column <code>public.sysop_actions.id</code>.
     */
    public final TableField<SysopActionsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.sysop_actions.actor_id</code>.
     */
    public final TableField<SysopActionsRecord, Long> ACTOR_ID = createField(DSL.name("actor_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sysop_actions.action</code>.
     */
    public final TableField<SysopActionsRecord, String> ACTION = createField(DSL.name("action"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.sysop_actions.payload</code>.
     */
    public final TableField<SysopActionsRecord, JSONB> PAYLOAD = createField(DSL.name("payload"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.sysop_actions.at</code>.
     */
    public final TableField<SysopActionsRecord, OffsetDateTime> AT = createField(DSL.name("at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private SysopActions(Name alias, Table<SysopActionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SysopActions(Name alias, Table<SysopActionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.sysop_actions</code> table reference
     */
    public SysopActions(String alias) {
        this(DSL.name(alias), SYSOP_ACTIONS);
    }

    /**
     * Create an aliased <code>public.sysop_actions</code> table reference
     */
    public SysopActions(Name alias) {
        this(alias, SYSOP_ACTIONS);
    }

    /**
     * Create a <code>public.sysop_actions</code> table reference
     */
    public SysopActions() {
        this(DSL.name("sysop_actions"), null);
    }

    public <O extends Record> SysopActions(Table<O> path, ForeignKey<O, SysopActionsRecord> childPath, InverseForeignKey<O, SysopActionsRecord> parentPath) {
        super(path, childPath, parentPath, SYSOP_ACTIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SysopActionsPath extends SysopActions implements Path<SysopActionsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SysopActionsPath(Table<O> path, ForeignKey<O, SysopActionsRecord> childPath, InverseForeignKey<O, SysopActionsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SysopActionsPath(Name alias, Table<SysopActionsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SysopActionsPath as(String alias) {
            return new SysopActionsPath(DSL.name(alias), this);
        }

        @Override
        public SysopActionsPath as(Name alias) {
            return new SysopActionsPath(alias, this);
        }

        @Override
        public SysopActionsPath as(Table<?> alias) {
            return new SysopActionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SYSOP_ACTIONS_AT);
    }

    @Override
    public Identity<SysopActionsRecord, Long> getIdentity() {
        return (Identity<SysopActionsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SysopActionsRecord> getPrimaryKey() {
        return Keys.SYSOP_ACTIONS_PKEY;
    }

    @Override
    public List<ForeignKey<SysopActionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SYSOP_ACTIONS__SYSOP_ACTIONS_ACTOR_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.SYSOP_ACTIONS__SYSOP_ACTIONS_ACTOR_ID_FKEY, null);

        return _users;
    }

    @Override
    public SysopActions as(String alias) {
        return new SysopActions(DSL.name(alias), this);
    }

    @Override
    public SysopActions as(Name alias) {
        return new SysopActions(alias, this);
    }

    @Override
    public SysopActions as(Table<?> alias) {
        return new SysopActions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SysopActions rename(String name) {
        return new SysopActions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysopActions rename(Name name) {
        return new SysopActions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysopActions rename(Table<?> name) {
        return new SysopActions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SysopActions where(Condition condition) {
        return new SysopActions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SysopActions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SysopActions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SysopActions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SysopActions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SysopActions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SysopActions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SysopActions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SysopActions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SysopActions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
