/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Indexes;
import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.MessageBases.MessageBasesPath;
import io.aeyer.voidcore.jooq.tables.Posts.PostsPath;
import io.aeyer.voidcore.jooq.tables.ThreadRead.ThreadReadPath;
import io.aeyer.voidcore.jooq.tables.Users.UsersPath;
import io.aeyer.voidcore.jooq.tables.records.ThreadsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Threads extends TableImpl<ThreadsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.threads</code>
     */
    public static final Threads THREADS = new Threads();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ThreadsRecord> getRecordType() {
        return ThreadsRecord.class;
    }

    /**
     * The column <code>public.threads.id</code>.
     */
    public final TableField<ThreadsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.threads.base_id</code>.
     */
    public final TableField<ThreadsRecord, Long> BASE_ID = createField(DSL.name("base_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.threads.subject</code>.
     */
    public final TableField<ThreadsRecord, String> SUBJECT = createField(DSL.name("subject"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.threads.author_id</code>.
     */
    public final TableField<ThreadsRecord, Long> AUTHOR_ID = createField(DSL.name("author_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.threads.created_at</code>.
     */
    public final TableField<ThreadsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.threads.last_post_at</code>.
     */
    public final TableField<ThreadsRecord, OffsetDateTime> LAST_POST_AT = createField(DSL.name("last_post_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.threads.post_count</code>.
     */
    public final TableField<ThreadsRecord, Integer> POST_COUNT = createField(DSL.name("post_count"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.threads.is_pinned</code>.
     */
    public final TableField<ThreadsRecord, Boolean> IS_PINNED = createField(DSL.name("is_pinned"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.threads.is_locked</code>.
     */
    public final TableField<ThreadsRecord, Boolean> IS_LOCKED = createField(DSL.name("is_locked"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    private Threads(Name alias, Table<ThreadsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Threads(Name alias, Table<ThreadsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.threads</code> table reference
     */
    public Threads(String alias) {
        this(DSL.name(alias), THREADS);
    }

    /**
     * Create an aliased <code>public.threads</code> table reference
     */
    public Threads(Name alias) {
        this(alias, THREADS);
    }

    /**
     * Create a <code>public.threads</code> table reference
     */
    public Threads() {
        this(DSL.name("threads"), null);
    }

    public <O extends Record> Threads(Table<O> path, ForeignKey<O, ThreadsRecord> childPath, InverseForeignKey<O, ThreadsRecord> parentPath) {
        super(path, childPath, parentPath, THREADS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ThreadsPath extends Threads implements Path<ThreadsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ThreadsPath(Table<O> path, ForeignKey<O, ThreadsRecord> childPath, InverseForeignKey<O, ThreadsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ThreadsPath(Name alias, Table<ThreadsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ThreadsPath as(String alias) {
            return new ThreadsPath(DSL.name(alias), this);
        }

        @Override
        public ThreadsPath as(Name alias) {
            return new ThreadsPath(alias, this);
        }

        @Override
        public ThreadsPath as(Table<?> alias) {
            return new ThreadsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_THREADS_BASE_LASTPOST);
    }

    @Override
    public Identity<ThreadsRecord, Long> getIdentity() {
        return (Identity<ThreadsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ThreadsRecord> getPrimaryKey() {
        return Keys.THREADS_PKEY;
    }

    @Override
    public List<ForeignKey<ThreadsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.THREADS__THREADS_AUTHOR_ID_FKEY, Keys.THREADS__THREADS_BASE_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.THREADS__THREADS_AUTHOR_ID_FKEY, null);

        return _users;
    }

    private transient MessageBasesPath _messageBases;

    /**
     * Get the implicit join path to the <code>public.message_bases</code>
     * table.
     */
    public MessageBasesPath messageBases() {
        if (_messageBases == null)
            _messageBases = new MessageBasesPath(this, Keys.THREADS__THREADS_BASE_ID_FKEY, null);

        return _messageBases;
    }

    private transient PostsPath _posts;

    /**
     * Get the implicit to-many join path to the <code>public.posts</code> table
     */
    public PostsPath posts() {
        if (_posts == null)
            _posts = new PostsPath(this, null, Keys.POSTS__POSTS_THREAD_ID_FKEY.getInverseKey());

        return _posts;
    }

    private transient ThreadReadPath _threadRead;

    /**
     * Get the implicit to-many join path to the <code>public.thread_read</code>
     * table
     */
    public ThreadReadPath threadRead() {
        if (_threadRead == null)
            _threadRead = new ThreadReadPath(this, null, Keys.THREAD_READ__THREAD_READ_THREAD_ID_FKEY.getInverseKey());

        return _threadRead;
    }

    @Override
    public Threads as(String alias) {
        return new Threads(DSL.name(alias), this);
    }

    @Override
    public Threads as(Name alias) {
        return new Threads(alias, this);
    }

    @Override
    public Threads as(Table<?> alias) {
        return new Threads(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Threads rename(String name) {
        return new Threads(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Threads rename(Name name) {
        return new Threads(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Threads rename(Table<?> name) {
        return new Threads(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Threads where(Condition condition) {
        return new Threads(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Threads where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Threads where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Threads where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Threads where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Threads where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Threads where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Threads where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Threads whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Threads whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
