/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables;


import io.aeyer.voidcore.jooq.Keys;
import io.aeyer.voidcore.jooq.Public;
import io.aeyer.voidcore.jooq.tables.Threads.ThreadsPath;
import io.aeyer.voidcore.jooq.tables.Users.UsersPath;
import io.aeyer.voidcore.jooq.tables.records.ThreadReadRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ThreadRead extends TableImpl<ThreadReadRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.thread_read</code>
     */
    public static final ThreadRead THREAD_READ = new ThreadRead();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ThreadReadRecord> getRecordType() {
        return ThreadReadRecord.class;
    }

    /**
     * The column <code>public.thread_read.user_id</code>.
     */
    public final TableField<ThreadReadRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.thread_read.thread_id</code>.
     */
    public final TableField<ThreadReadRecord, Long> THREAD_ID = createField(DSL.name("thread_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.thread_read.last_read_at</code>.
     */
    public final TableField<ThreadReadRecord, OffsetDateTime> LAST_READ_AT = createField(DSL.name("last_read_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private ThreadRead(Name alias, Table<ThreadReadRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ThreadRead(Name alias, Table<ThreadReadRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.thread_read</code> table reference
     */
    public ThreadRead(String alias) {
        this(DSL.name(alias), THREAD_READ);
    }

    /**
     * Create an aliased <code>public.thread_read</code> table reference
     */
    public ThreadRead(Name alias) {
        this(alias, THREAD_READ);
    }

    /**
     * Create a <code>public.thread_read</code> table reference
     */
    public ThreadRead() {
        this(DSL.name("thread_read"), null);
    }

    public <O extends Record> ThreadRead(Table<O> path, ForeignKey<O, ThreadReadRecord> childPath, InverseForeignKey<O, ThreadReadRecord> parentPath) {
        super(path, childPath, parentPath, THREAD_READ);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ThreadReadPath extends ThreadRead implements Path<ThreadReadRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ThreadReadPath(Table<O> path, ForeignKey<O, ThreadReadRecord> childPath, InverseForeignKey<O, ThreadReadRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ThreadReadPath(Name alias, Table<ThreadReadRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ThreadReadPath as(String alias) {
            return new ThreadReadPath(DSL.name(alias), this);
        }

        @Override
        public ThreadReadPath as(Name alias) {
            return new ThreadReadPath(alias, this);
        }

        @Override
        public ThreadReadPath as(Table<?> alias) {
            return new ThreadReadPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ThreadReadRecord> getPrimaryKey() {
        return Keys.THREAD_READ_PKEY;
    }

    @Override
    public List<ForeignKey<ThreadReadRecord, ?>> getReferences() {
        return Arrays.asList(Keys.THREAD_READ__THREAD_READ_THREAD_ID_FKEY, Keys.THREAD_READ__THREAD_READ_USER_ID_FKEY);
    }

    private transient ThreadsPath _threads;

    /**
     * Get the implicit join path to the <code>public.threads</code> table.
     */
    public ThreadsPath threads() {
        if (_threads == null)
            _threads = new ThreadsPath(this, Keys.THREAD_READ__THREAD_READ_THREAD_ID_FKEY, null);

        return _threads;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.THREAD_READ__THREAD_READ_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public ThreadRead as(String alias) {
        return new ThreadRead(DSL.name(alias), this);
    }

    @Override
    public ThreadRead as(Name alias) {
        return new ThreadRead(alias, this);
    }

    @Override
    public ThreadRead as(Table<?> alias) {
        return new ThreadRead(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ThreadRead rename(String name) {
        return new ThreadRead(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ThreadRead rename(Name name) {
        return new ThreadRead(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ThreadRead rename(Table<?> name) {
        return new ThreadRead(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ThreadRead where(Condition condition) {
        return new ThreadRead(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ThreadRead where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ThreadRead where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ThreadRead where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ThreadRead where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ThreadRead where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ThreadRead where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ThreadRead where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ThreadRead whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ThreadRead whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
