/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Achievements implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String slug;
    private final String name;
    private final String description;
    private final OffsetDateTime createdAt;
    private final Integer points;
    private final String category;
    private final String source;

    public Achievements(Achievements value) {
        this.id = value.id;
        this.slug = value.slug;
        this.name = value.name;
        this.description = value.description;
        this.createdAt = value.createdAt;
        this.points = value.points;
        this.category = value.category;
        this.source = value.source;
    }

    public Achievements(
        Long id,
        String slug,
        String name,
        String description,
        OffsetDateTime createdAt,
        Integer points,
        String category,
        String source
    ) {
        this.id = id;
        this.slug = slug;
        this.name = name;
        this.description = description;
        this.createdAt = createdAt;
        this.points = points;
        this.category = category;
        this.source = source;
    }

    /**
     * Getter for <code>public.achievements.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.achievements.slug</code>.
     */
    public String getSlug() {
        return this.slug;
    }

    /**
     * Getter for <code>public.achievements.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.achievements.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Getter for <code>public.achievements.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>public.achievements.points</code>.
     */
    public Integer getPoints() {
        return this.points;
    }

    /**
     * Getter for <code>public.achievements.category</code>.
     */
    public String getCategory() {
        return this.category;
    }

    /**
     * Getter for <code>public.achievements.source</code>.
     */
    public String getSource() {
        return this.source;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Achievements other = (Achievements) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.slug == null) {
            if (other.slug != null)
                return false;
        }
        else if (!this.slug.equals(other.slug))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.points == null) {
            if (other.points != null)
                return false;
        }
        else if (!this.points.equals(other.points))
            return false;
        if (this.category == null) {
            if (other.category != null)
                return false;
        }
        else if (!this.category.equals(other.category))
            return false;
        if (this.source == null) {
            if (other.source != null)
                return false;
        }
        else if (!this.source.equals(other.source))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.slug == null) ? 0 : this.slug.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.points == null) ? 0 : this.points.hashCode());
        result = prime * result + ((this.category == null) ? 0 : this.category.hashCode());
        result = prime * result + ((this.source == null) ? 0 : this.source.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Achievements (");

        sb.append(id);
        sb.append(", ").append(slug);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(points);
        sb.append(", ").append(category);
        sb.append(", ").append(source);

        sb.append(")");
        return sb.toString();
    }
}
