/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AclGrants implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String resourceType;
    private final Long resourceId;
    private final String permission;
    private final String principalType;
    private final Long principalId;
    private final OffsetDateTime createdAt;

    public AclGrants(AclGrants value) {
        this.id = value.id;
        this.resourceType = value.resourceType;
        this.resourceId = value.resourceId;
        this.permission = value.permission;
        this.principalType = value.principalType;
        this.principalId = value.principalId;
        this.createdAt = value.createdAt;
    }

    public AclGrants(
        Long id,
        String resourceType,
        Long resourceId,
        String permission,
        String principalType,
        Long principalId,
        OffsetDateTime createdAt
    ) {
        this.id = id;
        this.resourceType = resourceType;
        this.resourceId = resourceId;
        this.permission = permission;
        this.principalType = principalType;
        this.principalId = principalId;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.acl_grants.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.acl_grants.resource_type</code>.
     */
    public String getResourceType() {
        return this.resourceType;
    }

    /**
     * Getter for <code>public.acl_grants.resource_id</code>.
     */
    public Long getResourceId() {
        return this.resourceId;
    }

    /**
     * Getter for <code>public.acl_grants.permission</code>.
     */
    public String getPermission() {
        return this.permission;
    }

    /**
     * Getter for <code>public.acl_grants.principal_type</code>.
     */
    public String getPrincipalType() {
        return this.principalType;
    }

    /**
     * Getter for <code>public.acl_grants.principal_id</code>.
     */
    public Long getPrincipalId() {
        return this.principalId;
    }

    /**
     * Getter for <code>public.acl_grants.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AclGrants other = (AclGrants) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.resourceType == null) {
            if (other.resourceType != null)
                return false;
        }
        else if (!this.resourceType.equals(other.resourceType))
            return false;
        if (this.resourceId == null) {
            if (other.resourceId != null)
                return false;
        }
        else if (!this.resourceId.equals(other.resourceId))
            return false;
        if (this.permission == null) {
            if (other.permission != null)
                return false;
        }
        else if (!this.permission.equals(other.permission))
            return false;
        if (this.principalType == null) {
            if (other.principalType != null)
                return false;
        }
        else if (!this.principalType.equals(other.principalType))
            return false;
        if (this.principalId == null) {
            if (other.principalId != null)
                return false;
        }
        else if (!this.principalId.equals(other.principalId))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.resourceType == null) ? 0 : this.resourceType.hashCode());
        result = prime * result + ((this.resourceId == null) ? 0 : this.resourceId.hashCode());
        result = prime * result + ((this.permission == null) ? 0 : this.permission.hashCode());
        result = prime * result + ((this.principalType == null) ? 0 : this.principalType.hashCode());
        result = prime * result + ((this.principalId == null) ? 0 : this.principalId.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AclGrants (");

        sb.append(id);
        sb.append(", ").append(resourceType);
        sb.append(", ").append(resourceId);
        sb.append(", ").append(permission);
        sb.append(", ").append(principalType);
        sb.append(", ").append(principalId);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
