/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ActivityEvents implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String topic;
    private final Long actorId;
    private final JSONB payload;
    private final OffsetDateTime emittedAt;

    public ActivityEvents(ActivityEvents value) {
        this.id = value.id;
        this.topic = value.topic;
        this.actorId = value.actorId;
        this.payload = value.payload;
        this.emittedAt = value.emittedAt;
    }

    public ActivityEvents(
        Long id,
        String topic,
        Long actorId,
        JSONB payload,
        OffsetDateTime emittedAt
    ) {
        this.id = id;
        this.topic = topic;
        this.actorId = actorId;
        this.payload = payload;
        this.emittedAt = emittedAt;
    }

    /**
     * Getter for <code>public.activity_events.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.activity_events.topic</code>.
     */
    public String getTopic() {
        return this.topic;
    }

    /**
     * Getter for <code>public.activity_events.actor_id</code>.
     */
    public Long getActorId() {
        return this.actorId;
    }

    /**
     * Getter for <code>public.activity_events.payload</code>.
     */
    public JSONB getPayload() {
        return this.payload;
    }

    /**
     * Getter for <code>public.activity_events.emitted_at</code>.
     */
    public OffsetDateTime getEmittedAt() {
        return this.emittedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ActivityEvents other = (ActivityEvents) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.topic == null) {
            if (other.topic != null)
                return false;
        }
        else if (!this.topic.equals(other.topic))
            return false;
        if (this.actorId == null) {
            if (other.actorId != null)
                return false;
        }
        else if (!this.actorId.equals(other.actorId))
            return false;
        if (this.payload == null) {
            if (other.payload != null)
                return false;
        }
        else if (!this.payload.equals(other.payload))
            return false;
        if (this.emittedAt == null) {
            if (other.emittedAt != null)
                return false;
        }
        else if (!this.emittedAt.equals(other.emittedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.topic == null) ? 0 : this.topic.hashCode());
        result = prime * result + ((this.actorId == null) ? 0 : this.actorId.hashCode());
        result = prime * result + ((this.payload == null) ? 0 : this.payload.hashCode());
        result = prime * result + ((this.emittedAt == null) ? 0 : this.emittedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActivityEvents (");

        sb.append(id);
        sb.append(", ").append(topic);
        sb.append(", ").append(actorId);
        sb.append(", ").append(payload);
        sb.append(", ").append(emittedAt);

        sb.append(")");
        return sb.toString();
    }
}
