/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChatRooms implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String slug;
    private final String label;
    private final Boolean isPrivate;
    private final Boolean isActive;
    private final Integer sortOrder;
    private final OffsetDateTime createdAt;
    private final Boolean isDm;

    public ChatRooms(ChatRooms value) {
        this.id = value.id;
        this.slug = value.slug;
        this.label = value.label;
        this.isPrivate = value.isPrivate;
        this.isActive = value.isActive;
        this.sortOrder = value.sortOrder;
        this.createdAt = value.createdAt;
        this.isDm = value.isDm;
    }

    public ChatRooms(
        Long id,
        String slug,
        String label,
        Boolean isPrivate,
        Boolean isActive,
        Integer sortOrder,
        OffsetDateTime createdAt,
        Boolean isDm
    ) {
        this.id = id;
        this.slug = slug;
        this.label = label;
        this.isPrivate = isPrivate;
        this.isActive = isActive;
        this.sortOrder = sortOrder;
        this.createdAt = createdAt;
        this.isDm = isDm;
    }

    /**
     * Getter for <code>public.chat_rooms.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.chat_rooms.slug</code>.
     */
    public String getSlug() {
        return this.slug;
    }

    /**
     * Getter for <code>public.chat_rooms.label</code>.
     */
    public String getLabel() {
        return this.label;
    }

    /**
     * Getter for <code>public.chat_rooms.is_private</code>.
     */
    public Boolean getIsPrivate() {
        return this.isPrivate;
    }

    /**
     * Getter for <code>public.chat_rooms.is_active</code>.
     */
    public Boolean getIsActive() {
        return this.isActive;
    }

    /**
     * Getter for <code>public.chat_rooms.sort_order</code>.
     */
    public Integer getSortOrder() {
        return this.sortOrder;
    }

    /**
     * Getter for <code>public.chat_rooms.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>public.chat_rooms.is_dm</code>.
     */
    public Boolean getIsDm() {
        return this.isDm;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ChatRooms other = (ChatRooms) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.slug == null) {
            if (other.slug != null)
                return false;
        }
        else if (!this.slug.equals(other.slug))
            return false;
        if (this.label == null) {
            if (other.label != null)
                return false;
        }
        else if (!this.label.equals(other.label))
            return false;
        if (this.isPrivate == null) {
            if (other.isPrivate != null)
                return false;
        }
        else if (!this.isPrivate.equals(other.isPrivate))
            return false;
        if (this.isActive == null) {
            if (other.isActive != null)
                return false;
        }
        else if (!this.isActive.equals(other.isActive))
            return false;
        if (this.sortOrder == null) {
            if (other.sortOrder != null)
                return false;
        }
        else if (!this.sortOrder.equals(other.sortOrder))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.isDm == null) {
            if (other.isDm != null)
                return false;
        }
        else if (!this.isDm.equals(other.isDm))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.slug == null) ? 0 : this.slug.hashCode());
        result = prime * result + ((this.label == null) ? 0 : this.label.hashCode());
        result = prime * result + ((this.isPrivate == null) ? 0 : this.isPrivate.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        result = prime * result + ((this.sortOrder == null) ? 0 : this.sortOrder.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.isDm == null) ? 0 : this.isDm.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChatRooms (");

        sb.append(id);
        sb.append(", ").append(slug);
        sb.append(", ").append(label);
        sb.append(", ").append(isPrivate);
        sb.append(", ").append(isActive);
        sb.append(", ").append(sortOrder);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(isDm);

        sb.append(")");
        return sb.toString();
    }
}
