/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChatRoomMembers implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long roomId;
    private final Long userId;
    private final OffsetDateTime grantedAt;

    public ChatRoomMembers(ChatRoomMembers value) {
        this.roomId = value.roomId;
        this.userId = value.userId;
        this.grantedAt = value.grantedAt;
    }

    public ChatRoomMembers(
        Long roomId,
        Long userId,
        OffsetDateTime grantedAt
    ) {
        this.roomId = roomId;
        this.userId = userId;
        this.grantedAt = grantedAt;
    }

    /**
     * Getter for <code>public.chat_room_members.room_id</code>.
     */
    public Long getRoomId() {
        return this.roomId;
    }

    /**
     * Getter for <code>public.chat_room_members.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.chat_room_members.granted_at</code>.
     */
    public OffsetDateTime getGrantedAt() {
        return this.grantedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ChatRoomMembers other = (ChatRoomMembers) obj;
        if (this.roomId == null) {
            if (other.roomId != null)
                return false;
        }
        else if (!this.roomId.equals(other.roomId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.grantedAt == null) {
            if (other.grantedAt != null)
                return false;
        }
        else if (!this.grantedAt.equals(other.grantedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.roomId == null) ? 0 : this.roomId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.grantedAt == null) ? 0 : this.grantedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChatRoomMembers (");

        sb.append(roomId);
        sb.append(", ").append(userId);
        sb.append(", ").append(grantedAt);

        sb.append(")");
        return sb.toString();
    }
}
