/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.Arrays;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DocumentRevisions implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long documentId;
    private final String body;
    private final JSONB frontmatter;
    private final Long editedBy;
    private final OffsetDateTime editedAt;
    private final Integer rev;
    private final String title;
    private final String[] tags;
    private final String visibility;
    private final String status;
    private final String typeSlug;
    private final Integer typeVersion;
    private final String editSummary;
    private final Boolean isDeletion;

    public DocumentRevisions(DocumentRevisions value) {
        this.id = value.id;
        this.documentId = value.documentId;
        this.body = value.body;
        this.frontmatter = value.frontmatter;
        this.editedBy = value.editedBy;
        this.editedAt = value.editedAt;
        this.rev = value.rev;
        this.title = value.title;
        this.tags = value.tags;
        this.visibility = value.visibility;
        this.status = value.status;
        this.typeSlug = value.typeSlug;
        this.typeVersion = value.typeVersion;
        this.editSummary = value.editSummary;
        this.isDeletion = value.isDeletion;
    }

    public DocumentRevisions(
        Long id,
        Long documentId,
        String body,
        JSONB frontmatter,
        Long editedBy,
        OffsetDateTime editedAt,
        Integer rev,
        String title,
        String[] tags,
        String visibility,
        String status,
        String typeSlug,
        Integer typeVersion,
        String editSummary,
        Boolean isDeletion
    ) {
        this.id = id;
        this.documentId = documentId;
        this.body = body;
        this.frontmatter = frontmatter;
        this.editedBy = editedBy;
        this.editedAt = editedAt;
        this.rev = rev;
        this.title = title;
        this.tags = tags;
        this.visibility = visibility;
        this.status = status;
        this.typeSlug = typeSlug;
        this.typeVersion = typeVersion;
        this.editSummary = editSummary;
        this.isDeletion = isDeletion;
    }

    /**
     * Getter for <code>public.document_revisions.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.document_revisions.document_id</code>.
     */
    public Long getDocumentId() {
        return this.documentId;
    }

    /**
     * Getter for <code>public.document_revisions.body</code>.
     */
    public String getBody() {
        return this.body;
    }

    /**
     * Getter for <code>public.document_revisions.frontmatter</code>.
     */
    public JSONB getFrontmatter() {
        return this.frontmatter;
    }

    /**
     * Getter for <code>public.document_revisions.edited_by</code>.
     */
    public Long getEditedBy() {
        return this.editedBy;
    }

    /**
     * Getter for <code>public.document_revisions.edited_at</code>.
     */
    public OffsetDateTime getEditedAt() {
        return this.editedAt;
    }

    /**
     * Getter for <code>public.document_revisions.rev</code>.
     */
    public Integer getRev() {
        return this.rev;
    }

    /**
     * Getter for <code>public.document_revisions.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Getter for <code>public.document_revisions.tags</code>.
     */
    public String[] getTags() {
        return this.tags;
    }

    /**
     * Getter for <code>public.document_revisions.visibility</code>.
     */
    public String getVisibility() {
        return this.visibility;
    }

    /**
     * Getter for <code>public.document_revisions.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Getter for <code>public.document_revisions.type_slug</code>.
     */
    public String getTypeSlug() {
        return this.typeSlug;
    }

    /**
     * Getter for <code>public.document_revisions.type_version</code>.
     */
    public Integer getTypeVersion() {
        return this.typeVersion;
    }

    /**
     * Getter for <code>public.document_revisions.edit_summary</code>.
     */
    public String getEditSummary() {
        return this.editSummary;
    }

    /**
     * Getter for <code>public.document_revisions.is_deletion</code>.
     */
    public Boolean getIsDeletion() {
        return this.isDeletion;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DocumentRevisions other = (DocumentRevisions) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.documentId == null) {
            if (other.documentId != null)
                return false;
        }
        else if (!this.documentId.equals(other.documentId))
            return false;
        if (this.body == null) {
            if (other.body != null)
                return false;
        }
        else if (!this.body.equals(other.body))
            return false;
        if (this.frontmatter == null) {
            if (other.frontmatter != null)
                return false;
        }
        else if (!this.frontmatter.equals(other.frontmatter))
            return false;
        if (this.editedBy == null) {
            if (other.editedBy != null)
                return false;
        }
        else if (!this.editedBy.equals(other.editedBy))
            return false;
        if (this.editedAt == null) {
            if (other.editedAt != null)
                return false;
        }
        else if (!this.editedAt.equals(other.editedAt))
            return false;
        if (this.rev == null) {
            if (other.rev != null)
                return false;
        }
        else if (!this.rev.equals(other.rev))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.tags == null) {
            if (other.tags != null)
                return false;
        }
        else if (!Arrays.deepEquals(this.tags, other.tags))
            return false;
        if (this.visibility == null) {
            if (other.visibility != null)
                return false;
        }
        else if (!this.visibility.equals(other.visibility))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.typeSlug == null) {
            if (other.typeSlug != null)
                return false;
        }
        else if (!this.typeSlug.equals(other.typeSlug))
            return false;
        if (this.typeVersion == null) {
            if (other.typeVersion != null)
                return false;
        }
        else if (!this.typeVersion.equals(other.typeVersion))
            return false;
        if (this.editSummary == null) {
            if (other.editSummary != null)
                return false;
        }
        else if (!this.editSummary.equals(other.editSummary))
            return false;
        if (this.isDeletion == null) {
            if (other.isDeletion != null)
                return false;
        }
        else if (!this.isDeletion.equals(other.isDeletion))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.documentId == null) ? 0 : this.documentId.hashCode());
        result = prime * result + ((this.body == null) ? 0 : this.body.hashCode());
        result = prime * result + ((this.frontmatter == null) ? 0 : this.frontmatter.hashCode());
        result = prime * result + ((this.editedBy == null) ? 0 : this.editedBy.hashCode());
        result = prime * result + ((this.editedAt == null) ? 0 : this.editedAt.hashCode());
        result = prime * result + ((this.rev == null) ? 0 : this.rev.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.tags == null) ? 0 : Arrays.deepHashCode(this.tags));
        result = prime * result + ((this.visibility == null) ? 0 : this.visibility.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.typeSlug == null) ? 0 : this.typeSlug.hashCode());
        result = prime * result + ((this.typeVersion == null) ? 0 : this.typeVersion.hashCode());
        result = prime * result + ((this.editSummary == null) ? 0 : this.editSummary.hashCode());
        result = prime * result + ((this.isDeletion == null) ? 0 : this.isDeletion.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DocumentRevisions (");

        sb.append(id);
        sb.append(", ").append(documentId);
        sb.append(", ").append(body);
        sb.append(", ").append(frontmatter);
        sb.append(", ").append(editedBy);
        sb.append(", ").append(editedAt);
        sb.append(", ").append(rev);
        sb.append(", ").append(title);
        sb.append(", ").append(Arrays.deepToString(tags));
        sb.append(", ").append(visibility);
        sb.append(", ").append(status);
        sb.append(", ").append(typeSlug);
        sb.append(", ").append(typeVersion);
        sb.append(", ").append(editSummary);
        sb.append(", ").append(isDeletion);

        sb.append(")");
        return sb.toString();
    }
}
