/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DocumentEditors implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long documentId;
    private final Long userId;

    public DocumentEditors(DocumentEditors value) {
        this.documentId = value.documentId;
        this.userId = value.userId;
    }

    public DocumentEditors(
        Long documentId,
        Long userId
    ) {
        this.documentId = documentId;
        this.userId = userId;
    }

    /**
     * Getter for <code>public.document_editors.document_id</code>.
     */
    public Long getDocumentId() {
        return this.documentId;
    }

    /**
     * Getter for <code>public.document_editors.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DocumentEditors other = (DocumentEditors) obj;
        if (this.documentId == null) {
            if (other.documentId != null)
                return false;
        }
        else if (!this.documentId.equals(other.documentId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.documentId == null) ? 0 : this.documentId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DocumentEditors (");

        sb.append(documentId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
