/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Documents implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String slug;
    private final String title;
    private final String typeSlug;
    private final String body;
    private final JSONB frontmatter;
    private final String[] tags;
    private final Long authorId;
    private final String visibility;
    private final String status;
    private final OffsetDateTime createdAt;
    private final OffsetDateTime updatedAt;
    private final Object searchVector;
    private final UUID anchorDocumentId;
    private final Integer typeVersion;
    private final Integer rev;
    private final OffsetDateTime deletedAt;
    private final Long deletedBy;

    public Documents(Documents value) {
        this.id = value.id;
        this.slug = value.slug;
        this.title = value.title;
        this.typeSlug = value.typeSlug;
        this.body = value.body;
        this.frontmatter = value.frontmatter;
        this.tags = value.tags;
        this.authorId = value.authorId;
        this.visibility = value.visibility;
        this.status = value.status;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.searchVector = value.searchVector;
        this.anchorDocumentId = value.anchorDocumentId;
        this.typeVersion = value.typeVersion;
        this.rev = value.rev;
        this.deletedAt = value.deletedAt;
        this.deletedBy = value.deletedBy;
    }

    public Documents(
        Long id,
        String slug,
        String title,
        String typeSlug,
        String body,
        JSONB frontmatter,
        String[] tags,
        Long authorId,
        String visibility,
        String status,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt,
        Object searchVector,
        UUID anchorDocumentId,
        Integer typeVersion,
        Integer rev,
        OffsetDateTime deletedAt,
        Long deletedBy
    ) {
        this.id = id;
        this.slug = slug;
        this.title = title;
        this.typeSlug = typeSlug;
        this.body = body;
        this.frontmatter = frontmatter;
        this.tags = tags;
        this.authorId = authorId;
        this.visibility = visibility;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.searchVector = searchVector;
        this.anchorDocumentId = anchorDocumentId;
        this.typeVersion = typeVersion;
        this.rev = rev;
        this.deletedAt = deletedAt;
        this.deletedBy = deletedBy;
    }

    /**
     * Getter for <code>public.documents.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.documents.slug</code>.
     */
    public String getSlug() {
        return this.slug;
    }

    /**
     * Getter for <code>public.documents.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Getter for <code>public.documents.type_slug</code>.
     */
    public String getTypeSlug() {
        return this.typeSlug;
    }

    /**
     * Getter for <code>public.documents.body</code>.
     */
    public String getBody() {
        return this.body;
    }

    /**
     * Getter for <code>public.documents.frontmatter</code>.
     */
    public JSONB getFrontmatter() {
        return this.frontmatter;
    }

    /**
     * Getter for <code>public.documents.tags</code>.
     */
    public String[] getTags() {
        return this.tags;
    }

    /**
     * Getter for <code>public.documents.author_id</code>.
     */
    public Long getAuthorId() {
        return this.authorId;
    }

    /**
     * Getter for <code>public.documents.visibility</code>.
     */
    public String getVisibility() {
        return this.visibility;
    }

    /**
     * Getter for <code>public.documents.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Getter for <code>public.documents.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>public.documents.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getSearchVector() {
        return this.searchVector;
    }

    /**
     * Getter for <code>public.documents.anchor_document_id</code>.
     */
    public UUID getAnchorDocumentId() {
        return this.anchorDocumentId;
    }

    /**
     * Getter for <code>public.documents.type_version</code>.
     */
    public Integer getTypeVersion() {
        return this.typeVersion;
    }

    /**
     * Getter for <code>public.documents.rev</code>.
     */
    public Integer getRev() {
        return this.rev;
    }

    /**
     * Getter for <code>public.documents.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return this.deletedAt;
    }

    /**
     * Getter for <code>public.documents.deleted_by</code>.
     */
    public Long getDeletedBy() {
        return this.deletedBy;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Documents other = (Documents) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.slug == null) {
            if (other.slug != null)
                return false;
        }
        else if (!this.slug.equals(other.slug))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.typeSlug == null) {
            if (other.typeSlug != null)
                return false;
        }
        else if (!this.typeSlug.equals(other.typeSlug))
            return false;
        if (this.body == null) {
            if (other.body != null)
                return false;
        }
        else if (!this.body.equals(other.body))
            return false;
        if (this.frontmatter == null) {
            if (other.frontmatter != null)
                return false;
        }
        else if (!this.frontmatter.equals(other.frontmatter))
            return false;
        if (this.tags == null) {
            if (other.tags != null)
                return false;
        }
        else if (!Arrays.deepEquals(this.tags, other.tags))
            return false;
        if (this.authorId == null) {
            if (other.authorId != null)
                return false;
        }
        else if (!this.authorId.equals(other.authorId))
            return false;
        if (this.visibility == null) {
            if (other.visibility != null)
                return false;
        }
        else if (!this.visibility.equals(other.visibility))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        if (this.searchVector == null) {
            if (other.searchVector != null)
                return false;
        }
        else if (!this.searchVector.equals(other.searchVector))
            return false;
        if (this.anchorDocumentId == null) {
            if (other.anchorDocumentId != null)
                return false;
        }
        else if (!this.anchorDocumentId.equals(other.anchorDocumentId))
            return false;
        if (this.typeVersion == null) {
            if (other.typeVersion != null)
                return false;
        }
        else if (!this.typeVersion.equals(other.typeVersion))
            return false;
        if (this.rev == null) {
            if (other.rev != null)
                return false;
        }
        else if (!this.rev.equals(other.rev))
            return false;
        if (this.deletedAt == null) {
            if (other.deletedAt != null)
                return false;
        }
        else if (!this.deletedAt.equals(other.deletedAt))
            return false;
        if (this.deletedBy == null) {
            if (other.deletedBy != null)
                return false;
        }
        else if (!this.deletedBy.equals(other.deletedBy))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.slug == null) ? 0 : this.slug.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.typeSlug == null) ? 0 : this.typeSlug.hashCode());
        result = prime * result + ((this.body == null) ? 0 : this.body.hashCode());
        result = prime * result + ((this.frontmatter == null) ? 0 : this.frontmatter.hashCode());
        result = prime * result + ((this.tags == null) ? 0 : Arrays.deepHashCode(this.tags));
        result = prime * result + ((this.authorId == null) ? 0 : this.authorId.hashCode());
        result = prime * result + ((this.visibility == null) ? 0 : this.visibility.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.searchVector == null) ? 0 : this.searchVector.hashCode());
        result = prime * result + ((this.anchorDocumentId == null) ? 0 : this.anchorDocumentId.hashCode());
        result = prime * result + ((this.typeVersion == null) ? 0 : this.typeVersion.hashCode());
        result = prime * result + ((this.rev == null) ? 0 : this.rev.hashCode());
        result = prime * result + ((this.deletedAt == null) ? 0 : this.deletedAt.hashCode());
        result = prime * result + ((this.deletedBy == null) ? 0 : this.deletedBy.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Documents (");

        sb.append(id);
        sb.append(", ").append(slug);
        sb.append(", ").append(title);
        sb.append(", ").append(typeSlug);
        sb.append(", ").append(body);
        sb.append(", ").append(frontmatter);
        sb.append(", ").append(Arrays.deepToString(tags));
        sb.append(", ").append(authorId);
        sb.append(", ").append(visibility);
        sb.append(", ").append(status);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(searchVector);
        sb.append(", ").append(anchorDocumentId);
        sb.append(", ").append(typeVersion);
        sb.append(", ").append(rev);
        sb.append(", ").append(deletedAt);
        sb.append(", ").append(deletedBy);

        sb.append(")");
        return sb.toString();
    }
}
