/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InstanceFeatures implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String featureSlug;
    private final Boolean enabled;

    public InstanceFeatures(InstanceFeatures value) {
        this.featureSlug = value.featureSlug;
        this.enabled = value.enabled;
    }

    public InstanceFeatures(
        String featureSlug,
        Boolean enabled
    ) {
        this.featureSlug = featureSlug;
        this.enabled = enabled;
    }

    /**
     * Getter for <code>public.instance_features.feature_slug</code>.
     */
    public String getFeatureSlug() {
        return this.featureSlug;
    }

    /**
     * Getter for <code>public.instance_features.enabled</code>.
     */
    public Boolean getEnabled() {
        return this.enabled;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final InstanceFeatures other = (InstanceFeatures) obj;
        if (this.featureSlug == null) {
            if (other.featureSlug != null)
                return false;
        }
        else if (!this.featureSlug.equals(other.featureSlug))
            return false;
        if (this.enabled == null) {
            if (other.enabled != null)
                return false;
        }
        else if (!this.enabled.equals(other.enabled))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.featureSlug == null) ? 0 : this.featureSlug.hashCode());
        result = prime * result + ((this.enabled == null) ? 0 : this.enabled.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InstanceFeatures (");

        sb.append(featureSlug);
        sb.append(", ").append(enabled);

        sb.append(")");
        return sb.toString();
    }
}
