/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LastCallers implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long userId;
    private final OffsetDateTime at;

    public LastCallers(LastCallers value) {
        this.id = value.id;
        this.userId = value.userId;
        this.at = value.at;
    }

    public LastCallers(
        Long id,
        Long userId,
        OffsetDateTime at
    ) {
        this.id = id;
        this.userId = userId;
        this.at = at;
    }

    /**
     * Getter for <code>public.last_callers.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.last_callers.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.last_callers.at</code>.
     */
    public OffsetDateTime getAt() {
        return this.at;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final LastCallers other = (LastCallers) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.at == null) {
            if (other.at != null)
                return false;
        }
        else if (!this.at.equals(other.at))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.at == null) ? 0 : this.at.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LastCallers (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(at);

        sb.append(")");
        return sb.toString();
    }
}
