/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LoginAttempts implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String ip;
    private final String handle;
    private final Boolean success;
    private final OffsetDateTime at;

    public LoginAttempts(LoginAttempts value) {
        this.id = value.id;
        this.ip = value.ip;
        this.handle = value.handle;
        this.success = value.success;
        this.at = value.at;
    }

    public LoginAttempts(
        Long id,
        String ip,
        String handle,
        Boolean success,
        OffsetDateTime at
    ) {
        this.id = id;
        this.ip = ip;
        this.handle = handle;
        this.success = success;
        this.at = at;
    }

    /**
     * Getter for <code>public.login_attempts.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.login_attempts.ip</code>.
     */
    public String getIp() {
        return this.ip;
    }

    /**
     * Getter for <code>public.login_attempts.handle</code>.
     */
    public String getHandle() {
        return this.handle;
    }

    /**
     * Getter for <code>public.login_attempts.success</code>.
     */
    public Boolean getSuccess() {
        return this.success;
    }

    /**
     * Getter for <code>public.login_attempts.at</code>.
     */
    public OffsetDateTime getAt() {
        return this.at;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final LoginAttempts other = (LoginAttempts) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.ip == null) {
            if (other.ip != null)
                return false;
        }
        else if (!this.ip.equals(other.ip))
            return false;
        if (this.handle == null) {
            if (other.handle != null)
                return false;
        }
        else if (!this.handle.equals(other.handle))
            return false;
        if (this.success == null) {
            if (other.success != null)
                return false;
        }
        else if (!this.success.equals(other.success))
            return false;
        if (this.at == null) {
            if (other.at != null)
                return false;
        }
        else if (!this.at.equals(other.at))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.ip == null) ? 0 : this.ip.hashCode());
        result = prime * result + ((this.handle == null) ? 0 : this.handle.hashCode());
        result = prime * result + ((this.success == null) ? 0 : this.success.hashCode());
        result = prime * result + ((this.at == null) ? 0 : this.at.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LoginAttempts (");

        sb.append(id);
        sb.append(", ").append(ip);
        sb.append(", ").append(handle);
        sb.append(", ").append(success);
        sb.append(", ").append(at);

        sb.append(")");
        return sb.toString();
    }
}
