/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageBases implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String slug;
    private final String name;
    private final String description;
    private final Integer sortOrder;
    private final Boolean isLocked;

    public MessageBases(MessageBases value) {
        this.id = value.id;
        this.slug = value.slug;
        this.name = value.name;
        this.description = value.description;
        this.sortOrder = value.sortOrder;
        this.isLocked = value.isLocked;
    }

    public MessageBases(
        Long id,
        String slug,
        String name,
        String description,
        Integer sortOrder,
        Boolean isLocked
    ) {
        this.id = id;
        this.slug = slug;
        this.name = name;
        this.description = description;
        this.sortOrder = sortOrder;
        this.isLocked = isLocked;
    }

    /**
     * Getter for <code>public.message_bases.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.message_bases.slug</code>.
     */
    public String getSlug() {
        return this.slug;
    }

    /**
     * Getter for <code>public.message_bases.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.message_bases.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Getter for <code>public.message_bases.sort_order</code>.
     */
    public Integer getSortOrder() {
        return this.sortOrder;
    }

    /**
     * Getter for <code>public.message_bases.is_locked</code>.
     */
    public Boolean getIsLocked() {
        return this.isLocked;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MessageBases other = (MessageBases) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.slug == null) {
            if (other.slug != null)
                return false;
        }
        else if (!this.slug.equals(other.slug))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.sortOrder == null) {
            if (other.sortOrder != null)
                return false;
        }
        else if (!this.sortOrder.equals(other.sortOrder))
            return false;
        if (this.isLocked == null) {
            if (other.isLocked != null)
                return false;
        }
        else if (!this.isLocked.equals(other.isLocked))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.slug == null) ? 0 : this.slug.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.sortOrder == null) ? 0 : this.sortOrder.hashCode());
        result = prime * result + ((this.isLocked == null) ? 0 : this.isLocked.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MessageBases (");

        sb.append(id);
        sb.append(", ").append(slug);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(sortOrder);
        sb.append(", ").append(isLocked);

        sb.append(")");
        return sb.toString();
    }
}
