/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Netmail implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long fromId;
    private final Long toId;
    private final String subject;
    private final String body;
    private final OffsetDateTime sentAt;
    private final OffsetDateTime readAt;
    private final Boolean fromDeleted;
    private final Boolean toDeleted;

    public Netmail(Netmail value) {
        this.id = value.id;
        this.fromId = value.fromId;
        this.toId = value.toId;
        this.subject = value.subject;
        this.body = value.body;
        this.sentAt = value.sentAt;
        this.readAt = value.readAt;
        this.fromDeleted = value.fromDeleted;
        this.toDeleted = value.toDeleted;
    }

    public Netmail(
        Long id,
        Long fromId,
        Long toId,
        String subject,
        String body,
        OffsetDateTime sentAt,
        OffsetDateTime readAt,
        Boolean fromDeleted,
        Boolean toDeleted
    ) {
        this.id = id;
        this.fromId = fromId;
        this.toId = toId;
        this.subject = subject;
        this.body = body;
        this.sentAt = sentAt;
        this.readAt = readAt;
        this.fromDeleted = fromDeleted;
        this.toDeleted = toDeleted;
    }

    /**
     * Getter for <code>public.netmail.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.netmail.from_id</code>.
     */
    public Long getFromId() {
        return this.fromId;
    }

    /**
     * Getter for <code>public.netmail.to_id</code>.
     */
    public Long getToId() {
        return this.toId;
    }

    /**
     * Getter for <code>public.netmail.subject</code>.
     */
    public String getSubject() {
        return this.subject;
    }

    /**
     * Getter for <code>public.netmail.body</code>.
     */
    public String getBody() {
        return this.body;
    }

    /**
     * Getter for <code>public.netmail.sent_at</code>.
     */
    public OffsetDateTime getSentAt() {
        return this.sentAt;
    }

    /**
     * Getter for <code>public.netmail.read_at</code>.
     */
    public OffsetDateTime getReadAt() {
        return this.readAt;
    }

    /**
     * Getter for <code>public.netmail.from_deleted</code>.
     */
    public Boolean getFromDeleted() {
        return this.fromDeleted;
    }

    /**
     * Getter for <code>public.netmail.to_deleted</code>.
     */
    public Boolean getToDeleted() {
        return this.toDeleted;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Netmail other = (Netmail) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.fromId == null) {
            if (other.fromId != null)
                return false;
        }
        else if (!this.fromId.equals(other.fromId))
            return false;
        if (this.toId == null) {
            if (other.toId != null)
                return false;
        }
        else if (!this.toId.equals(other.toId))
            return false;
        if (this.subject == null) {
            if (other.subject != null)
                return false;
        }
        else if (!this.subject.equals(other.subject))
            return false;
        if (this.body == null) {
            if (other.body != null)
                return false;
        }
        else if (!this.body.equals(other.body))
            return false;
        if (this.sentAt == null) {
            if (other.sentAt != null)
                return false;
        }
        else if (!this.sentAt.equals(other.sentAt))
            return false;
        if (this.readAt == null) {
            if (other.readAt != null)
                return false;
        }
        else if (!this.readAt.equals(other.readAt))
            return false;
        if (this.fromDeleted == null) {
            if (other.fromDeleted != null)
                return false;
        }
        else if (!this.fromDeleted.equals(other.fromDeleted))
            return false;
        if (this.toDeleted == null) {
            if (other.toDeleted != null)
                return false;
        }
        else if (!this.toDeleted.equals(other.toDeleted))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.fromId == null) ? 0 : this.fromId.hashCode());
        result = prime * result + ((this.toId == null) ? 0 : this.toId.hashCode());
        result = prime * result + ((this.subject == null) ? 0 : this.subject.hashCode());
        result = prime * result + ((this.body == null) ? 0 : this.body.hashCode());
        result = prime * result + ((this.sentAt == null) ? 0 : this.sentAt.hashCode());
        result = prime * result + ((this.readAt == null) ? 0 : this.readAt.hashCode());
        result = prime * result + ((this.fromDeleted == null) ? 0 : this.fromDeleted.hashCode());
        result = prime * result + ((this.toDeleted == null) ? 0 : this.toDeleted.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Netmail (");

        sb.append(id);
        sb.append(", ").append(fromId);
        sb.append(", ").append(toId);
        sb.append(", ").append(subject);
        sb.append(", ").append(body);
        sb.append(", ").append(sentAt);
        sb.append(", ").append(readAt);
        sb.append(", ").append(fromDeleted);
        sb.append(", ").append(toDeleted);

        sb.append(")");
        return sb.toString();
    }
}
