/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Oneliners implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long authorId;
    private final String body;
    private final OffsetDateTime postedAt;

    public Oneliners(Oneliners value) {
        this.id = value.id;
        this.authorId = value.authorId;
        this.body = value.body;
        this.postedAt = value.postedAt;
    }

    public Oneliners(
        Long id,
        Long authorId,
        String body,
        OffsetDateTime postedAt
    ) {
        this.id = id;
        this.authorId = authorId;
        this.body = body;
        this.postedAt = postedAt;
    }

    /**
     * Getter for <code>public.oneliners.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.oneliners.author_id</code>.
     */
    public Long getAuthorId() {
        return this.authorId;
    }

    /**
     * Getter for <code>public.oneliners.body</code>.
     */
    public String getBody() {
        return this.body;
    }

    /**
     * Getter for <code>public.oneliners.posted_at</code>.
     */
    public OffsetDateTime getPostedAt() {
        return this.postedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Oneliners other = (Oneliners) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.authorId == null) {
            if (other.authorId != null)
                return false;
        }
        else if (!this.authorId.equals(other.authorId))
            return false;
        if (this.body == null) {
            if (other.body != null)
                return false;
        }
        else if (!this.body.equals(other.body))
            return false;
        if (this.postedAt == null) {
            if (other.postedAt != null)
                return false;
        }
        else if (!this.postedAt.equals(other.postedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.authorId == null) ? 0 : this.authorId.hashCode());
        result = prime * result + ((this.body == null) ? 0 : this.body.hashCode());
        result = prime * result + ((this.postedAt == null) ? 0 : this.postedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Oneliners (");

        sb.append(id);
        sb.append(", ").append(authorId);
        sb.append(", ").append(body);
        sb.append(", ").append(postedAt);

        sb.append(")");
        return sb.toString();
    }
}
