/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PollVotes implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long pollId;
    private final Long optionId;
    private final Long userId;
    private final OffsetDateTime votedAt;

    public PollVotes(PollVotes value) {
        this.pollId = value.pollId;
        this.optionId = value.optionId;
        this.userId = value.userId;
        this.votedAt = value.votedAt;
    }

    public PollVotes(
        Long pollId,
        Long optionId,
        Long userId,
        OffsetDateTime votedAt
    ) {
        this.pollId = pollId;
        this.optionId = optionId;
        this.userId = userId;
        this.votedAt = votedAt;
    }

    /**
     * Getter for <code>public.poll_votes.poll_id</code>.
     */
    public Long getPollId() {
        return this.pollId;
    }

    /**
     * Getter for <code>public.poll_votes.option_id</code>.
     */
    public Long getOptionId() {
        return this.optionId;
    }

    /**
     * Getter for <code>public.poll_votes.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.poll_votes.voted_at</code>.
     */
    public OffsetDateTime getVotedAt() {
        return this.votedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PollVotes other = (PollVotes) obj;
        if (this.pollId == null) {
            if (other.pollId != null)
                return false;
        }
        else if (!this.pollId.equals(other.pollId))
            return false;
        if (this.optionId == null) {
            if (other.optionId != null)
                return false;
        }
        else if (!this.optionId.equals(other.optionId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.votedAt == null) {
            if (other.votedAt != null)
                return false;
        }
        else if (!this.votedAt.equals(other.votedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.pollId == null) ? 0 : this.pollId.hashCode());
        result = prime * result + ((this.optionId == null) ? 0 : this.optionId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.votedAt == null) ? 0 : this.votedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PollVotes (");

        sb.append(pollId);
        sb.append(", ").append(optionId);
        sb.append(", ").append(userId);
        sb.append(", ").append(votedAt);

        sb.append(")");
        return sb.toString();
    }
}
