/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Schemas implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String slug;
    private final Integer version;
    private final String label;
    private final String description;
    private final JSONB definition;
    private final JSONB presentation;
    private final String status;
    private final Long createdBy;
    private final OffsetDateTime createdAt;
    private final OffsetDateTime updatedAt;

    public Schemas(Schemas value) {
        this.id = value.id;
        this.slug = value.slug;
        this.version = value.version;
        this.label = value.label;
        this.description = value.description;
        this.definition = value.definition;
        this.presentation = value.presentation;
        this.status = value.status;
        this.createdBy = value.createdBy;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Schemas(
        Long id,
        String slug,
        Integer version,
        String label,
        String description,
        JSONB definition,
        JSONB presentation,
        String status,
        Long createdBy,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
    ) {
        this.id = id;
        this.slug = slug;
        this.version = version;
        this.label = label;
        this.description = description;
        this.definition = definition;
        this.presentation = presentation;
        this.status = status;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.schemas.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.schemas.slug</code>.
     */
    public String getSlug() {
        return this.slug;
    }

    /**
     * Getter for <code>public.schemas.version</code>.
     */
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Getter for <code>public.schemas.label</code>.
     */
    public String getLabel() {
        return this.label;
    }

    /**
     * Getter for <code>public.schemas.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Getter for <code>public.schemas.definition</code>.
     */
    public JSONB getDefinition() {
        return this.definition;
    }

    /**
     * Getter for <code>public.schemas.presentation</code>.
     */
    public JSONB getPresentation() {
        return this.presentation;
    }

    /**
     * Getter for <code>public.schemas.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Getter for <code>public.schemas.created_by</code>.
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Getter for <code>public.schemas.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>public.schemas.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Schemas other = (Schemas) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.slug == null) {
            if (other.slug != null)
                return false;
        }
        else if (!this.slug.equals(other.slug))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        if (this.label == null) {
            if (other.label != null)
                return false;
        }
        else if (!this.label.equals(other.label))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.definition == null) {
            if (other.definition != null)
                return false;
        }
        else if (!this.definition.equals(other.definition))
            return false;
        if (this.presentation == null) {
            if (other.presentation != null)
                return false;
        }
        else if (!this.presentation.equals(other.presentation))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.slug == null) ? 0 : this.slug.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.label == null) ? 0 : this.label.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.definition == null) ? 0 : this.definition.hashCode());
        result = prime * result + ((this.presentation == null) ? 0 : this.presentation.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Schemas (");

        sb.append(id);
        sb.append(", ").append(slug);
        sb.append(", ").append(version);
        sb.append(", ").append(label);
        sb.append(", ").append(description);
        sb.append(", ").append(definition);
        sb.append(", ").append(presentation);
        sb.append(", ").append(status);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
