/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sessions implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String token;
    private final Long userId;
    private final OffsetDateTime createdAt;
    private final OffsetDateTime lastSeenAt;
    private final OffsetDateTime expiresAt;
    private final String ip;
    private final String ua;
    private final JSONB currentScreen;
    private final JSONB appState;

    public Sessions(Sessions value) {
        this.token = value.token;
        this.userId = value.userId;
        this.createdAt = value.createdAt;
        this.lastSeenAt = value.lastSeenAt;
        this.expiresAt = value.expiresAt;
        this.ip = value.ip;
        this.ua = value.ua;
        this.currentScreen = value.currentScreen;
        this.appState = value.appState;
    }

    public Sessions(
        String token,
        Long userId,
        OffsetDateTime createdAt,
        OffsetDateTime lastSeenAt,
        OffsetDateTime expiresAt,
        String ip,
        String ua,
        JSONB currentScreen,
        JSONB appState
    ) {
        this.token = token;
        this.userId = userId;
        this.createdAt = createdAt;
        this.lastSeenAt = lastSeenAt;
        this.expiresAt = expiresAt;
        this.ip = ip;
        this.ua = ua;
        this.currentScreen = currentScreen;
        this.appState = appState;
    }

    /**
     * Getter for <code>public.sessions.token</code>.
     */
    public String getToken() {
        return this.token;
    }

    /**
     * Getter for <code>public.sessions.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.sessions.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>public.sessions.last_seen_at</code>.
     */
    public OffsetDateTime getLastSeenAt() {
        return this.lastSeenAt;
    }

    /**
     * Getter for <code>public.sessions.expires_at</code>.
     */
    public OffsetDateTime getExpiresAt() {
        return this.expiresAt;
    }

    /**
     * Getter for <code>public.sessions.ip</code>.
     */
    public String getIp() {
        return this.ip;
    }

    /**
     * Getter for <code>public.sessions.ua</code>.
     */
    public String getUa() {
        return this.ua;
    }

    /**
     * Getter for <code>public.sessions.current_screen</code>.
     */
    public JSONB getCurrentScreen() {
        return this.currentScreen;
    }

    /**
     * Getter for <code>public.sessions.app_state</code>.
     */
    public JSONB getAppState() {
        return this.appState;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Sessions other = (Sessions) obj;
        if (this.token == null) {
            if (other.token != null)
                return false;
        }
        else if (!this.token.equals(other.token))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.lastSeenAt == null) {
            if (other.lastSeenAt != null)
                return false;
        }
        else if (!this.lastSeenAt.equals(other.lastSeenAt))
            return false;
        if (this.expiresAt == null) {
            if (other.expiresAt != null)
                return false;
        }
        else if (!this.expiresAt.equals(other.expiresAt))
            return false;
        if (this.ip == null) {
            if (other.ip != null)
                return false;
        }
        else if (!this.ip.equals(other.ip))
            return false;
        if (this.ua == null) {
            if (other.ua != null)
                return false;
        }
        else if (!this.ua.equals(other.ua))
            return false;
        if (this.currentScreen == null) {
            if (other.currentScreen != null)
                return false;
        }
        else if (!this.currentScreen.equals(other.currentScreen))
            return false;
        if (this.appState == null) {
            if (other.appState != null)
                return false;
        }
        else if (!this.appState.equals(other.appState))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.token == null) ? 0 : this.token.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.lastSeenAt == null) ? 0 : this.lastSeenAt.hashCode());
        result = prime * result + ((this.expiresAt == null) ? 0 : this.expiresAt.hashCode());
        result = prime * result + ((this.ip == null) ? 0 : this.ip.hashCode());
        result = prime * result + ((this.ua == null) ? 0 : this.ua.hashCode());
        result = prime * result + ((this.currentScreen == null) ? 0 : this.currentScreen.hashCode());
        result = prime * result + ((this.appState == null) ? 0 : this.appState.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Sessions (");

        sb.append(token);
        sb.append(", ").append(userId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(lastSeenAt);
        sb.append(", ").append(expiresAt);
        sb.append(", ").append(ip);
        sb.append(", ").append(ua);
        sb.append(", ").append(currentScreen);
        sb.append(", ").append(appState);

        sb.append(")");
        return sb.toString();
    }
}
