/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SysopNotes implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long subjectId;
    private final Long authorId;
    private final String body;
    private final OffsetDateTime createdAt;

    public SysopNotes(SysopNotes value) {
        this.id = value.id;
        this.subjectId = value.subjectId;
        this.authorId = value.authorId;
        this.body = value.body;
        this.createdAt = value.createdAt;
    }

    public SysopNotes(
        Long id,
        Long subjectId,
        Long authorId,
        String body,
        OffsetDateTime createdAt
    ) {
        this.id = id;
        this.subjectId = subjectId;
        this.authorId = authorId;
        this.body = body;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.sysop_notes.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.sysop_notes.subject_id</code>.
     */
    public Long getSubjectId() {
        return this.subjectId;
    }

    /**
     * Getter for <code>public.sysop_notes.author_id</code>.
     */
    public Long getAuthorId() {
        return this.authorId;
    }

    /**
     * Getter for <code>public.sysop_notes.body</code>.
     */
    public String getBody() {
        return this.body;
    }

    /**
     * Getter for <code>public.sysop_notes.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SysopNotes other = (SysopNotes) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.subjectId == null) {
            if (other.subjectId != null)
                return false;
        }
        else if (!this.subjectId.equals(other.subjectId))
            return false;
        if (this.authorId == null) {
            if (other.authorId != null)
                return false;
        }
        else if (!this.authorId.equals(other.authorId))
            return false;
        if (this.body == null) {
            if (other.body != null)
                return false;
        }
        else if (!this.body.equals(other.body))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.subjectId == null) ? 0 : this.subjectId.hashCode());
        result = prime * result + ((this.authorId == null) ? 0 : this.authorId.hashCode());
        result = prime * result + ((this.body == null) ? 0 : this.body.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysopNotes (");

        sb.append(id);
        sb.append(", ").append(subjectId);
        sb.append(", ").append(authorId);
        sb.append(", ").append(body);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
