/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SysopActions implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long actorId;
    private final String action;
    private final JSONB payload;
    private final OffsetDateTime at;

    public SysopActions(SysopActions value) {
        this.id = value.id;
        this.actorId = value.actorId;
        this.action = value.action;
        this.payload = value.payload;
        this.at = value.at;
    }

    public SysopActions(
        Long id,
        Long actorId,
        String action,
        JSONB payload,
        OffsetDateTime at
    ) {
        this.id = id;
        this.actorId = actorId;
        this.action = action;
        this.payload = payload;
        this.at = at;
    }

    /**
     * Getter for <code>public.sysop_actions.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.sysop_actions.actor_id</code>.
     */
    public Long getActorId() {
        return this.actorId;
    }

    /**
     * Getter for <code>public.sysop_actions.action</code>.
     */
    public String getAction() {
        return this.action;
    }

    /**
     * Getter for <code>public.sysop_actions.payload</code>.
     */
    public JSONB getPayload() {
        return this.payload;
    }

    /**
     * Getter for <code>public.sysop_actions.at</code>.
     */
    public OffsetDateTime getAt() {
        return this.at;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SysopActions other = (SysopActions) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.actorId == null) {
            if (other.actorId != null)
                return false;
        }
        else if (!this.actorId.equals(other.actorId))
            return false;
        if (this.action == null) {
            if (other.action != null)
                return false;
        }
        else if (!this.action.equals(other.action))
            return false;
        if (this.payload == null) {
            if (other.payload != null)
                return false;
        }
        else if (!this.payload.equals(other.payload))
            return false;
        if (this.at == null) {
            if (other.at != null)
                return false;
        }
        else if (!this.at.equals(other.at))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.actorId == null) ? 0 : this.actorId.hashCode());
        result = prime * result + ((this.action == null) ? 0 : this.action.hashCode());
        result = prime * result + ((this.payload == null) ? 0 : this.payload.hashCode());
        result = prime * result + ((this.at == null) ? 0 : this.at.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysopActions (");

        sb.append(id);
        sb.append(", ").append(actorId);
        sb.append(", ").append(action);
        sb.append(", ").append(payload);
        sb.append(", ").append(at);

        sb.append(")");
        return sb.toString();
    }
}
