/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ThreadRead implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long userId;
    private final Long threadId;
    private final OffsetDateTime lastReadAt;

    public ThreadRead(ThreadRead value) {
        this.userId = value.userId;
        this.threadId = value.threadId;
        this.lastReadAt = value.lastReadAt;
    }

    public ThreadRead(
        Long userId,
        Long threadId,
        OffsetDateTime lastReadAt
    ) {
        this.userId = userId;
        this.threadId = threadId;
        this.lastReadAt = lastReadAt;
    }

    /**
     * Getter for <code>public.thread_read.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.thread_read.thread_id</code>.
     */
    public Long getThreadId() {
        return this.threadId;
    }

    /**
     * Getter for <code>public.thread_read.last_read_at</code>.
     */
    public OffsetDateTime getLastReadAt() {
        return this.lastReadAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ThreadRead other = (ThreadRead) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.threadId == null) {
            if (other.threadId != null)
                return false;
        }
        else if (!this.threadId.equals(other.threadId))
            return false;
        if (this.lastReadAt == null) {
            if (other.lastReadAt != null)
                return false;
        }
        else if (!this.lastReadAt.equals(other.lastReadAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.threadId == null) ? 0 : this.threadId.hashCode());
        result = prime * result + ((this.lastReadAt == null) ? 0 : this.lastReadAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ThreadRead (");

        sb.append(userId);
        sb.append(", ").append(threadId);
        sb.append(", ").append(lastReadAt);

        sb.append(")");
        return sb.toString();
    }
}
