/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Threads implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Long baseId;
    private final String subject;
    private final Long authorId;
    private final OffsetDateTime createdAt;
    private final OffsetDateTime lastPostAt;
    private final Integer postCount;
    private final Boolean isPinned;
    private final Boolean isLocked;

    public Threads(Threads value) {
        this.id = value.id;
        this.baseId = value.baseId;
        this.subject = value.subject;
        this.authorId = value.authorId;
        this.createdAt = value.createdAt;
        this.lastPostAt = value.lastPostAt;
        this.postCount = value.postCount;
        this.isPinned = value.isPinned;
        this.isLocked = value.isLocked;
    }

    public Threads(
        Long id,
        Long baseId,
        String subject,
        Long authorId,
        OffsetDateTime createdAt,
        OffsetDateTime lastPostAt,
        Integer postCount,
        Boolean isPinned,
        Boolean isLocked
    ) {
        this.id = id;
        this.baseId = baseId;
        this.subject = subject;
        this.authorId = authorId;
        this.createdAt = createdAt;
        this.lastPostAt = lastPostAt;
        this.postCount = postCount;
        this.isPinned = isPinned;
        this.isLocked = isLocked;
    }

    /**
     * Getter for <code>public.threads.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.threads.base_id</code>.
     */
    public Long getBaseId() {
        return this.baseId;
    }

    /**
     * Getter for <code>public.threads.subject</code>.
     */
    public String getSubject() {
        return this.subject;
    }

    /**
     * Getter for <code>public.threads.author_id</code>.
     */
    public Long getAuthorId() {
        return this.authorId;
    }

    /**
     * Getter for <code>public.threads.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>public.threads.last_post_at</code>.
     */
    public OffsetDateTime getLastPostAt() {
        return this.lastPostAt;
    }

    /**
     * Getter for <code>public.threads.post_count</code>.
     */
    public Integer getPostCount() {
        return this.postCount;
    }

    /**
     * Getter for <code>public.threads.is_pinned</code>.
     */
    public Boolean getIsPinned() {
        return this.isPinned;
    }

    /**
     * Getter for <code>public.threads.is_locked</code>.
     */
    public Boolean getIsLocked() {
        return this.isLocked;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Threads other = (Threads) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.baseId == null) {
            if (other.baseId != null)
                return false;
        }
        else if (!this.baseId.equals(other.baseId))
            return false;
        if (this.subject == null) {
            if (other.subject != null)
                return false;
        }
        else if (!this.subject.equals(other.subject))
            return false;
        if (this.authorId == null) {
            if (other.authorId != null)
                return false;
        }
        else if (!this.authorId.equals(other.authorId))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.lastPostAt == null) {
            if (other.lastPostAt != null)
                return false;
        }
        else if (!this.lastPostAt.equals(other.lastPostAt))
            return false;
        if (this.postCount == null) {
            if (other.postCount != null)
                return false;
        }
        else if (!this.postCount.equals(other.postCount))
            return false;
        if (this.isPinned == null) {
            if (other.isPinned != null)
                return false;
        }
        else if (!this.isPinned.equals(other.isPinned))
            return false;
        if (this.isLocked == null) {
            if (other.isLocked != null)
                return false;
        }
        else if (!this.isLocked.equals(other.isLocked))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.baseId == null) ? 0 : this.baseId.hashCode());
        result = prime * result + ((this.subject == null) ? 0 : this.subject.hashCode());
        result = prime * result + ((this.authorId == null) ? 0 : this.authorId.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.lastPostAt == null) ? 0 : this.lastPostAt.hashCode());
        result = prime * result + ((this.postCount == null) ? 0 : this.postCount.hashCode());
        result = prime * result + ((this.isPinned == null) ? 0 : this.isPinned.hashCode());
        result = prime * result + ((this.isLocked == null) ? 0 : this.isLocked.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Threads (");

        sb.append(id);
        sb.append(", ").append(baseId);
        sb.append(", ").append(subject);
        sb.append(", ").append(authorId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(lastPostAt);
        sb.append(", ").append(postCount);
        sb.append(", ").append(isPinned);
        sb.append(", ").append(isLocked);

        sb.append(")");
        return sb.toString();
    }
}
