/*
 * This file is generated by jOOQ.
 */
package io.aeyer.voidcore.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserAchievements implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long userId;
    private final Long achievementId;
    private final OffsetDateTime awardedAt;

    public UserAchievements(UserAchievements value) {
        this.userId = value.userId;
        this.achievementId = value.achievementId;
        this.awardedAt = value.awardedAt;
    }

    public UserAchievements(
        Long userId,
        Long achievementId,
        OffsetDateTime awardedAt
    ) {
        this.userId = userId;
        this.achievementId = achievementId;
        this.awardedAt = awardedAt;
    }

    /**
     * Getter for <code>public.user_achievements.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>public.user_achievements.achievement_id</code>.
     */
    public Long getAchievementId() {
        return this.achievementId;
    }

    /**
     * Getter for <code>public.user_achievements.awarded_at</code>.
     */
    public OffsetDateTime getAwardedAt() {
        return this.awardedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserAchievements other = (UserAchievements) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.achievementId == null) {
            if (other.achievementId != null)
                return false;
        }
        else if (!this.achievementId.equals(other.achievementId))
            return false;
        if (this.awardedAt == null) {
            if (other.awardedAt != null)
                return false;
        }
        else if (!this.awardedAt.equals(other.awardedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.achievementId == null) ? 0 : this.achievementId.hashCode());
        result = prime * result + ((this.awardedAt == null) ? 0 : this.awardedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserAchievements (");

        sb.append(userId);
        sb.append(", ").append(achievementId);
        sb.append(", ").append(awardedAt);

        sb.append(")");
        return sb.toString();
    }
}
